#![cfg_attr(rustfmt, rustfmt_skip)]

valid!(literal_zero, "int main(void) { return !((0 == (0)) && (sizeof(0) == sizeof(int)) && (((0) - (0) - 1 < 0) == 1)); }", 0, "");
valid!(literal_decimal, "int main(void) { return !((42 == (42)) && (sizeof(42) == sizeof(int)) && (((42) - (42) - 1 < 0) == 1)); }", 0, "");
valid!(literal_int_max, "int main(void) { return !((2147483647 == (2147483647)) && (sizeof(2147483647) == sizeof(int)) && (((2147483647) - (2147483647) - 1 < 0) == 1)); }", 0, "");
valid!(literal_decimal_above_int_max, "int main(void) { return !((2147483648 == (2147483648ul)) && (sizeof(2147483648) == sizeof(unsigned long)) && (((2147483648) - (2147483648) - 1 < 0) == 0)); }", 0, "");
valid!(literal_octal, "int main(void) { return !((010 == (8)) && (sizeof(010) == sizeof(int)) && (((010) - (010) - 1 < 0) == 1)); }", 0, "");
valid!(literal_octal_max, "int main(void) { return !((017777777777 == (2147483647)) && (sizeof(017777777777) == sizeof(int)) && (((017777777777) - (017777777777) - 1 < 0) == 1)); }", 0, "");
valid!(literal_hexadecimal, "int main(void) { return !((0x10 == (16)) && (sizeof(0x10) == sizeof(int)) && (((0x10) - (0x10) - 1 < 0) == 1)); }", 0, "");
valid!(literal_hexadecimal_upper, "int main(void) { return !((0XFF == (255)) && (sizeof(0XFF) == sizeof(int)) && (((0XFF) - (0XFF) - 1 < 0) == 1)); }", 0, "");
valid!(literal_hexadecimal_above_int_max, "int main(void) { return !((0x80000000 == (2147483648u)) && (sizeof(0x80000000) == sizeof(unsigned int)) && (((0x80000000) - (0x80000000) - 1 < 0) == 0)); }", 0, "");
valid!(literal_octal_above_int_max, "int main(void) { return !((020000000000 == (2147483648u)) && (sizeof(020000000000) == sizeof(unsigned int)) && (((020000000000) - (020000000000) - 1 < 0) == 0)); }", 0, "");
valid!(literal_unsigned_suffix, "int main(void) { return !((1u == (1u)) && (sizeof(1u) == sizeof(unsigned int)) && (((1u) - (1u) - 1 < 0) == 0)); }", 0, "");
valid!(literal_unsigned_suffix_upper, "int main(void) { return !((1U == (1u)) && (sizeof(1U) == sizeof(unsigned int)) && (((1U) - (1U) - 1 < 0) == 0)); }", 0, "");
valid!(literal_long_suffix, "int main(void) { return !((1l == (1l)) && (sizeof(1l) == sizeof(long)) && (((1l) - (1l) - 1 < 0) == 1)); }", 0, "");
valid!(literal_long_suffix_upper, "int main(void) { return !((1L == (1l)) && (sizeof(1L) == sizeof(long)) && (((1L) - (1L) - 1 < 0) == 1)); }", 0, "");
valid!(literal_unsigned_long_suffix, "int main(void) { return !((1ul == (1ul)) && (sizeof(1ul) == sizeof(unsigned long)) && (((1ul) - (1ul) - 1 < 0) == 0)); }", 0, "");
valid!(literal_long_unsigned_suffix, "int main(void) { return !((1lu == (1ul)) && (sizeof(1lu) == sizeof(unsigned long)) && (((1lu) - (1lu) - 1 < 0) == 0)); }", 0, "");
valid!(literal_unsigned_long_suffix_upper, "int main(void) { return !((1UL == (1ul)) && (sizeof(1UL) == sizeof(unsigned long)) && (((1UL) - (1UL) - 1 < 0) == 0)); }", 0, "");
valid!(literal_double, "int main(void) { return !((1.5 == (1.5)) && (sizeof(1.5) == sizeof(double))); }", 0, "");
valid!(literal_double_leading_dot, "int main(void) { return !((.5 == (0.5)) && (sizeof(.5) == sizeof(double))); }", 0, "");
valid!(literal_double_exponent, "int main(void) { return !((1e3 == (1000.0)) && (sizeof(1e3) == sizeof(double))); }", 0, "");
valid!(literal_double_negative_exponent, "int main(void) { return !((1e-3 == (0.001)) && (sizeof(1e-3) == sizeof(double))); }", 0, "");
valid!(literal_float_suffix, "int main(void) { return !((1.5f == (1.5f)) && (sizeof(1.5f) == sizeof(float))); }", 0, "");
valid!(literal_float_suffix_upper, "int main(void) { return !((1.5F == (1.5f)) && (sizeof(1.5F) == sizeof(float))); }", 0, "");
valid!(literal_long_double_suffix, "int main(void) { return !((1.5l == (1.5l)) && (sizeof(1.5l) == sizeof(long double))); }", 0, "");
valid!(literal_char, "int main(void) { return !(('a' == (97)) && (sizeof('a') == sizeof(int)) && ((('a') - ('a') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_digit, "int main(void) { return !(('0' == (48)) && (sizeof('0') == sizeof(int)) && ((('0') - ('0') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_newline, "int main(void) { return !(('\\n' == (10)) && (sizeof('\\n') == sizeof(int)) && ((('\\n') - ('\\n') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_tab, "int main(void) { return !(('\\t' == (9)) && (sizeof('\\t') == sizeof(int)) && ((('\\t') - ('\\t') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_null, "int main(void) { return !(('\\0' == (0)) && (sizeof('\\0') == sizeof(int)) && ((('\\0') - ('\\0') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_backslash, "int main(void) { return !(('\\\\' == (92)) && (sizeof('\\\\') == sizeof(int)) && ((('\\\\') - ('\\\\') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_quote, "int main(void) { return !(('\\'' == (39)) && (sizeof('\\'') == sizeof(int)) && ((('\\'') - ('\\'') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_bell, "int main(void) { return !(('\\a' == (7)) && (sizeof('\\a') == sizeof(int)) && ((('\\a') - ('\\a') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_backspace, "int main(void) { return !(('\\b' == (8)) && (sizeof('\\b') == sizeof(int)) && ((('\\b') - ('\\b') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_form_feed, "int main(void) { return !(('\\f' == (12)) && (sizeof('\\f') == sizeof(int)) && ((('\\f') - ('\\f') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_carriage_return, "int main(void) { return !(('\\r' == (13)) && (sizeof('\\r') == sizeof(int)) && ((('\\r') - ('\\r') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_vertical_tab, "int main(void) { return !(('\\v' == (11)) && (sizeof('\\v') == sizeof(int)) && ((('\\v') - ('\\v') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_octal, "int main(void) { return !(('\\101' == (65)) && (sizeof('\\101') == sizeof(int)) && ((('\\101') - ('\\101') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_hexadecimal, "int main(void) { return !(('\\x41' == (65)) && (sizeof('\\x41') == sizeof(int)) && ((('\\x41') - ('\\x41') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_is_sign_extended, "int main(void) { return !(('\\377' == (-1)) && (sizeof('\\377') == sizeof(int)) && ((('\\377') - ('\\377') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_hexadecimal_is_sign_extended, "int main(void) { return !(('\\xff' == (-1)) && (sizeof('\\xff') == sizeof(int)) && ((('\\xff') - ('\\xff') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_multi_is_packed, "int main(void) { return !(('ab' == (24930)) && (sizeof('ab') == sizeof(int)) && ((('ab') - ('ab') - 1 < 0) == 1)); }", 0, "");
valid!(literal_wide_char, "int main(void) { return !((L'a' == (97)) && (sizeof(L'a') == sizeof(int)) && (((L'a') - (L'a') - 1 < 0) == 1)); }", 0, "");
valid!(literal_wide_char_is_not_sign_extended, "int main(void) { return !((L'\\xff' == (255)) && (sizeof(L'\\xff') == sizeof(int)) && (((L'\\xff') - (L'\\xff') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_octal_escape_at_range_limit, "int main(void) { return !(('\\377' == (-1)) && (sizeof('\\377') == sizeof(int)) && ((('\\377') - ('\\377') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_hex_escape_at_range_limit, "int main(void) { return !(('\\xff' == (-1)) && (sizeof('\\xff') == sizeof(int)) && ((('\\xff') - ('\\xff') - 1 < 0) == 1)); }", 0, "");
valid!(literal_wide_char_hex_escape_at_range_limit, "int main(void) { return !((L'\\xffffffff' == (-1)) && (sizeof(L'\\xffffffff') == sizeof(int)) && (((L'\\xffffffff') - (L'\\xffffffff') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_hex_escape_extra_leading_zeros, "int main(void) { return !(('\\x0000000000041' == (65)) && (sizeof('\\x0000000000041') == sizeof(int)) && ((('\\x0000000000041') - ('\\x0000000000041') - 1 < 0) == 1)); }", 0, "");
valid!(literal_wide_char_hex_escape_above_char_range, "int main(void) { return !((L'\\x100' == (256)) && (sizeof(L'\\x100') == sizeof(int)) && (((L'\\x100') - (L'\\x100') - 1 < 0) == 1)); }", 0, "");
valid!(literal_wide_char_hex_escape_uses_wchar_range, "int main(void) { return !((L'\\xffff' == (65535)) && (sizeof(L'\\xffff') == sizeof(int)) && (((L'\\xffff') - (L'\\xffff') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_question_mark, "int main(void) { return !(('\\?' == (63)) && (sizeof('\\?') == sizeof(int)) && ((('\\?') - ('\\?') - 1 < 0) == 1)); }", 0, "");
valid!(literal_char_escape_double_quote, "int main(void) { return !(('\\\"' == (34)) && (sizeof('\\\"') == sizeof(int)) && ((('\\\"') - ('\\\"') - 1 < 0) == 1)); }", 0, "");
invalid!(literal_char_hex_escape_no_digits, "int value = '\\x';", &["error: \\x used with no following hex digits"]);
invalid!(literal_char_hex_escape_bad_digit, "int value = '\\xg';", &["error: \\x used with no following hex digits"]);
invalid!(literal_octal_with_digit_eight, "int value = 08;", &["error: invalid digit \"8\" in octal constant"]);
invalid!(literal_octal_with_digit_nine_after_valid_ones, "int value = 0129u;", &["error: invalid digit \"9\" in octal constant"]);
invalid!(literal_wide_char_hex_escape_no_digits, "int value = L'\\x';", &["error: \\x used with no following hex digits"]);
invalid!(literal_char_unknown_escape, "int value = '\\q';", &["error: unknown escape sequence: '\\q'"]);
invalid!(literal_char_escape_e_is_unknown, "int value = '\\e';", &["error: unknown escape sequence: '\\e'"]);
invalid!(literal_char_octal_escape_out_of_range, "int value = '\\777';", &["error: escape sequence is out of range for the character type"]);
invalid!(literal_char_octal_escape_just_out_of_range, "int value = '\\400';", &["error: escape sequence is out of range for the character type"]);
invalid!(literal_char_hex_escape_out_of_range, "int value = '\\x100';", &["error: escape sequence is out of range for the character type"]);
invalid!(literal_char_hex_escape_far_out_of_range, "int value = '\\x1ff';", &["error: escape sequence is out of range for the character type"]);
invalid!(literal_multi_char_escape_out_of_range, "int value = 'a\\x100';", &["error: escape sequence is out of range for the character type"]);
invalid!(literal_char_hex_escape_grossly_out_of_range, "int value = '\\x100000041';", &["error: escape sequence is out of range for the character type"]);
invalid!(literal_wide_char_hex_escape_grossly_out_of_range, "int value = L'\\x100000041';", &["error: escape sequence is out of range for the character type"]);
invalid!(literal_above_unsigned_int_max, "int value = 0x100000000;", &["error: integer constant is too large for any integer type"]);
invalid!(literal_above_long_max, "int value = 0xffffffffffffffff;", &["error: integer constant is too large for any integer type"]);
invalid!(literal_unsigned_suffix_promotes, "int value = 4294967296u;", &["error: integer constant is too large for any integer type"]);
valid!(add_int, "int main(void) { return !(((1) + (2)) == (3)); }", 0, "");
valid!(sub_unsigned_wraps, "int main(void) { return !(((1u) - (2u)) == (4294967295u)); }", 0, "");
valid!(div_int, "int main(void) { return !(((7) / (2)) == (3)); }", 0, "");
valid!(div_negative_truncates_toward_zero, "int main(void) { return !(((-7) / (2)) == (-3)); }", 0, "");
valid!(rem_int, "int main(void) { return !(((7) % (2)) == (1)); }", 0, "");
valid!(rem_keeps_sign_of_dividend, "int main(void) { return !(((-7) % (2)) == (-1)); }", 0, "");
valid!(bitand_int, "int main(void) { return !(((6) & (3)) == (2)); }", 0, "");
valid!(bitor_int, "int main(void) { return !(((6) | (3)) == (7)); }", 0, "");
valid!(bitxor_int, "int main(void) { return !(((6) ^ (3)) == (5)); }", 0, "");
valid!(shift_left, "int main(void) { return !(((1) << (4)) == (16)); }", 0, "");
valid!(shift_left_into_sign_bit, "int main(void) { return !(((1) << (31)) == (-2147483648)); }", 0, "");
valid!(shift_right_is_arithmetic, "int main(void) { return !(((-8) >> (1)) == (-4)); }", 0, "");
valid!(shift_right_unsigned_is_logical, "int main(void) { return !(((2147483648u) >> (31)) == (1u)); }", 0, "");
valid!(shift_keeps_left_operand_type, "int main(void) { return !(((1l) << (1)) == (2l)); }", 0, "");
valid!(neg_int, "int main(void) { return !((-(1)) == (-1)); }", 0, "");
valid!(neg_double, "int main(void) { return !((-(1.5)) == (-1.5)); }", 0, "");
valid!(bitnot_int, "int main(void) { return !((~(0)) == (-1)); }", 0, "");
valid!(bitnot_unsigned, "int main(void) { return !((~(0u)) == (4294967295u)); }", 0, "");
valid!(convert_to_int, "int main(void) { return !(((int)(300l)) == (300)); }", 0, "");
valid!(convert_to_unsigned_long_is_32_bits_on_i386, "int main(void) { return !(((unsigned long)(-1)) == (4294967295ul)); }", 0, "");
valid!(convert_to_double, "int main(void) { return !(((double)(3)) == (3.0)); }", 0, "");
valid!(convert_from_double_truncates, "int main(void) { return !(((int)(3.9)) == (3)); }", 0, "");
valid!(unsigned_div, "int main(void) { return !(((7u) / (2u)) == (3u)); }", 0, "");
valid!(unsigned_rem, "int main(void) { return !(((7u) % (2u)) == (1u)); }", 0, "");
valid!(unsigned_mul_wraps_without_a_diagnostic, "int main(void) { return !(((65536u) * (65536u)) == (0u)); }", 0, "");
valid!(unsigned_bitor, "int main(void) { return !(((4026531840u) | (15u)) == (4026531855u)); }", 0, "");
valid!(unsigned_long_sub_wraps, "int main(void) { return !(((0ul) - (1ul)) == (4294967295ul)); }", 0, "");
valid!(double_sub, "int main(void) { return !(((1.5) - (0.25)) == (1.25)); }", 0, "");
valid!(double_mul, "int main(void) { return !(((1.5) * (2.0)) == (3.0)); }", 0, "");
valid!(long_double_add, "int main(void) { return !(((1.5l) + (1.5l)) == (3.0l)); }", 0, "");
valid!(neg_unsigned_wraps, "int main(void) { return !((-(1u)) == (4294967295u)); }", 0, "");
valid!(neg_long, "int main(void) { return !((-(-1l)) == (1l)); }", 0, "");
valid!(neg_floating_zero_keeps_its_sign, "int sprintf(char *, const char *, ...); int puts(const char *); int main(void) { char text[20]; sprintf(text, \"%.1f\", -0.0); puts(text); return 0; }", 0, "-0.0\n");
valid!(bitnot_long, "int main(void) { return !((~(0l)) == (-1l)); }", 0, "");
valid!(convert_to_a_narrow_integer_type, "int main(void) { return !(((char)(300)) == (44)); }", 0, "");
valid!(convert_to_unsigned_int_wraps, "int main(void) { return !(((unsigned int)(-1)) == (4294967295u)); }", 0, "");
valid!(convert_to_long_double, "int main(void) { return !(((long double)(3)) == (3.0l)); }", 0, "");
valid!(convert_to_float_rounds, "int main(void) { return !(((float)(16777217.0)) == (16777216.0f)); }", 0, "");
valid!(unsigned_int_shift_left, "int main(void) { return !(((1u) << (31)) == (2147483648u)); }", 0, "");
valid!(unsigned_long_shift_left, "int main(void) { return !(((1ul) << (4)) == (16ul)); }", 0, "");
valid!(long_shift_right_is_arithmetic, "int main(void) { return !(((-8l) >> (1)) == (-4l)); }", 0, "");
valid!(unsigned_long_shift_right_is_logical, "int main(void) { return !(((2147483648ul) >> (31)) == (1ul)); }", 0, "");
valid!(a_shift_narrows_to_the_width_of_its_type, "int main(void) { return !(((1l) << (31)) == (-2147483648l)); }", 0, "");
valid!(bitnot_unsigned_long, "int main(void) { return !((~(0ul)) == (4294967295ul)); }", 0, "");
valid!(double_div, "int main(void) { return !(((3.0) / (2.0)) == (1.5)); }", 0, "");
valid!(unsigned_add_wraps, "int main(void) { return !(((4294967295u) + (1u)) == (0u)); }", 0, "");
valid!(unsigned_bitxor, "int main(void) { return !(((6u) ^ (3u)) == (5u)); }", 0, "");
valid!(convert_an_unsigned_int_to_double, "int main(void) { return !(((double)(1u)) == (1.0)); }", 0, "");
valid!(convert_a_long_to_double, "int main(void) { return !(((double)(2l)) == (2.0)); }", 0, "");
valid!(convert_an_unsigned_long_to_double, "int main(void) { return !(((double)(3ul)) == (3.0)); }", 0, "");
invalid!(add_wraps, "enum { VALUE = (2147483647) + (1) };", &["error: integer overflow in constant expression"]);
invalid!(mul_wraps, "enum { VALUE = (65536) * (65536) };", &["error: integer overflow in constant expression"]);
invalid!(neg_wraps, "enum { VALUE = -((-2147483647 - 1)) };", &["error: integer overflow in constant expression"]);
invalid!(long_add_wraps_at_32_bits, "enum { VALUE = (2147483647l) + (1l) };", &["error: integer overflow in constant expression"]);
