#![cfg_attr(rustfmt, rustfmt_skip)]

valid!(tag_reference_after_definition, "struct S { int a; }; struct S x;\nint main(void) { return 0; }", 0, "");
valid!(tag_reference_before_definition, "struct S *p; struct S { int a; };\nint main(void) { return 0; }", 0, "");
valid!(tag_incomplete_pointer, "struct T; struct T *p;\nint main(void) { return 0; }", 0, "");
valid!(tag_self_reference, "struct N { int v; struct N *next; };\nint main(void) { return 0; }", 0, "");
valid!(tag_mutually_recursive, "struct A { struct B *b; }; struct B { struct A *a; };\nint main(void) { return 0; }", 0, "");
valid!(tag_reference_in_inner_scope, "struct S { int a; }; void f(void) { struct S s; }\nint main(void) { return 0; }", 0, "");
valid!(tag_shadowed_in_inner_scope, "struct S { int a; }; void f(void) { struct S { char b; } s; s.b = 0; }\nint main(void) { return 0; }", 0, "");
valid!(prototype_enumerator_visible_in_body, "int f(enum E { A, B } x) { return x + B; }\nint main(void) { return 0; }", 0, "");
valid!(prototype_tag_hides_file_tag, "struct W { int a; }; void m(struct W { char c; } *p);\nint main(void) { return 0; }", 0, "");
valid!(definition_parameter_tag_visible_in_body, "void h(struct U { int a; } x) { struct U y; y.a = x.a; }\nint main(void) { return 0; }", 0, "");
valid!(bit_field_width_below_the_type_width, "struct S { int a : 3; };\nint main(void) { return 0; }", 0, "");
valid!(bit_field_width_at_the_type_width, "struct S { int a : 32; };\nint main(void) { return 0; }", 0, "");
valid!(unsigned_bit_field_width_at_the_type_width, "struct S { unsigned a : 32; };\nint main(void) { return 0; }", 0, "");
valid!(bit_field_width_from_a_constant_expression, "struct S { int a : 2 + 1; };\nint main(void) { return 0; }", 0, "");
valid!(anonymous_bit_field_of_zero_width, "struct S { int a : 1; int : 0; };\nint main(void) { return 0; }", 0, "");
valid!(enum_reference_after_definition, "enum E { A }; enum E x;\nint main(void) { return 0; }", 0, "");
valid!(enum_pointer_after_definition, "enum E { A }; enum E *p;\nint main(void) { return 0; }", 0, "");
valid!(typedef_repeated_use, "typedef int T; T u; T v;\nint main(void) { return 0; }", 0, "");
valid!(typedef_redeclaration_compatible, "typedef int T; T w; T w;\nint main(void) { return 0; }", 0, "");
valid!(typedef_and_spelled_out_type_agree, "typedef int T; T w; int w;\nint main(void) { return 0; }", 0, "");
valid!(typedef_qualifier_applies_to_outer_level, "typedef int *P; const P p; int *const p;\nint main(void) { return 0; }", 0, "");
valid!(typedef_of_tag, "struct S { int a; }; typedef struct S S; S v; struct S w;\nint main(void) { return 0; }", 0, "");
valid!(qualifier_matching_redeclaration, "const int x; const int x;\nint main(void) { return 0; }", 0, "");
valid!(enumerator_implicit_increment, "enum e { A, B, C }; int f(void) { return C; }\nint main(void) { return 0; }", 0, "");
valid!(enumerator_references_previous, "enum e { A = 1, B = A + 1, C = B * 2 + A };\nint main(void) { return 0; }", 0, "");
valid!(enumerator_negative_start, "enum e { A = -1, B, C };\nint main(void) { return 0; }", 0, "");
valid!(enumerator_char_constant, "enum e { A = 'a', B };\nint main(void) { return 0; }", 0, "");
valid!(enumerator_parenthesized, "enum e { A = (1 + 2) * 3 };\nint main(void) { return 0; }", 0, "");
valid!(enumerator_int_max, "enum e { M = 2147483647 };\nint main(void) { return 0; }", 0, "");
valid!(enumerator_sizeof_type, "enum e { A = sizeof(int), B };\nint main(void) { return 0; }", 0, "");
valid!(enum_tag_complete_after_definition, "enum e { A = 1 }; enum e v;\nint main(void) { return 0; }", 0, "");
valid!(enumerator_used_in_function, "enum e { A = 1 }; int f(void) { int x; x = A; return x; }\nint main(void) { return 0; }", 0, "");
valid!(enumerator_shadowed_in_inner_scope, "enum e { A = 1 }; int f(void) { int A; A = 2; return A; }\nint main(void) { return 0; }", 0, "");
valid!(identifier_implicit_function_declaration, "int f(void) { return g(); }\nint main(void) { return 0; }\nint g(void) { return 0; }", 0, "");
valid!(cast_float_constant_to_int, "enum e { A = (int)1.5 };\nint main(void) { return 0; }", 0, "");
valid!(cast_parenthesized_float_constant, "enum e { A = (int)(1.5) };\nint main(void) { return 0; }", 0, "");
valid!(cast_integral_expression, "enum e { A = (int)(1 + 2) };\nint main(void) { return 0; }", 0, "");
valid!(cast_narrowing_to_char, "enum e { A = (char)300 };\nint main(void) { return 0; }", 0, "");
valid!(cast_narrowing_to_unsigned_char, "enum e { A = (unsigned char)-1 };\nint main(void) { return 0; }", 0, "");
valid!(cast_narrowing_to_short, "enum e { A = (short)70000 };\nint main(void) { return 0; }", 0, "");
valid!(cast_nested_integral, "enum e { A = (int)(char)300 };\nint main(void) { return 0; }", 0, "");
valid!(cast_mixed_integer_ranks, "enum e { A = (long)1 + (short)2 };\nint main(void) { return 0; }", 0, "");
valid!(cast_to_enum_tag, "enum f { X = 1 }; enum e { A = (enum f)2 };\nint main(void) { return 0; }", 0, "");
valid!(constant_reaching_unsigned_int, "enum e { A = (0x80000000 % 1000) };\nint main(void) { return 0; }", 0, "");
valid!(constant_sizeof_is_size_t, "enum e { A = sizeof(int) };\nint main(void) { return 0; }", 0, "");
valid!(declaration_of_a_struct_tag, "struct S;\nint main(void) { return 0; }", 0, "");
valid!(definition_of_a_struct_tag, "struct S { int a; };\nint main(void) { return 0; }", 0, "");
valid!(definition_of_a_union_tag, "union U { int a; };\nint main(void) { return 0; }", 0, "");
valid!(definition_of_an_enumeration, "enum E { A };\nint main(void) { return 0; }", 0, "");
valid!(definition_of_an_unnamed_enumeration, "enum { A };\nint main(void) { return 0; }", 0, "");
valid!(external_declaration_with_static, "static int x;\nint main(void) { return 0; }", 0, "");
valid!(external_declaration_with_extern, "extern int x;\nint main(void) { return 0; }", 0, "");
valid!(external_declaration_with_typedef, "typedef int T;\nint main(void) { return 0; }", 0, "");
valid!(block_declaration_with_register, "void f(void) { register int x; }\nint main(void) { return 0; }", 0, "");
valid!(block_declaration_with_auto, "void f(void) { auto int x; }\nint main(void) { return 0; }", 0, "");
valid!(block_function_declaration_with_extern, "void f(void) { extern int g(void); }\nint main(void) { return 0; }", 0, "");
valid!(block_function_declaration_without_storage, "void f(void) { int g(void); }\nint main(void) { return 0; }", 0, "");
valid!(block_declaration_of_a_pointer_to_function, "void f(void) { auto int (*fp)(void); }\nint main(void) { return 0; }", 0, "");
valid!(block_typedef_of_a_function_type, "void f(void) { typedef int T(void); }\nint main(void) { return 0; }", 0, "");
valid!(external_function_declaration_with_static, "static int g(void);\nint main(void) { return 0; }", 0, "");
valid!(external_function_declaration_returning_pointer, "static int *g(void);\nint main(void) { return 0; }", 0, "");
valid!(function_returning_a_pointer_to_function, "int (*f(void))(void);\nint main(void) { return 0; }", 0, "");
valid!(function_returning_a_pointer_to_array, "int (*f(void))[3];\nint main(void) { return 0; }", 0, "");
valid!(function_declared_with_an_incomplete_return_type, "struct S; struct S f(void);\nint main(void) { return 0; }", 0, "");
valid!(function_both_parameter_lists_absent, "int f(); int f();\nint main(void) { return 0; }", 0, "");
valid!(function_prototype_then_unspecified, "int f(int); int f();\nint main(void) { return 0; }", 0, "");
valid!(function_unspecified_then_prototype, "int f(); int f(int);\nint main(void) { return 0; }", 0, "");
valid!(function_void_prototype_then_unspecified, "int f(void); int f();\nint main(void) { return 0; }", 0, "");
valid!(function_pointer_parameter_is_not_promoted, "int f(int *); int f();\nint main(void) { return 0; }", 0, "");
valid!(function_parameter_qualifier_is_dropped, "int f(const int); int f();\nint main(void) { return 0; }", 0, "");
valid!(function_prototype_then_identifier_list_definition, "int f(int); int f(a) int a; { }\nint main(void) { return 0; }", 0, "");
valid!(function_unspecified_then_identifier_list_definition, "int f(); int f(a) int a; { }\nint main(void) { return 0; }", 0, "");
valid!(function_identifier_without_declaration_is_int, "int f(int); int f(a) { }\nint main(void) { return 0; }", 0, "");
valid!(function_identifier_short_promotes_to_int, "int f(int); int f(a) short a; { }\nint main(void) { return 0; }", 0, "");
valid!(function_identifier_float_promotes_to_double, "int f(double); int f(a) float a; { }\nint main(void) { return 0; }", 0, "");
valid!(function_variadic_prototype_then_identifier_list_definition, "int f(int,...); int f(a) int a; { }\nint main(void) { return 0; }", 0, "");
valid!(function_identifier_list_definition_then_prototype, "int f(a) int a; { } int f(int);\nint main(void) { return 0; }", 0, "");
valid!(enum_parameter_prototype_then_unspecified, "enum e { A }; int f(enum e); int f();\nint main(void) { return 0; }", 0, "");
valid!(enum_parameter_prototype_then_identifier_list_definition, "enum e { A }; int f(enum e); int f(a) enum e a; { }\nint main(void) { return 0; }", 0, "");
valid!(compatible_pointer_to_function, "extern int (*p)(int); extern int (*p)(int);\nint main(void) { return 0; }", 0, "");
valid!(compatible_pointer_to_completed_tag, "struct S; extern struct S *p; struct S { int a; }; extern struct S *p;\nint main(void) { return 0; }", 0, "");
valid!(compatible_array_unsized_then_sized, "extern int a[]; extern int a[10];\nint main(void) { return 0; }", 0, "");
valid!(compatible_array_sized_then_unsized, "extern int a[10]; extern int a[];\nint main(void) { return 0; }", 0, "");
valid!(compatible_array_both_unsized, "extern const int a[]; extern const int a[10];\nint main(void) { return 0; }", 0, "");
valid!(compatible_array_of_array_outer_unsized, "extern int a[][4]; extern int a[3][4];\nint main(void) { return 0; }", 0, "");
valid!(compatible_array_of_array_outer_sized_first, "extern int a[10][4]; extern int a[][4];\nint main(void) { return 0; }", 0, "");
valid!(compatible_pointer_to_unsized_array, "extern int (*p)[10]; extern int (*p)[];\nint main(void) { return 0; }", 0, "");
valid!(compatible_enum_declared_twice, "enum a { X }; extern enum a v; extern enum a v;\nint main(void) { return 0; }", 0, "");
valid!(compatible_int_against_signed_int, "extern int x; extern signed int x;\nint main(void) { return 0; }", 0, "");
valid!(void_pointer_parameter_old_style, "void h(p) void *p; { }\nint main(void) { return 0; }", 0, "");
valid!(extern_incomplete_variable, "struct S; extern struct S b;\nint main(void) { return 0; }", 0, "");
valid!(extern_incomplete_block_variable, "struct S; void f(void) { extern struct S y; }\nint main(void) { return 0; }", 0, "");
valid!(pointer_to_incomplete_variable, "struct S; struct S *p;\nint main(void) { return 0; }", 0, "");
valid!(typedef_of_incomplete_type, "struct S; typedef struct S TS;\nint main(void) { return 0; }", 0, "");
valid!(incomplete_parameter_in_prototype_only, "struct S; void g(struct S p);\nint main(void) { return 0; }", 0, "");
valid!(incomplete_return_in_prototype_only, "struct S; struct S ret(void);\nint main(void) { return 0; }", 0, "");
valid!(self_referential_struct_pointer_member, "struct X { struct X *p; };\nint main(void) { return 0; }", 0, "");
valid!(tentative_definition_completed_later, "struct S; struct S late; struct S { int a; };\nint main(void) { return 0; }", 0, "");
valid!(unsized_array_completed_by_initializer, "int a[] = { 1, 2 };\nint main(void) { return 0; }", 0, "");
invalid!(enum_recovers_after_undeclared_enumerator, "enum e { A = Z, B = 2, C = B + 1 }; enum e v; int f(void) { return B + C; }", &["error: Use of undeclared identifier 'Z'", "error: Non constant expression"]);
invalid!(enum_recovers_after_non_integer_enumerator, "enum g { P = 1.5, Q = 2, R = 3 }; int f(void) { return Q + R; }", &["error: Non integer constant expression"]);
invalid!(enum_recovers_after_out_of_range_enumerator, "enum h { M = 2147483647, N, O = 5 }; int g(void) { return O; }", &["error: Enumerator value should be in int range"]);
invalid!(two_dimensional_array_reports_element_incompleteness_once, "struct S; struct S a[2][3];", &["error: array has incomplete or function element type 'struct S'"]);
invalid!(incomplete_member_reports_once_without_tag_without_member, "struct S; struct T { struct S s; };", &["error: field has incomplete or function type 'struct S'"]);
invalid!(tag_redefinition, "struct S { int a; }; struct S { int b; };", &["error: duplicate declaration of struct `S'"]);
invalid!(tag_kind_mismatch, "struct S { int a; }; union S { int c; };", &["error: duplicate declaration of struct `S'"]);
invalid!(prototype_tag_not_visible_after_declaration, "void f(struct S { int a; } *p); struct S s;", &["error: tentative definition has type 'struct S' that is never completed"]);
invalid!(prototype_tag_differs_from_later_file_tag, "void g(struct T *p); struct T { int x; }; void g(struct T *p);", &["error: duplicate declaration of function `g'"]);
invalid!(nested_prototype_tag_not_visible_after_declaration, "void k(void (*fp)(struct V { int a; } *)); struct V v;", &["error: tentative definition has type 'struct V' that is never completed"]);
invalid!(prototype_enumerator_not_visible_after_declaration, "void f(enum E { A } x); int y = A;", &["error: Use of undeclared identifier 'A'"]);
invalid!(nested_prototype_enumerator_not_visible_in_body, "int f(void (*g)(enum E { A } y)) { return A; }", &["error: Use of undeclared identifier 'A'"]);
invalid!(prototype_enumerator_conflicts_with_param, "int f(enum E { A } A) { return 0; }", &["error: duplicate declaration of parameter `A'"]);
invalid!(definition_parameter_tag_not_visible_after_body, "void h(struct U { int a; } x) { } struct U z;", &["error: tentative definition has type 'struct U' that is never completed"]);
invalid!(tag_duplicate_member, "struct S { int a; int a; };", &["error: duplicate declaration of member `a'"]);
invalid!(bit_field_width_exceeding_the_type_width, "struct S { int a : 33; };", &["error: width of bit-field 'a' (33 bits) exceeds the width of its type (32 bits)"]);
invalid!(unsigned_bit_field_width_exceeding_the_type_width, "struct S { unsigned a : 33; };", &["error: width of bit-field 'a' (33 bits) exceeds the width of its type (32 bits)"]);
invalid!(anonymous_bit_field_width_exceeding_the_type_width, "struct S { int a; int : 33; };", &["error: width of anonymous bit-field (33 bits) exceeds the width of its type (32 bits)"]);
invalid!(negative_bit_field_width, "struct S { int a : -1; };", &["error: bit-field 'a' has negative width (-1)"]);
invalid!(negative_anonymous_bit_field_width, "struct S { int a; int : -1; };", &["error: anonymous bit-field has negative width (-1)"]);
invalid!(zero_width_named_bit_field, "struct S { int a : 0; };", &["error: named bit-field 'a' has zero width"]);
invalid!(bit_field_width_in_a_union_exceeding_the_type_width, "union U { int a : 33; };", &["error: width of bit-field 'a' (33 bits) exceeds the width of its type (32 bits)"]);
invalid!(enum_forward_declaration, "enum E;", &["error: ISO C forbids forward references to enum 'E'"]);
invalid!(enum_forward_reference_in_a_declaration, "enum E x;", &["error: ISO C forbids forward references to enum 'E'", "error: tentative definition has type 'enum E' that is never completed"]);
invalid!(enum_forward_reference_through_a_pointer, "enum E *p;", &["error: ISO C forbids forward references to enum 'E'"]);
invalid!(enum_forward_reference_in_a_prototype, "void f(enum E x);", &["error: ISO C forbids forward references to enum 'E'"]);
invalid!(typedef_duplicate_qualifier, "typedef const int CI; const CI q;", &["error: Duplicate type qualifiers"]);
invalid!(qualifier_conflicting_redeclaration, "const int x; int x;", &["error: duplicate declaration of variable `x'"]);
invalid!(qualifier_volatile_conflicting_redeclaration, "volatile int x; int x;", &["error: duplicate declaration of variable `x'"]);
invalid!(qualifier_duplicate_const, "const const int x;", &["error: Duplicate type qualifiers"]);
invalid!(enumerator_undeclared_reference, "enum e { A = Z };", &["error: Use of undeclared identifier 'Z'", "error: Non constant expression"]);
invalid!(enumerator_references_object, "int x; enum e { A = x };", &["error: Non constant expression"]);
invalid!(enumerator_non_integer_constant, "enum e { A = 1.5 };", &["error: Non integer constant expression"]);
invalid!(enumerator_exceeds_int_range, "enum e { M = 2147483647, N };", &["error: Enumerator value should be in int range"]);
invalid!(identifier_undeclared_in_expression, "int f(void) { return undeclared_thing; }", &["error: Use of undeclared identifier 'undeclared_thing'"]);
invalid!(identifier_used_before_declaration, "int f(void) { return v; }", &["error: Use of undeclared identifier 'v'"]);
invalid!(cast_to_floating_rejected, "enum e { A = (double)1 };", &["error: Non integer constant expression"]);
invalid!(cast_through_floating_rejected, "enum e { A = (int)(double)1 };", &["error: Non integer constant expression"]);
invalid!(cast_non_immediate_float_operand_rejected, "enum e { A = (int)(1.5 + 1) };", &["error: Non integer constant expression"]);
invalid!(cast_to_pointer_rejected, "enum e { A = (int *)0 };", &["error: Non integer constant expression"]);
invalid!(cast_to_void_rejected, "enum e { A = (void)0 };", &["error: Non integer constant expression"]);
invalid!(cast_to_struct_rejected, "struct s { int a; }; enum e { A = (int)(struct s)1 };", &["error: Conversion to non scalar type"]);
invalid!(cast_of_object_rejected, "int x; enum e { A = (int)x };", &["error: Non constant expression"]);
invalid!(cast_unsigned_wraparound_exceeds_int_range, "enum e { A = (unsigned int)-1 };", &["error: Enumerator value should be in int range"]);
invalid!(constant_division_by_zero, "enum E { A = 1 / 0 };", &["error: division by zero is undefined"]);
invalid!(constant_remainder_by_zero, "enum E { A = 1 % 0 };", &["error: remainder by zero is undefined"]);
invalid!(constant_division_overflows, "enum E { A = (-2147483647 - 1) / -1 };", &["error: overflow in constant expression"]);
invalid!(constant_remainder_overflows, "enum E { A = (-2147483647 - 1) % -1 };", &["error: overflow in constant expression"]);
invalid!(empty_declaration_of_a_basic_type, "int ;", &["error: Declaration declares nothing"]);
invalid!(empty_declaration_of_a_qualified_type, "const int;", &["error: Declaration declares nothing"]);
invalid!(empty_declaration_of_a_typedef_name, "typedef int T; T;", &["error: Declaration declares nothing"]);
invalid!(empty_declaration_of_an_unnamed_struct, "struct { int a; };", &["error: Declaration declares nothing"]);
invalid!(empty_declaration_of_an_unnamed_union, "union { int a; };", &["error: Declaration declares nothing"]);
invalid!(external_declaration_with_register, "register int x;", &["error: file-scope declaration specifies 'auto' or 'register'"]);
invalid!(external_declaration_with_auto, "auto int x;", &["error: file-scope declaration specifies 'auto' or 'register'"]);
invalid!(external_definition_with_register, "register int f(void) { return 0; }", &["error: Function storage shall be auto or extern", "error: file-scope declaration specifies 'auto' or 'register'"]);
invalid!(block_function_declaration_with_auto, "void f(void) { auto int g(void); }", &["error: Function in block not declared as extern"]);
invalid!(block_function_declaration_with_static, "void f(void) { static int g(void); }", &["error: Function in block not declared as extern"]);
invalid!(block_function_declaration_with_register, "void f(void) { register int g(); }", &["error: Function in block not declared as extern"]);
invalid!(nested_block_function_declaration_with_static, "void f(void) { { static int g(void); } }", &["error: Function in block not declared as extern"]);
invalid!(function_returning_an_array, "int f(void)[3];", &["error: function cannot return array type 'int[3]'"]);
invalid!(function_returning_an_array_through_a_typedef, "typedef int A[3]; A f(void);", &["error: function cannot return array type 'int[3]'"]);
invalid!(function_returning_a_function, "int f(void)(void);", &["error: function cannot return function type 'int(void)'"]);
invalid!(function_char_parameter_promotes_to_int, "int f(char); int f();", &["error: duplicate declaration of function `f'"]);
invalid!(function_float_parameter_promotes_to_double, "int f(float); int f();", &["error: duplicate declaration of function `f'"]);
invalid!(function_variadic_prototype_then_unspecified, "int f(int,...); int f();", &["error: duplicate declaration of function `f'"]);
invalid!(function_prototype_then_empty_identifier_list_definition, "int f(int); int f() { }", &["error: duplicate declaration of function `f'"]);
invalid!(function_identifier_list_definition_with_fewer_parameters, "int f(int,int); int f(a) int a; { }", &["error: duplicate declaration of function `f'"]);
invalid!(function_identifier_char_promotes_to_int, "int f(char); int f(a) char a; { }", &["error: duplicate declaration of function `f'"]);
invalid!(function_identifier_list_definition_with_other_return_type, "int f(int); void f(a) int a; { }", &["error: duplicate declaration of function `f'"]);
invalid!(compatible_const_against_plain, "extern const int x; extern int x;", &["error: duplicate declaration of variable `x'"]);
invalid!(compatible_volatile_against_plain, "extern volatile int x; extern int x;", &["error: duplicate declaration of variable `x'"]);
invalid!(compatible_const_pointer_against_plain, "extern int *const p; extern int *p;", &["error: duplicate declaration of variable `p'"]);
invalid!(compatible_pointer_to_const_against_pointer, "extern const int *p; extern int *p;", &["error: duplicate declaration of variable `p'"]);
invalid!(compatible_const_tag_against_plain, "struct S { int a; }; extern const struct S s; extern struct S s;", &["error: duplicate declaration of variable `s'"]);
invalid!(compatible_const_element_against_plain, "extern const int a[10]; extern int a[10];", &["error: duplicate declaration of variable `a'"]);
invalid!(compatible_pointer_to_function_other_parameter, "extern int (*p)(int); extern int (*p)(char);", &["error: duplicate declaration of variable `p'"]);
invalid!(compatible_pointer_to_function_other_return, "extern int (*p)(int); extern char (*p)(int);", &["error: duplicate declaration of variable `p'"]);
invalid!(compatible_array_other_size, "extern int a[10]; extern int a[11];", &["error: duplicate declaration of variable `a'"]);
invalid!(compatible_array_of_array_other_inner_size, "extern int a[3][4]; extern int a[3][5];", &["error: duplicate declaration of variable `a'"]);
invalid!(compatible_distinct_enums, "enum a { X }; enum b { Y }; extern enum a v; extern enum b v;", &["error: duplicate declaration of variable `v'"]);
invalid!(compatible_char_against_signed_char, "extern char c; extern signed char c;", &["error: duplicate declaration of variable `c'"]);
invalid!(compatible_int_against_unsigned_int, "extern int x; extern unsigned int x;", &["error: duplicate declaration of variable `x'"]);
invalid!(incomplete_void_variable, "void v;", &["error: variable has incomplete type 'void'", "error: tentative definition has type 'void' that is never completed"], gcc_accepts = true);
invalid!(incomplete_initialized_variable, "struct S; struct S x = { 1 };", &["error: variable has incomplete type 'struct S'", "error: excess elements in array initializer"]);
invalid!(incomplete_block_variable, "struct S; void f(void) { struct S x; }", &["error: variable has incomplete type 'struct S'"]);
invalid!(incomplete_static_block_variable, "struct S; void f(void) { static struct S x; }", &["error: variable has incomplete type 'struct S'"]);
invalid!(incomplete_array_element_sized, "struct S; struct S a[3];", &["error: array has incomplete or function element type 'struct S'"]);
invalid!(incomplete_array_element_unsized, "struct S; extern struct S a[];", &["error: array has incomplete or function element type 'struct S'"]);
invalid!(void_array_element, "void a[3];", &["error: array has incomplete or function element type 'void'"]);
invalid!(incomplete_struct_member, "struct S; struct T { struct S s; };", &["error: field has incomplete or function type 'struct S'"]);
invalid!(void_struct_member, "struct U { void v; };", &["error: field has incomplete or function type 'void'"]);
invalid!(self_referential_struct_member, "struct W { struct W w; };", &["error: nested redefinition of 'W'"]);
invalid!(self_referential_struct_member_no_crash, "struct W { struct W w; }; enum e { P = sizeof(struct W) };", &["error: nested redefinition of 'W'", "error: invalid application of 'sizeof' to an incomplete type 'struct W'"]);
invalid!(self_referential_struct_array_member_zero_size_no_crash, "struct W { struct W w[0]; }; enum e { P = sizeof(struct W) };", &["error: array has incomplete or function element type 'struct W'", "error: size of array is zero"]);
invalid!(self_referential_struct_array_member_no_crash, "struct W { struct W w[3]; }; enum e { P = sizeof(struct W) };", &["error: array has incomplete or function element type 'struct W'"]);
invalid!(incomplete_parameter_prototype, "struct S; void h(struct S p) { (void)0; }", &["error: parameter has incomplete type 'struct S'"]);
invalid!(incomplete_parameter_old_style, "struct S; void h(p) struct S p; { (void)0; }", &["error: parameter has incomplete type 'struct S'"]);
invalid!(void_parameter_old_style, "void h(p) void p; { }", &["error: Parameter shall not have void type"]);
invalid!(void_parameter_old_style_second, "void h(a, b) int b; void a; { }", &["error: Parameter shall not have void type"]);
invalid!(void_parameter_old_style_typedef, "typedef void V; void h(p) V p; { }", &["error: Parameter shall not have void type"]);
invalid!(void_parameter_old_style_qualified, "void h(p) const void p; { }", &["error: Parameter shall not have void type"]);
invalid!(void_parameter_old_style_register, "void h(p) register void p; { }", &["error: Parameter shall not have void type"]);
invalid!(initialized_parameter_old_style, "int f(a) int a = 1; { return a; }", &["error: parameter cannot have an initializer"]);
invalid!(initialized_parameter_old_style_first_of_two, "int f(a, b) int a = 1, b; { return a; }", &["error: parameter cannot have an initializer"]);
invalid!(empty_declaration_old_style, "int f(a) int; int a; { return a; }", &["error: declaration does not declare a parameter"]);
invalid!(empty_register_declaration_old_style, "int f(a) register; int a; { return a; }", &["error: declaration does not declare a parameter"]);
invalid!(tag_declaration_old_style, "int f(a) struct S; int a; { return a; }", &["error: declaration does not declare a parameter"]);
invalid!(struct_definition_old_style, "int f(a) struct S { int x; }; int a; { return a; }", &["error: declaration does not declare a parameter"]);
invalid!(enum_definition_old_style, "int f(a) enum E { A }; int a; { return a; }", &["error: declaration does not declare a parameter"]);
invalid!(incomplete_return_type, "struct S; struct S r(void) { struct S v; return v; }", &["error: function definition has incomplete return type 'struct S'", "error: variable has incomplete type 'struct S'", "error: incomplete definition of type 'struct S'"]);
invalid!(incomplete_definition_parameter_array, "struct S; void f(struct S a[]);", &["error: array has incomplete or function element type 'struct S'"]);
valid!(cast_value_float_truncates_toward_zero, "enum e { A = (int)1.5 };\nint main(void) { return !((A == 1)); }", 0, "");
valid!(cast_value_char_wraps, "enum e { A = (char)300 };\nint main(void) { return !((A == 44)); }", 0, "");
valid!(cast_value_char_is_signed, "enum e { A = (char)-1 };\nint main(void) { return !((A == -1)); }", 0, "");
valid!(cast_value_unsigned_char_wraps, "enum e { A = (unsigned char)-1 };\nint main(void) { return !((A == 255)); }", 0, "");
valid!(cast_value_short_wraps, "enum e { A = (short)70000 };\nint main(void) { return !((A == 4464)); }", 0, "");
valid!(cast_value_unsigned_int_wraps, "enum e { A = (unsigned int)-1 % 1000 };\nint main(void) { return !((A == 295)); }", 0, "");
valid!(cast_value_long_is_32_bits_on_i386, "enum e { A = (unsigned long)-1 % 1000 };\nint main(void) { return !((A == 295)); }", 0, "");
valid!(cast_value_enum_sequence, "enum e { A = (int)(1 + 2), B, C = (char)-1, D };\nint main(void) { return !((A == 3) && (B == 4) && (C == -1) && (D == 0)); }", 0, "");
valid!(pp_number_valid_constants_unchanged, "enum e { A = (int)1.e+1, B = 0x1E, C = 0x1E - 1, D = (int)(.5e+1f), E = 0x1eUL, F = (int)1E-1 };\nint main(void) { return !((A == 10) && (B == 30) && (C == 29) && (D == 5) && (E == 30) && (F == 0)); }", 0, "");
valid!(main_without_parameters, "int fixture_main(void) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(main_with_empty_parameter_list, "int fixture_main() { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(main_with_argc_argv, "int fixture_main(int argc, char **argv) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(main_with_array_argv, "int fixture_main(int argc, char *argv[]) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(main_with_envp, "int fixture_main(int argc, char **argv, char **envp) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(main_ignores_qualifiers, "const int fixture_main(int a, const char **b, char *const *c) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(main_old_style_is_not_checked, "int fixture_main(a, b) int a; int b; { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(main_static_declaration_before_definition, "static int fixture_main(void);\nint fixture_main(void) { return 0; }\nint main(void) { return 0; }", 0, "");
invalid!(main_is_static, "static int main(void) { return 0; }", &["error: ‘main’ is normally a non-static function"]);
invalid!(main_returns_long, "long main(void) { return 0; }", &["error: return type of ‘main’ is not ‘int’"]);
invalid!(main_returns_void, "void main(a) { }", &["error: return type of ‘main’ is not ‘int’"]);
invalid!(main_returns_enum, "enum e { A }; enum e main(void) { return 0; }", &["error: return type of ‘main’ is not ‘int’"]);
invalid!(main_with_one_parameter, "int main(int a) { return 0; }", &["error: ‘main’ takes only zero or two arguments"]);
invalid!(main_with_four_parameters, "int main(int a, char **b, char **c, int d) { return 0; }", &["error: ‘main’ takes only zero or two arguments"]);
invalid!(main_second_parameter_int, "int main(int a, int b) { return 0; }", &["error: second argument of ‘main’ should be ‘char **’"]);
invalid!(main_second_parameter_unsigned_char, "int main(int a, unsigned char **b) { return 0; }", &["error: second argument of ‘main’ should be ‘char **’"]);
invalid!(main_second_parameter_array_of_arrays, "int main(int a, char b[][2]) { return 0; }", &["error: second argument of ‘main’ should be ‘char **’"]);
invalid!(main_third_parameter_int, "int main(int a, char **b, int c) { return 0; }", &["error: third argument of ‘main’ should probably be ‘char **’"]);
invalid!(main_third_parameter_triple_pointer, "int main(int a, char **b, char ***c) { return 0; }", &["error: third argument of ‘main’ should probably be ‘char **’"]);
valid!(main_first_parameter_const_int, "int fixture_main(const int a, char **b) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(main_first_parameter_signed, "int fixture_main(signed a, char **b) { return 0; }\nint main(void) { return 0; }", 0, "");
invalid!(main_first_parameter_long, "int main(long a, char **b) { return 0; }", &["error: first argument of ‘main’ should be ‘int’"]);
invalid!(main_first_parameter_unsigned, "int main(unsigned a, char *b[]) { return 0; }", &["error: first argument of ‘main’ should be ‘int’"]);
invalid!(main_first_parameter_enum, "enum e { A }; int main(enum e a, char **b) { return 0; }", &["error: first argument of ‘main’ should be ‘int’"]);
invalid!(main_is_variadic, "int main(int a, char **b, ...) { return 0; }", &["error: ‘main’ declared as variadic function"]);
invalid!(main_variadic_with_one_parameter, "int main(int a, ...) { return 0; }", &["error: ‘main’ takes only zero or two arguments", "error: ‘main’ declared as variadic function"]);
invalid!(main_reports_every_violation, "static long main(long a, int b, int c, ...) { return 0; }", &["error: return type of ‘main’ is not ‘int’", "error: first argument of ‘main’ should be ‘int’", "error: second argument of ‘main’ should be ‘char **’", "error: third argument of ‘main’ should probably be ‘char **’", "error: ‘main’ declared as variadic function", "error: ‘main’ is normally a non-static function"]);
invalid!(void_cast_argument_to_unprototyped_function, "int f(); int main(void) { f((void)0); return 0; } int f() { return 0; }", &["error: invalid use of void expression"]);
invalid!(void_call_argument_in_variadic_part, "int printf(const char *, ...); void g(void) {} int main(void) { printf(\"%d\\n\", g()); return 0; }", &["error: invalid use of void expression"]);
invalid!(void_dereference_argument_in_variadic_part, "int printf(const char *, ...); int main(void) { int x = 1; void *p = &x; printf(\"%d\\n\", *p); return 0; }", &["warning: dereferencing 'void *' pointer", "error: invalid use of void expression"]);
