#![cfg_attr(rustfmt, rustfmt_skip)]

valid!(post_inc, "int main(void) { int a = 4; int b = a++; return a * 10 + b; }", 54, "");
valid!(post_dec, "int main(void) { int a = 4; int b = a--; return a * 10 + b; }", 34, "");
valid!(pre_inc, "int main(void) { int a = 4; int b = ++a; return a * 10 + b; }", 55, "");
valid!(pre_dec, "int main(void) { int a = 4; int b = --a; return a * 10 + b; }", 33, "");
valid!(addr, "int main(void) { int a = 7; int *p = &a; return *p; }", 7, "");
valid!(deref, "int main(void) { int a = 7; int *p = &a; *p = 9; return a; }", 9, "");
valid!(unary_plus, "int main(void) { int a = 4; return +a; }", 4, "");
valid!(unary_minus, "int main(void) { int a = -4; return -a; }", 4, "");
valid!(bit_not, "int main(void) { unsigned a = 0xfffffff0u; return ~a; }", 15, "");
valid!(logical_not, "int main(void) { int a = 0; return !a; }", 1, "");
valid!(add, "int main(void) { int a = 4; int b = 3; return a + b; }", 7, "");
valid!(sub, "int main(void) { int a = 4; int b = 3; return a - b; }", 1, "");
valid!(mul, "int main(void) { int a = 4; int b = 3; return a * b; }", 12, "");
valid!(div, "int main(void) { int a = 7; int b = 3; return a / b; }", 2, "");
valid!(mod_, "int main(void) { int a = 7; int b = 3; return a % b; }", 1, "");
valid!(left, "int main(void) { int a = 3; int b = 2; return a << b; }", 12, "");
valid!(right, "int main(void) { int a = 12; int b = 2; return a >> b; }", 3, "");
valid!(greater, "int main(void) { int a = 4; int b = 3; return a > b; }", 1, "");
valid!(lower, "int main(void) { int a = 3; int b = 4; return a < b; }", 1, "");
valid!(greater_eq, "int main(void) { int a = 3; int b = 3; return a >= b; }", 1, "");
valid!(lower_eq, "int main(void) { int a = 3; int b = 3; return a <= b; }", 1, "");
valid!(eq, "int main(void) { int a = 3; int b = 3; return a == b; }", 1, "");
valid!(neq, "int main(void) { int a = 3; int b = 4; return a != b; }", 1, "");
valid!(bit_and, "int main(void) { int a = 6; int b = 3; return a & b; }", 2, "");
valid!(bit_or, "int main(void) { int a = 6; int b = 3; return a | b; }", 7, "");
valid!(bit_xor, "int main(void) { int a = 6; int b = 3; return a ^ b; }", 5, "");
valid!(logical_and, "int main(void) { int a = 3; int b = 4; return a && b; }", 1, "");
valid!(logical_or, "int main(void) { int a = 0; int b = 4; return a || b; }", 1, "");
valid!(assign, "int main(void) { int a = 0; int b = 7; a = b; return a; }", 7, "");
valid!(mul_assign, "int main(void) { int a = 4; a *= 3; return a; }", 12, "");
valid!(div_assign, "int main(void) { int a = 7; a /= 3; return a; }", 2, "");
valid!(mod_assign, "int main(void) { int a = 7; a %= 3; return a; }", 1, "");
valid!(add_assign, "int main(void) { int a = 7; a += 3; return a; }", 10, "");
valid!(sub_assign, "int main(void) { int a = 7; a -= 3; return a; }", 4, "");
valid!(left_assign, "int main(void) { int a = 3; a <<= 2; return a; }", 12, "");
valid!(right_assign, "int main(void) { int a = 12; a >>= 2; return a; }", 3, "");
valid!(bit_and_assign, "void f(int a, int b) { a &= b; }\nint main(void) { return 0; }", 0, "");
valid!(bit_xor_assign, "void f(int a, int b) { a ^= b; }\nint main(void) { return 0; }", 0, "");
valid!(bit_or_assign, "void f(int a, int b) { a |= b; }\nint main(void) { return 0; }", 0, "");
valid!(dot, "int main(void) { struct S { int x; } value = { 7 }; return value.x; }", 7, "");
valid!(arrow, "int main(void) { struct S { int x; } value = { 7 }; struct S *p = &value; return p->x; }", 7, "");
valid!(array_access, "int main(void) { int a[2] = { 7, 9 }; return a[1]; }", 9, "");
valid!(ternary, "int f(int a, int b, int c) { return a ? b : c; } int main(void) { return f(1, 3, 7) + f(0, 3, 7); }", 10, "");
valid!(function_call, "int g(int x) { return x + 3; } int main(void) { return g(4); }", 7, "");
valid!(sizeof_expr, "int main(void) { int a = 1; return sizeof(a); }", 4, "");
valid!(sizeof_type, "int main(void) { return sizeof(int); }", 4, "");
valid!(cast, "int main(void) { double a = 7.9; return (int)a; }", 7, "");
valid!(comma_list, "int main(void) { int a = 0; int b = (a = 3, a + 4); return a + b; }", 10, "");
valid!(constant_expression, "int main(void) { enum E { A = 1 }; return A; }", 1, "");
valid!(signed_shift_left_no_nsw, "int f(int x) { return x << 3; }\nint main(void) { return 0; }", 0, "");
valid!(signed_shift_left_assign_no_nsw, "void f(int x) { x <<= 3; }\nint main(void) { return 0; }", 0, "");
valid!(signed_shift_left_plain, "int f(int x) { return x << 3; }\nint main(void) { return 0; }", 0, "");
