#![cfg_attr(rustfmt, rustfmt_skip)]

valid!(init_struct_list, "struct S { int a; int b; }; struct S s = { 1, 2 };\nint main(void) { return 0; }", 0, "");
valid!(init_struct_partial, "struct S { int a; int b; }; struct S s = { 1 };\nint main(void) { return 0; }", 0, "");
valid!(init_struct_brace_elision, "struct S { int a; int b[2]; int c; }; struct S s = { 1, 2, 3, 4 };\nint main(void) { return 0; }", 0, "");
valid!(init_struct_fully_braced, "struct S { int a; int b[2]; int c; }; struct S s = { 1, { 2, 3 }, 4 };\nint main(void) { return 0; }", 0, "");
valid!(init_struct_nested, "struct I { int x; }; struct S { struct I i; }; struct S s = { { 1 } };\nint main(void) { return 0; }", 0, "");
valid!(init_union_first_member, "union U { int a; double b; }; union U u = { 1 };\nint main(void) { return 0; }", 0, "");
valid!(init_array_of_struct, "struct S { int a; int b; }; struct S s[2] = { { 1, 2 }, { 3, 4 } };\nint main(void) { return 0; }", 0, "");
valid!(init_unnamed_bitfield_skipped, "struct S { int a : 3; int : 2; int b : 3; }; struct S s = { 1, 2 };\nint main(void) { return 0; }", 0, "");
valid!(init_char_array_from_string, "char s[4] = \"abc\";\nint main(void) { return 0; }", 0, "");
valid!(init_char_array_exact_drops_nul, "char s[3] = \"abc\";\nint main(void) { return 0; }", 0, "");
valid!(init_char_array_braced_string, "char s[4] = { \"abc\" };\nint main(void) { return 0; }", 0, "");
valid!(init_char_pointer_from_string, "char *p = \"abc\";\nint main(void) { return 0; }", 0, "");
valid!(init_automatic_scalar_from_variable, "int g; void f(void) { int x = g; }\nint main(void) { return 0; }", 0, "");
valid!(init_static_scalar_constant, "void f(void) { static int x = 1 + 2; }\nint main(void) { return 0; }", 0, "");
valid!(init_address_constant, "int g; int *p = &g;\nint main(void) { return 0; }", 0, "");
valid!(init_array_decay_constant, "int a[3]; int *p = a;\nint main(void) { return 0; }", 0, "");
valid!(init_function_address_constant, "int f(void); int (*p)(void) = f;\nint main(void) { return 0; }\nint f(void) { return 0; }", 0, "");
valid!(init_unsigned_wraps, "unsigned x = 4294967295u + 1;\nint main(void) { return 0; }", 0, "");
valid!(init_integer_narrowing_is_not_overflow, "char c = 300; int x = (int)2147483648u;\nint main(void) { return 0; }", 0, "");
valid!(init_double_truncates_into_range, "int x = 2147483647.9; int y = -2147483648.9; unsigned u = 4294967295.0; unsigned z = 0.5;\nint main(void) { return 0; }", 0, "");
valid!(init_floating_targets_do_not_overflow, "float f = 1e39; double d = 1e10;\nint main(void) { return 0; }", 0, "");
valid!(init_static_cast_of_a_floating_expression, "int i = (int)(2.5 * 2); double d = (float)(1.0 / 3); int j = (int)-2.5; int k = (int)(1.0 < 2.0) + (char)3.5 * 2.0;\nint main(void) { return 0; }", 0, "");
valid!(init_automatic_scalar_overflow_is_not_a_constant_expression, "int f(void) { int x = 2147483647 + 1; int y = 1e10; return x + y; }\nint main(void) { return 0; }", 0, "");
valid!(init_static_cast_of_a_floating_expression_values, "int i = (int)(2.5 * 2); int j = (int)-2.5; double d = (float)(1.0 / 4); int main(void) { return i * 10 - j + (int)(d * 4); }", 53, "");
valid!(init_folds_address_of_object, "int g; int *p = &g;\nint main(void) { return !(((char *)p - (char *)&g == 0)); }", 0, "");
valid!(init_folds_array_decay, "int a[3]; int *p = a;\nint main(void) { return !(((char *)p - (char *)&a == 0)); }", 0, "");
valid!(init_folds_function_designator, "int f(void); int (*p)(void) = f;\nint f(void) { return 0; } int main(void) { return !(p == f); }", 0, "");
valid!(init_folds_address_of_element, "int a[10]; int *p = &a[3];\nint main(void) { return !(((char *)p - (char *)&a == +12)); }", 0, "");
valid!(init_folds_address_of_member, "struct S { int x; int y; } s; int *p = &s.y;\nint main(void) { return !(((char *)p - (char *)&s == +4)); }", 0, "");
valid!(init_folds_address_of_element_of_member, "struct S { int x; int a[4]; } s; int *p = &s.a[2];\nint main(void) { return !(((char *)p - (char *)&s == +12)); }", 0, "");
valid!(init_folds_member_array_decay, "struct S { int x; int a[4]; } s; int *p = s.a;\nint main(void) { return !(((char *)p - (char *)&s == +4)); }", 0, "");
valid!(init_folds_address_of_row_element, "int a[3][4]; int *p = &a[1][2];\nint main(void) { return !(((char *)p - (char *)&a == +24)); }", 0, "");
valid!(init_folds_pointer_addition, "int a[10]; int *p = a + 3;\nint main(void) { return !(((char *)p - (char *)&a == +12)); }", 0, "");
valid!(init_folds_pointer_subtraction, "int a[10]; int *p = &a[5] - 2;\nint main(void) { return !(((char *)p - (char *)&a == +12)); }", 0, "");
valid!(init_folds_byte_offset_through_a_cast, "int x; char *p = (char *)&x + 1;\nint main(void) { return !(((char *)p - (char *)&x == +1)); }", 0, "");
valid!(init_folds_offset_into_a_string_literal, "char *p = \"abc\" + 1;\nint main(void) { return !((p == (\"abc\" + 1))); }", 0, "");
valid!(init_folds_indirection_of_address, "int x; int *p = &*&x;\nint main(void) { return !(((char *)p - (char *)&x == 0)); }", 0, "");
valid!(init_folds_address_constant_into_an_integer, "int a[10]; long n = (long)&a[3];\nint main(void) { return !(((char *)n - (char *)&a == +12)); }", 0, "");
valid!(init_long_double_constant, "long double x = 3.3L;\nint main(void) { return !((x == (3.3l))); }", 0, "");
invalid!(init_static_int_overflows, "int x = 2147483647 + 1;", &["error: integer overflow in constant expression"]);
invalid!(init_static_int_underflows, "int x = -2147483647 - 2;", &["error: integer overflow in constant expression"]);
invalid!(init_static_long_overflows, "long x = 2147483647L + 1L;", &["error: integer overflow in constant expression"]);
invalid!(init_static_overflow_is_kept_after_folding_back_in_range, "int x = 2147483647 * 2 / 2;", &["error: integer overflow in constant expression"]);
invalid!(init_block_static_overflows, "int f(void) { static int x = 2147483647 + 1; return x; }", &["error: integer overflow in constant expression"]);
invalid!(init_automatic_aggregate_element_overflows, "int f(void) { int a[2] = { 2147483647 + 1 }; return a[0]; }", &["error: integer overflow in constant expression"]);
invalid!(init_static_int_from_out_of_range_double, "int x = 1e10;", &["error: overflow in constant expression"]);
invalid!(init_static_int_from_out_of_range_negative_double, "int x = -1e10;", &["error: overflow in constant expression"]);
invalid!(init_static_unsigned_from_negative_double, "unsigned x = -1.5;", &["error: overflow in constant expression"]);
invalid!(init_static_unsigned_from_too_large_double, "unsigned x = 4294967296.0;", &["error: overflow in constant expression"]);
invalid!(init_static_char_from_out_of_range_double, "char c = 1e3;", &["error: overflow in constant expression"]);
invalid!(init_automatic_struct_member_from_out_of_range_double, "int f(void) { struct { int a; } s = { 1e10 }; return s.a; }", &["error: overflow in constant expression"]);
invalid!(init_struct_too_many, "struct S { int a; }; struct S s = { 1, 2 };", &["error: excess elements in array initializer"]);
invalid!(init_union_too_many, "union U { int a; double b; }; union U u = { 1, 2 };", &["error: excess elements in array initializer"]);
invalid!(init_nested_inner_too_many, "struct S { int a; int b[2]; }; struct S s = { 1, { 2, 3, 4 } };", &["error: excess elements in array initializer"]);
invalid!(init_char_array_string_too_long, "char s[2] = \"abc\";", &["error: excess elements in array initializer"]);
invalid!(init_int_array_from_string, "int a[4] = \"abc\";", &["error: initialization of 'int[4]' from incompatible pointer type 'char *'"]);
invalid!(init_file_scope_from_variable, "int g; int x = g;", &["error: initializer element is not a compile-time constant"]);
invalid!(init_block_static_from_variable, "int g; void f(void) { static int x = g; }", &["error: initializer element is not a compile-time constant"]);
invalid!(init_automatic_aggregate_from_variable, "struct S { int a; int b; }; void f(int n) { struct S s = { n, 1 }; }", &["error: initializer element is not a compile-time constant"]);
invalid!(init_automatic_array_from_variable, "void f(int n) { int a[2] = { n, 1 }; }", &["error: initializer element is not a compile-time constant"]);
invalid!(init_address_read_through_a_pointer_variable, "struct S { int x; } s; struct S *q = &s; int *p = &q->x;", &["error: initializer element is not a compile-time constant"]);
invalid!(init_address_of_an_automatic_object, "void f(void) { int x; static int *p = &x; }", &["error: initializer element is not a compile-time constant"]);
invalid!(init_static_struct_from_a_variable, "struct S { int a; } x; struct S y = x;", &["error: initializer element is not a compile-time constant"]);
valid!(init_char_array_sized_from_string, "char a[] = \"abc\";\nint main(void) { return !(sizeof(a) == 4); }", 0, "");
valid!(init_array_sized_from_list, "int a[] = { 1, 2, 3 };\nint main(void) { return !(sizeof(a) == 12); }", 0, "");
valid!(init_array_of_struct_sized_from_list, "struct S { int a; int b; }; struct S a[] = { { 1, 2 }, { 3, 4 } };\nint main(void) { return !(sizeof(a) == 16); }", 0, "");
invalid!(init_address_int_to_float, "int g; float f = (float)(int)&g;", &["error: initializer element is not a compile-time constant"]);
invalid!(init_address_int_to_double, "int g; double d = (int)&g;", &["error: initializer element is not a compile-time constant"]);
invalid!(init_address_long_to_float, "int g; float f = (long)&g;", &["error: initializer element is not a compile-time constant"]);
invalid!(init_address_int_to_long_double, "int g; long double ld = (int)&g;", &["error: initializer element is not a compile-time constant"]);
valid!(init_address_int_pointer_sized_kept, "int g; int i = (int)&g; long l = (long)&g; unsigned u = (unsigned)&g; char *p = (char *)(int)&g;\nint main(void) { return 0; }", 0, "");
valid!(init_automatic_address_int_to_double, "int main(void) { int g; double d = (int)&g; return d == 0; }", 0, "");
