#![cfg_attr(rustfmt, rustfmt_skip)]

valid!(the_address_of_a_dereferenced_pointer_to_an_incomplete_type_is_accepted, "struct S; struct S *p; struct S *f(void) { return &*p; }\nint main(void) { return 0; }", 0, "");
valid!(a_dereferenced_pointer_is_assignable, "int *p; void f(void) { *p = 1; }\nint main(void) { return 0; }", 0, "");
valid!(indirection_on_an_array_designates_its_first_element, "int a[3]; void f(void) { *a = 1; }\nint main(void) { return 0; }", 0, "");
valid!(indirection_on_a_function_designator_designates_the_function, "int g(void); void f(void) { (*g)(); }\nint main(void) { return 0; }\nint g(void) { return 0; }", 0, "");
valid!(a_subtractive_assignment_to_a_pointer_is_accepted, "int *p; void f(void) { p -= 1; }\nint main(void) { return 0; }", 0, "");
valid!(a_division_assignment_is_accepted, "int i; void f(void) { i /= 2; }\nint main(void) { return 0; }", 0, "");
valid!(a_remainder_assignment_is_accepted, "int i; void f(void) { i %= 2; }\nint main(void) { return 0; }", 0, "");
valid!(a_right_shift_assignment_is_accepted, "unsigned u; void f(void) { u >>= 1; }\nint main(void) { return 0; }", 0, "");
valid!(a_bitwise_or_assignment_is_accepted, "int i; void f(void) { i |= 1; }\nint main(void) { return 0; }", 0, "");
valid!(a_bitwise_xor_assignment_is_accepted, "int i; void f(void) { i ^= 1; }\nint main(void) { return 0; }", 0, "");
valid!(a_void_star_cast_of_zero_is_a_null_pointer_constant, "int *p; void f(void) { p == (void *)0; }\nint main(void) { return 0; }", 0, "");
valid!(an_int_star_cast_of_zero_compares_as_a_plain_pointer, "int *p; void f(void) { p == (int *)0; }\nint main(void) { return 0; }", 0, "");
valid!(a_const_void_star_cast_of_zero_is_not_a_null_pointer_constant, "int *p; void f(void) { p == (void *const)0; }\nint main(void) { return 0; }", 0, "");
valid!(a_void_star_cast_of_zero_may_be_assigned_to_a_pointer_to_function, "void (*p)(void); void f(void) { p = (void *)0; }\nint main(void) { return 0; }", 0, "");
valid!(a_void_star_cast_of_zero_may_be_compared_to_a_pointer_to_function, "void (*p)(void); void f(void) { p == (void *)0; }\nint main(void) { return 0; }", 0, "");
valid!(a_void_star_cast_of_zero_may_initialize_a_pointer_to_function, "void (*p)(void) = (void *)0;\nint main(void) { return 0; }", 0, "");
valid!(a_void_star_cast_of_zero_may_be_passed_to_a_pointer_to_function_parameter, "void g(void (*)(void)); void f(void) { g((void *)0); }\nint main(void) { return 0; }\nvoid g(void (*p0)(void)) {  }", 0, "");
valid!(a_void_star_cast_of_zero_may_be_a_conditional_operand_beside_a_pointer_to_function, "void (*p)(void); void f(int c) { c ? p : (void *)0; }\nint main(void) { return 0; }", 0, "");
valid!(an_int_cast_of_zero_is_a_null_pointer_constant, "int *p; void f(void) { p = (int)0; }\nint main(void) { return 0; }", 0, "");
valid!(a_char_cast_of_zero_is_a_null_pointer_constant, "int *p; void f(void) { p = (char)0; }\nint main(void) { return 0; }", 0, "");
valid!(a_long_cast_of_zero_is_a_null_pointer_constant, "int *p; void f(void) { p = (long)0; }\nint main(void) { return 0; }", 0, "");
valid!(sizeof_of_a_plain_member_beside_a_bit_field_is_accepted, "struct S { int x : 3; int y; } s; void f(void) { sizeof s.y; }\nint main(void) { return 0; }", 0, "");
invalid!(the_address_of_a_bit_field_is_rejected, "struct S { int x : 3; } s; void f(void) { &s.x; }", &["error: address of bit-field requested"]);
invalid!(the_address_of_a_bit_field_reached_through_a_pointer_is_rejected, "struct S { int x : 3; } *p; void f(void) { &p->x; }", &["error: address of bit-field requested"]);
invalid!(the_address_of_a_bit_field_of_a_union_is_rejected, "union U { int x : 3; } u; void f(void) { &u.x; }", &["error: address of bit-field requested"]);
invalid!(the_address_of_a_register_object_is_rejected, "void f(void) { register int i; &i; }", &["error: address of register variable requested"]);
invalid!(indirection_on_an_integer_is_rejected, "void f(void) { int i; *i; }", &["error: indirection requires pointer operand ('int' invalid)"]);
invalid!(indirection_on_a_structure_is_rejected, "struct S { int x; } s; void f(void) { *s; }", &["error: indirection requires pointer operand ('struct S' invalid)"]);
invalid!(the_value_of_an_indirection_on_a_pointer_to_void_is_rejected, "void f(void *v) { int i = *v; }", &["warning: dereferencing 'void *' pointer", "error: initialization of 'int' from incompatible pointer type 'void'"]);
invalid!(assigning_through_a_pointer_to_void_is_rejected, "void f(void *v) { *v = 0; }", &["warning: dereferencing 'void *' pointer", "error: expression is not assignable"]);
invalid!(assigning_to_a_member_of_a_const_structure_is_rejected, "struct S { int x; }; void f(void) { const struct S s; s.x = 1; }", &["error: cannot assign to variable with const-qualified type 'const int'"]);
invalid!(assigning_to_a_member_through_a_pointer_to_const_is_rejected, "struct S { int x; }; void f(void) { const struct S *p; p->x = 1; }", &["error: cannot assign to variable with const-qualified type 'const int'"]);
invalid!(a_member_of_an_incomplete_structure_is_rejected, "struct S; struct S *p; void f(void) { p->x; }", &["error: incomplete definition of type 'struct S'"]);
invalid!(post_increment_of_an_rvalue_is_rejected, "void f(void) { 1++; }", &["error: expression is not assignable"]);
invalid!(post_increment_of_a_const_object_is_rejected, "void f(void) { const int i; i++; }", &["error: cannot assign to variable with const-qualified type 'const int'"]);
invalid!(post_increment_of_an_array_is_rejected, "int a[3]; void f(void) { a++; }", &["error: cannot increment value of type 'int[3]'"]);
invalid!(post_increment_of_a_pointer_to_a_function_is_rejected, "void (*p)(void); void f(void) { p++; }", &["error: cannot increment value of type 'void (*)(void)'"]);
invalid!(post_decrement_of_a_pointer_to_a_function_is_rejected, "void (*p)(void); void f(void) { p--; }", &["error: cannot decrement value of type 'void (*)(void)'"]);
invalid!(pre_increment_of_an_rvalue_is_rejected, "void f(void) { ++1; }", &["error: expression is not assignable"]);
invalid!(pre_increment_of_a_const_object_is_rejected, "void f(void) { const int i; ++i; }", &["error: cannot assign to variable with const-qualified type 'const int'"]);
invalid!(pre_increment_of_an_array_is_rejected, "int a[3]; void f(void) { ++a; }", &["error: cannot increment value of type 'int[3]'"]);
invalid!(pre_increment_of_a_pointer_to_a_function_is_rejected, "void (*p)(void); void f(void) { ++p; }", &["error: cannot increment value of type 'void (*)(void)'"]);
invalid!(pre_decrement_of_a_pointer_to_a_function_is_rejected, "void (*p)(void); void f(void) { --p; }", &["error: cannot decrement value of type 'void (*)(void)'"]);
invalid!(a_shift_count_at_the_width_of_the_left_operand_is_rejected, "enum E { A = 1 << 32 };", &["warning: shift count >= width of type", "error: Non constant expression"]);
invalid!(a_negative_shift_count_is_rejected, "enum E { A = 1 >> -1 };", &["warning: shift count is negative", "error: Non constant expression"]);
invalid!(an_additive_assignment_with_a_pointer_right_operand_is_rejected, "int *p; int i; void f(void) { i += p; }", &["error: invalid operands to binary expression ('int' and 'int *')"]);
invalid!(a_subtractive_assignment_of_two_pointers_is_rejected, "int *p; int *q; void f(void) { p -= q; }", &["error: invalid operands to binary expression ('int *' and 'int *')"]);
invalid!(an_additive_assignment_to_a_pointer_to_an_incomplete_type_is_rejected, "struct S; struct S *p; void f(void) { p += 1; }", &["error: invalid operands to binary expression ('struct S *' and 'int')"]);
invalid!(an_additive_assignment_to_a_void_pointer_is_rejected, "void *p; void f(void) { p += 1; }", &["error: invalid operands to binary expression ('void *' and 'int')"]);
invalid!(an_additive_assignment_to_a_const_operand_is_rejected, "void f(void) { const int i; i += 1; }", &["error: cannot assign to variable with const-qualified type 'const int'"]);
invalid!(an_additive_assignment_to_an_rvalue_is_rejected, "void f(void) { 1 += 1; }", &["error: expression is not assignable"]);
invalid!(a_remainder_assignment_with_a_floating_left_operand_is_rejected, "double d; void f(void) { d %= 2; }", &["error: invalid operands to binary expression ('double' and 'int')"]);
invalid!(a_remainder_assignment_with_a_floating_right_operand_is_rejected, "int i; void f(void) { i %= 1.5; }", &["error: invalid operands to binary expression ('int' and 'double')"]);
invalid!(a_bitwise_assignment_with_a_floating_operand_is_rejected, "double d; void f(void) { d &= 1; }", &["error: invalid operands to binary expression ('double' and 'int')"]);
invalid!(a_multiplicative_assignment_to_a_pointer_is_rejected, "int *p; void f(void) { p *= 2; }", &["error: invalid operands to binary expression ('int *' and 'int')"]);
invalid!(a_shift_assignment_by_a_floating_count_is_rejected, "int i; void f(void) { i <<= 1.5; }", &["error: invalid operands to binary expression ('int' and 'double')"]);
invalid!(a_compound_assignment_to_a_const_operand_is_rejected, "void f(void) { const int i; i *= 2; }", &["error: cannot assign to variable with const-qualified type 'const int'"]);
invalid!(a_compound_assignment_to_an_rvalue_is_rejected, "void f(void) { 1 &= 1; }", &["error: expression is not assignable"]);
invalid!(a_void_star_cast_of_a_void_star_cast_of_zero_is_not_a_null_pointer_constant, "void (*p)(void); void f(void) { p = (void *)(void *)0; }", &["error: assignment to 'void (*)(void)' from incompatible pointer type 'void *'"]);
invalid!(sizeof_of_a_bit_field_is_rejected, "struct S { int x : 3; } s; void f(void) { sizeof s.x; }", &["error: invalid application of 'sizeof' to bit-field"]);
invalid!(sizeof_of_a_bit_field_reached_through_a_pointer_is_rejected, "struct S { int x : 3; } *p; void f(void) { sizeof p->x; }", &["error: invalid application of 'sizeof' to bit-field"]);
invalid!(a_poisoned_variadic_argument_is_rejected, "void g(int, ...); void f(void) { g(1, missing); }", &["error: Use of undeclared identifier 'missing'"]);
invalid!(an_array_operand_becomes_a_pointer_to_its_first_element, "char a[10]; void f(void) { -a; }", &["error: invalid argument type 'char[10]' to unary expression"]);
invalid!(a_function_designator_becomes_a_pointer_to_function, "int g(); void f(void) { g + 1; }", &["error: arithmetic on a pointer to the function type 'int()'"]);
invalid!(calling_a_prototype_with_too_many_arguments_is_rejected, "int g(int); void f(void) { g(1, 2); }", &["error: too many arguments to function call, expected 1, have 2"]);
invalid!(calling_a_prototype_with_too_few_arguments_is_rejected, "int g(int, int); void f(void) { g(1); }", &["error: too few arguments to function call, expected 2, have 1"]);
invalid!(a_prototype_with_no_parameters_takes_no_argument, "int g(void); void f(void) { g(1); }", &["error: too many arguments to function call, expected 0, have 1"]);
invalid!(a_variadic_call_still_needs_an_argument_for_each_named_parameter, "int g(int, ...); void f(void) { g(); }", &["error: too few arguments to function call, expected 1, have 0"]);
invalid!(an_argument_incompatible_with_its_parameter_is_rejected, "int g(char *); void f(void) { g(1); }", &["error: passing 'int' to parameter 1 of incompatible type 'char *'"]);
invalid!(a_void_argument_is_rejected, "void v(void); int g(int); void f(void) { g(v()); }", &["error: passing 'void' to parameter 1 of incompatible type 'int'"]);
invalid!(calling_an_object_is_rejected, "double d; void f(void) { d(); }", &["error: called object type 'double' is not a function or function pointer"]);
invalid!(calling_an_array_is_rejected, "int arr[3]; void f(void) { arr(); }", &["error: called object type 'int *' is not a function or function pointer"]);
invalid!(calling_the_result_of_a_call_is_rejected, "int g(int); void f(void) { g(1)(2); }", &["error: called object type 'int' is not a function or function pointer"]);
invalid!(calling_a_function_with_an_incomplete_return_type_is_rejected, "struct S; struct S g(void); void f(void) { g(); }", &["error: calling a function with incomplete return type 'struct S'"]);
invalid!(an_argument_without_a_type_does_not_cascade, "int g(int); void f(void) { g(x); }", &["error: Use of undeclared identifier 'x'"]);
invalid!(assigning_to_an_address_is_rejected, "int i, *p; void f(void) { &i = p; }", &["error: expression is not assignable"]);
invalid!(the_address_of_a_constant_is_rejected, "void f(void) { &1; }", &["error: cannot take the address of an rvalue of type 'int'"]);
invalid!(the_address_of_an_enumeration_constant_is_rejected, "enum E { A }; void f(void) { &A; }", &["error: cannot take the address of an rvalue of type 'int'"]);
invalid!(minus_rejects_a_pointer, "int *p; void f(void) { -p; }", &["error: invalid argument type 'int *' to unary expression"]);
invalid!(minus_rejects_a_structure, "struct S { int x; } s; void f(void) { -s; }", &["error: invalid argument type 'struct S' to unary expression"]);
invalid!(unary_plus_rejects_a_pointer, "int *p; void f(void) { +p; }", &["error: invalid argument type 'int *' to unary expression"]);
invalid!(unary_plus_rejects_a_structure, "struct S { int x; } s; void f(void) { +s; }", &["error: invalid argument type 'struct S' to unary expression"]);
invalid!(a_complement_rejects_a_floating_operand, "void f(void) { double d; ~d; }", &["error: invalid argument type 'double' to unary expression"]);
invalid!(a_complement_rejects_a_pointer, "int *p; void f(void) { ~p; }", &["error: invalid argument type 'int *' to unary expression"]);
invalid!(a_logical_negation_rejects_a_structure, "struct S { int x; } s; void f(void) { !s; }", &["error: invalid argument type 'struct S' to unary expression"]);
invalid!(add_rejects_two_structures, "struct S { int x; } s; void f(void) { s + s; }", &["error: invalid operands to binary expression ('struct S' and 'struct S')"]);
invalid!(add_rejects_a_floating_index, "int *p; void f(void) { p + 1.5; }", &["error: invalid operands to binary expression ('int *' and 'double')"]);
invalid!(add_rejects_a_pointer_to_void, "void *p; void f(void) { p + 1; }", &["error: arithmetic on a pointer to an incomplete type 'void'"]);
invalid!(add_rejects_a_pointer_to_an_incomplete_type, "struct S *p; void f(void) { p + 1; }", &["error: arithmetic on a pointer to an incomplete type 'struct S'"]);
invalid!(cast_of_a_non_scalar_operand_is_rejected, "struct S { int a; } s; void f(void) { (int)s; }", &["error: Conversion of non scalar type"]);
invalid!(cast_to_a_non_scalar_type_is_rejected, "struct S { int a; }; void f(void) { (struct S)1; }", &["error: Conversion to non scalar type"]);
invalid!(cast_from_a_pointer_to_a_floating_type_is_rejected, "int *p; void f(void) { (double)p; }", &["error: invalid cast from 'int *' to 'double'"]);
invalid!(cast_from_a_floating_type_to_a_pointer_is_rejected, "double d; void f(void) { (int *)d; }", &["error: invalid cast from 'double' to 'int *'"]);
invalid!(an_integer_minus_a_pointer_is_rejected, "int i; int *p; void f(void) { i - p; }", &["error: invalid operands to binary expression ('int' and 'int *')"]);
invalid!(subtracting_pointers_to_an_incomplete_type_is_rejected, "struct S *p, *q; void f(void) { p - q; }", &["error: arithmetic on a pointer to an incomplete type 'struct S'"]);
invalid!(subtracting_a_floating_index_is_rejected, "int *p; void f(void) { p - 1.5; }", &["error: invalid operands to binary expression ('int *' and 'double')"]);
invalid!(assigning_an_incompatible_pointer_is_rejected, "char *p; int *q; void f(void) { q = p; }", &["error: assignment to 'int *' from incompatible pointer type 'char *'"]);
invalid!(assigning_away_const_through_a_pointer_is_rejected, "const char *p; char *q; void f(void) { q = p; }", &["error: assigning to 'char *' from 'const char *' discards qualifiers"]);
invalid!(assigning_to_an_rvalue_is_rejected, "void f(void) { 1 = 1; }", &["error: expression is not assignable"]);
invalid!(assigning_to_a_const_variable_is_rejected, "void f(void) { const int x; x = 1; }", &["error: cannot assign to variable with const-qualified type 'const int'"]);
invalid!(initializing_a_pointer_with_a_double_is_rejected, "void f(void) { int *p = 3.5; }", &["error: initialization of 'int *' from incompatible pointer type 'double'"]);
invalid!(initializing_with_an_incompatible_pointer_is_rejected, "void f(void) { char *p; int *q = p; }", &["error: initialization of 'int *' from incompatible pointer type 'char *'"]);
invalid!(initializing_away_const_through_a_pointer_is_rejected, "void f(void) { const char *p; char *q = p; }", &["error: initializing 'char *' with an expression of type 'const char *' discards qualifiers"]);
invalid!(array_initializer_with_too_many_elements_is_rejected, "void f(void) { int a[2] = {1,2,3}; }", &["error: excess elements in array initializer"]);
invalid!(scalar_initializer_with_too_many_elements_is_rejected, "void f(void) { int x = {1,2}; }", &["error: excess elements in array initializer"]);
invalid!(excess_elements_in_a_nested_list_do_not_affect_sibling_lists, "void f(void) { int a[2][2] = {{1,2,3},{4,5}}; }", &["error: excess elements in array initializer"]);
invalid!(an_undeclared_identifier_has_no_type, "void f(void) { x; }", &["error: Use of undeclared identifier 'x'"]);
invalid!(an_operand_without_a_type_is_reported_once, "void f(void) { x + 1; }", &["error: Use of undeclared identifier 'x'"]);
invalid!(subscripting_a_structure_is_rejected, "struct S { int x; } s; void f(void) { s[0]; }", &["error: invalid operands to binary expression ('struct S' and 'int')"]);
invalid!(assigning_to_a_member_of_an_rvalue_structure_is_rejected, "struct S { int x; }; struct S g(void); void f(void) { g().x = 1; }", &["error: expression is not assignable"]);
invalid!(a_dot_applied_to_a_pointer_is_rejected, "struct S { int x; } *p; void f(void) { p.x; }", &["error: member reference base type 'struct S *' is not a structure or union"]);
invalid!(a_dot_applied_to_an_enumeration_is_rejected, "enum E { A }; enum E e; void f(void) { e.x; }", &["error: member reference base type 'enum E' is not a structure or union"]);
invalid!(a_member_that_the_structure_does_not_have_is_rejected, "struct S { int x; } s; void f(void) { s.y; }", &["error: no member named 'y' in 'struct S'"]);
invalid!(an_arrow_applied_to_a_structure_is_rejected, "struct S { int x; } s; void f(void) { s->x; }", &["error: member reference base type 'struct S' is not pointer"]);
invalid!(post_increment_of_a_structure_is_rejected, "struct S { int x; } s; void f(void) { s++; }", &["error: cannot increment value of type 'struct S'"]);
invalid!(post_increment_of_a_pointer_to_an_incomplete_type_is_rejected, "struct S; struct S *p; void f(void) { p++; }", &["error: incomplete definition of type 'struct S'"]);
invalid!(post_increment_of_a_pointer_to_void_is_rejected, "void *p; void f(void) { p++; }", &["error: incomplete definition of type 'void'"]);
invalid!(assigning_to_a_pre_increment_is_rejected, "int i; void f(void) { ++i = 1; }", &["error: expression is not assignable"]);
invalid!(pre_increment_of_a_structure_is_rejected, "struct S { int x; } s; void f(void) { ++s; }", &["error: cannot increment value of type 'struct S'"]);
invalid!(pre_decrement_of_a_pointer_to_an_incomplete_type_is_rejected, "struct S; struct S *p; void f(void) { --p; }", &["error: incomplete definition of type 'struct S'"]);
invalid!(multiplying_a_structure_is_rejected, "struct S { int x; } s; void f(void) { s * 1; }", &["error: invalid operands to binary expression ('struct S' and 'int')"]);
invalid!(multiplying_by_a_structure_is_rejected, "struct S { int x; } s; void f(void) { 1 * s; }", &["error: invalid operands to binary expression ('int' and 'struct S')"]);
invalid!(dividing_a_pointer_is_rejected, "int *p; void f(void) { p / 2; }", &["error: invalid operands to binary expression ('int *' and 'int')"]);
invalid!(a_remainder_with_a_floating_right_operand_is_rejected, "void f(void) { 1 % 1.5; }", &["error: invalid operands to binary expression ('int' and 'double')"]);
invalid!(a_remainder_with_a_floating_left_operand_is_rejected, "void f(void) { 1.5 % 1; }", &["error: invalid operands to binary expression ('double' and 'int')"]);
invalid!(shifting_a_floating_left_operand_is_rejected, "void f(void) { 1.5 << 1; }", &["error: invalid operands to binary expression ('double' and 'int')"]);
invalid!(shifting_by_a_floating_count_is_rejected, "void f(void) { 1 << 1.5; }", &["error: invalid operands to binary expression ('int' and 'double')"]);
invalid!(a_rejected_shift_leaves_its_operands_unpromoted, "enum E { A }; enum E e; void f(void) { e << 1.5; }", &["error: invalid operands to binary expression ('enum E' and 'double')"]);
invalid!(pointers_to_functions_may_not_be_ordered, "int (*p)(void); int (*q)(void); void f(void) { p < q; }", &["error: ordered comparison of function pointers ('int (*)(void)' and 'int (*)(void)')"]);
invalid!(pointers_to_incompatible_types_may_not_be_ordered, "int *p; unsigned *q; void f(void) { p < q; }", &["error: comparison of distinct pointer types ('int *' and 'unsigned int *')"]);
invalid!(a_pointer_to_an_incomplete_array_may_not_be_ordered_with_one_to_a_complete_array, "int (*p)[]; int (*q)[3]; void f(void) { p < q; }", &["error: ordered comparison needs two complete or two incomplete pointee types ('int (*)[]' and 'int (*)[3]')"]);
invalid!(a_pointer_may_not_be_ordered_with_a_null_pointer_constant, "int *p; void f(void) { p > 0; }", &["error: invalid operands to binary expression ('int *' and 'int')"]);
invalid!(a_pointer_to_void_may_not_be_ordered_with_a_pointer_to_an_object, "void *v; int *p; void f(void) { v < p; }", &["error: comparison of distinct pointer types ('void *' and 'int *')"]);
invalid!(a_pointer_to_a_function_may_not_be_compared_to_a_void_pointer, "void *v; int (*p)(void); void f(void) { v == p; }", &["error: comparison of distinct pointer types ('void *' and 'int (*)(void)')"]);
invalid!(a_bitwise_and_with_a_floating_left_operand_is_rejected, "void f(void) { 1.5 & 1; }", &["error: invalid operands to binary expression ('double' and 'int')"]);
invalid!(a_bitwise_xor_with_a_floating_right_operand_is_rejected, "void f(void) { 1 ^ 1.5; }", &["error: invalid operands to binary expression ('int' and 'double')"]);
invalid!(a_bitwise_or_with_a_pointer_operand_is_rejected, "int *p; void f(void) { p | 1; }", &["error: invalid operands to binary expression ('int *' and 'int')"]);
invalid!(combining_two_pointers_bitwise_is_rejected, "int *p; void f(void) { p & p; }", &["error: invalid operands to binary expression ('int *' and 'int *')"]);
invalid!(a_bitwise_and_with_a_structure_operand_is_rejected, "struct S { int x; } s; void f(void) { s & 1; }", &["error: invalid operands to binary expression ('struct S' and 'int')"]);
invalid!(an_array_operand_of_a_bitwise_or_is_rejected_after_it_decays, "char a[10]; void f(void) { a | 1; }", &["error: invalid operands to binary expression ('char[10]' and 'int')"]);
invalid!(a_rejected_bitwise_and_leaves_its_operands_unpromoted, "enum E { A }; enum E e; void f(void) { e & 1.5; }", &["error: invalid operands to binary expression ('enum E' and 'double')"]);
invalid!(a_logical_and_with_a_structure_left_operand_is_rejected, "struct S { int x; } s; void f(void) { s && 1; }", &["error: invalid operands to binary expression ('struct S' and 'int')"]);
invalid!(a_logical_or_with_a_structure_right_operand_is_rejected, "struct S { int x; } s; void f(void) { 1 || s; }", &["error: invalid operands to binary expression ('int' and 'struct S')"]);
invalid!(comparing_structures_for_equality_is_rejected, "struct S { int x; } s; void f(void) { s == s; }", &["error: invalid operands to binary expression ('struct S' and 'struct S')"]);
invalid!(a_conditional_with_a_non_scalar_controlling_expression_is_rejected, "struct S { int x; } s; void f(void) { s ? 1 : 2; }", &["error: used type 'struct S' where arithmetic or pointer type is required"]);
invalid!(a_conditional_mixing_an_arithmetic_and_a_pointer_operand_is_rejected, "int *p; void f(int c) { c ? 1 : p; }", &["error: incompatible operand types ('int' and 'int *')"]);
invalid!(a_conditional_between_incompatible_object_pointers_is_rejected, "int *p; char *q; void f(int c) { c ? p : q; }", &["error: pointer type mismatch ('int *' and 'char *')"]);
invalid!(subscripting_a_non_pointer_is_rejected, "void f(void) { int i; i[0]; }", &["error: subscripted value is not an array, pointer, or vector"]);
invalid!(sizeof_of_a_function_designator_is_rejected, "int g(void); void f(void) { sizeof g; }", &["error: invalid application of 'sizeof' to a function type"]);
valid!(a_constant_is_an_rvalue, "void f(void) { 1; }\nint main(void) { return 0; }", 0, "");
valid!(an_identifier_is_an_lvalue, "int i; void f(void) { i; }\nint main(void) { return 0; }", 0, "");
valid!(an_enumeration_constant_is_an_rvalue, "enum E { A }; void f(void) { A; }\nint main(void) { return 0; }", 0, "");
valid!(a_string_literal_is_an_array_lvalue, "void f(void) { \"ab\"; }\nint main(void) { return 0; }", 0, "");
valid!(an_operand_is_converted_to_the_value_it_designates, "int i; void f(void) { -i; }\nint main(void) { return 0; }", 0, "");
valid!(a_char_operand_promotes_to_int, "char c; void f(void) { -c; }\nint main(void) { return 0; }", 0, "");
valid!(a_short_operand_promotes_to_int, "short s; void f(void) { -s; }\nint main(void) { return 0; }", 0, "");
valid!(a_double_operand_is_left_alone, "double d; void f(void) { -d; }\nint main(void) { return 0; }", 0, "");
valid!(both_operands_of_an_addition_promote, "char c; void f(void) { c + c; }\nint main(void) { return 0; }", 0, "");
valid!(a_constant_carries_the_type_of_its_suffix, "void f(void) { 1; 1u; 1l; 1ul; 1.5f; 1.5; 1.5l; }\nint main(void) { return 0; }", 0, "");
valid!(a_character_constant_is_an_int, "void f(void) { 'a'; }\nint main(void) { return 0; }", 0, "");
valid!(two_constants_stay_int, "void f(void) { 1 + 2; }\nint main(void) { return 0; }", 0, "");
valid!(an_integer_and_a_double_meet_at_double, "int i; double d; void f(void) { i + d; }\nint main(void) { return 0; }", 0, "");
valid!(an_integer_and_a_float_meet_at_float, "float g; int i; void f(void) { g + i; }\nint main(void) { return 0; }", 0, "");
valid!(an_int_converts_to_the_unsigned_int_it_meets, "unsigned u; int i; void f(void) { u + i; }\nint main(void) { return 0; }", 0, "");
valid!(a_call_has_the_return_type_of_the_function_and_is_an_rvalue, "int g(void); void f(void) { g(); }\nint main(void) { return 0; }\nint g(void) { return 0; }", 0, "");
valid!(a_call_to_a_function_returning_void_has_type_void, "void g(void); void f(void) { g(); }\nint main(void) { return 0; }\nvoid g(void) {  }", 0, "");
valid!(a_call_returning_a_structure_is_an_rvalue, "struct S { int a; }; struct S g(void); void f(void) { g(); }\nint main(void) { return 0; }\nstruct S g(void) { struct S value = { 0 }; return value; }", 0, "");
valid!(an_argument_is_converted_as_if_by_assignment_to_its_parameter, "int g(char, float); void f(void) { g(1, 2); }\nint main(void) { return 0; }\nint g(char p0, float p1) { return 0; }", 0, "");
valid!(an_array_argument_becomes_a_pointer_to_its_first_element, "int g(char *); char a[4]; void f(void) { g(a); }\nint main(void) { return 0; }\nint g(char * p0) { return 0; }", 0, "");
valid!(a_structure_argument_is_passed_by_value, "struct S { int a; }; int g(struct S); struct S s; void f(void) { g(s); }\nint main(void) { return 0; }\nint g(struct S p0) { return 0; }", 0, "");
valid!(an_argument_pointer_may_gain_the_qualifiers_of_its_parameter, "int g(const char *); char *p; void f(void) { g(p); }\nint main(void) { return 0; }\nint g(const char * p0) { return 0; }", 0, "");
valid!(a_null_pointer_constant_may_be_passed_to_a_pointer_parameter, "int g(char *); void f(void) { g(0); }\nint main(void) { return 0; }\nint g(char * p0) { return 0; }", 0, "");
valid!(a_parameter_qualifier_is_not_part_of_the_function_type, "int g(const int); void f(void) { g(1); }\nint main(void) { return 0; }\nint g(const int p0) { return 0; }", 0, "");
valid!(an_enumeration_parameter_takes_an_integer_argument, "enum E { A }; int g(enum E); void f(void) { g(A); }\nint main(void) { return 0; }\nint g(enum E p0) { return 0; }", 0, "");
valid!(a_variadic_prototype_accepts_arguments_past_its_named_parameters, "int g(int, ...); void f(void) { g(1, 2, 3); }\nint main(void) { return 0; }\nint g(int p0, ...) { return 0; }", 0, "");
valid!(a_call_may_go_through_a_pointer_to_function, "int (*p)(int); void f(void) { p(1); }\nint main(void) { return 0; }", 0, "");
valid!(a_call_may_go_through_a_typedefed_function_pointer, "typedef int F(int); F *q; void f(void) { q(1); }\nint main(void) { return 0; }", 0, "");
valid!(calling_a_function_returning_a_completed_type_is_accepted, "struct S { int x; }; struct S g(void); void f(void) { g(); }\nint main(void) { return 0; }\nstruct S g(void) { struct S value = { 0 }; return value; }", 0, "");
valid!(the_result_of_a_call_is_an_unqualified_rvalue, "const int g(void); void f(void) { g(); }\nint main(void) { return 0; }\nconst int g(void) { return 0; }", 0, "");
valid!(a_trailing_argument_is_promoted, "int g(int, ...); void f(void) { char c; float x; g(1, c, x); }\nint main(void) { return 0; }\nint g(int p0, ...) { return 0; }", 0, "");
valid!(a_trailing_array_argument_becomes_a_pointer, "int g(int, ...); char a[4]; void f(void) { g(1, a); }\nint main(void) { return 0; }\nint g(int p0, ...) { return 0; }", 0, "");
valid!(an_argument_of_a_call_without_a_prototype_is_promoted, "int g(); void f(void) { char c; g(c); }\nint main(void) { return 0; }\nint g(void) { return 0; }", 0, "");
valid!(the_address_of_an_object_is_a_pointer_to_it, "int i; void f(void) { &i; }\nint main(void) { return 0; }", 0, "");
valid!(the_address_of_an_array_is_a_pointer_to_the_array, "int a[3]; void f(void) { &a; }\nint main(void) { return 0; }", 0, "");
valid!(the_address_of_a_function_is_a_pointer_to_function, "int g(void); void f(void) { &g; }\nint main(void) { return 0; }", 0, "");
valid!(the_address_of_a_const_object_points_to_a_const_type, "void f(void) { const int c; &c; }\nint main(void) { return 0; }", 0, "");
valid!(the_address_of_a_volatile_object_points_to_a_volatile_type, "void f(void) { volatile int v; &v; }\nint main(void) { return 0; }", 0, "");
valid!(the_address_of_a_member_is_a_pointer_to_it, "struct S { int x; } s; void f(void) { &s.x; }\nint main(void) { return 0; }", 0, "");
valid!(the_address_of_an_array_element_is_a_pointer_to_it, "int a[3]; void f(void) { &a[0]; }\nint main(void) { return 0; }", 0, "");
valid!(the_address_of_a_string_literal_is_a_pointer_to_the_array, "void f(void) { &\"ab\"; }\nint main(void) { return 0; }", 0, "");
valid!(the_address_of_a_dereference_is_the_pointer_itself, "int *p; void f(void) { &*p; }\nint main(void) { return 0; }", 0, "");
valid!(the_address_of_a_plain_member_beside_a_bit_field_is_accepted, "struct S { int x : 3; int y; } s; void f(void) { &s.y; }\nint main(void) { return 0; }", 0, "");
valid!(indirection_through_a_pointer_designates_an_object, "int *p; void f(void) { *p; }\nint main(void) { return 0; }", 0, "");
valid!(indirection_on_a_pointer_to_void_is_a_void_expression, "void f(void *v) { *v; }\nint main(void) { return 0; }", 0, "", warnings = &["warning: dereferencing 'void *' pointer"]);
valid!(unary_plus_yields_the_value_of_its_operand, "int i; void f(void) { +i; }\nint main(void) { return 0; }", 0, "");
valid!(unary_plus_promotes_its_operand, "void f(void) { char c; +c; }\nint main(void) { return 0; }", 0, "");
valid!(a_complement_yields_the_promoted_type_of_its_operand, "int i; void f(void) { ~i; }\nint main(void) { return 0; }", 0, "");
valid!(a_complement_promotes_its_operand, "void f(void) { char c; ~c; }\nint main(void) { return 0; }", 0, "");
valid!(a_complement_of_an_unsigned_operand_stays_unsigned, "void f(void) { unsigned u; ~u; }\nint main(void) { return 0; }", 0, "");
valid!(a_logical_negation_has_type_int, "int i; void f(void) { !i; }\nint main(void) { return 0; }", 0, "");
valid!(a_logical_negation_of_a_floating_operand_has_type_int, "void f(void) { double d; !d; }\nint main(void) { return 0; }", 0, "");
valid!(a_logical_negation_of_a_pointer_has_type_int, "int *p; void f(void) { !p; }\nint main(void) { return 0; }", 0, "");
valid!(a_logical_negation_does_not_promote_its_operand, "void f(void) { char c; !c; }\nint main(void) { return 0; }", 0, "");
valid!(a_logical_negation_of_an_array_is_accepted, "int a[3]; void f(void) { !a; }\nint main(void) { return 0; }", 0, "");
valid!(a_logical_negation_of_a_function_designator_is_accepted, "int g(); void f(void) { !g; }\nint main(void) { return 0; }", 0, "");
valid!(a_pointer_plus_an_integer_is_a_pointer, "int *p; void f(void) { p + 1; }\nint main(void) { return 0; }", 0, "");
valid!(an_integer_plus_a_pointer_is_a_pointer, "int *p; void f(void) { 1 + p; }\nint main(void) { return 0; }", 0, "");
valid!(an_array_plus_an_integer_is_a_pointer_to_the_element, "char a[10]; void f(void) { a + 1; }\nint main(void) { return 0; }", 0, "");
valid!(a_cast_result_is_always_an_rvalue, "int i; void f(void) { (double)i; }\nint main(void) { return 0; }", 0, "");
valid!(a_pointer_may_be_cast_to_an_integer, "int *p; void f(void) { (int)p; }\nint main(void) { return 0; }", 0, "");
valid!(an_integer_may_be_cast_to_a_pointer, "int i; void f(void) { (int *)i; }\nint main(void) { return 0; }", 0, "");
valid!(a_cast_to_void_discards_the_value, "void f(void) { (void)1; }\nint main(void) { return 0; }", 0, "");
valid!(a_constant_expression_mirrors_its_operand, "int a[2 + 3];\nint main(void) { return 0; }", 0, "");
valid!(a_pointer_minus_an_integer_is_a_pointer, "int *p; void f(void) { p - 1; }\nint main(void) { return 0; }", 0, "");
valid!(two_compatible_pointers_subtract_to_ptrdiff_t, "int *p, *q; void f(void) { p - q; }\nint main(void) { return 0; }", 0, "");
valid!(pointer_subtraction_works_for_any_compatible_object_type, "char *p, *q; void f(void) { p - q; }\nint main(void) { return 0; }", 0, "");
valid!(assigning_a_constant_keeps_the_lvalues_type, "int x; void f(void) { x = 1; }\nint main(void) { return 0; }", 0, "");
valid!(assigning_to_a_volatile_object_has_unqualified_result, "volatile int x; void f(void) { x = 1; }\nint main(void) { return 0; }", 0, "");
valid!(assignment_converts_the_right_operand_to_the_left_operands_type, "int x; void f(void) { x = 3.5; }\nint main(void) { return 0; }", 0, "");
valid!(zero_is_a_null_pointer_constant, "int *p; void f(void) { p = 0; }\nint main(void) { return 0; }", 0, "");
valid!(assigning_a_pointer_that_gains_const_is_accepted, "char *p; const char *q; void f(void) { q = p; }\nint main(void) { return 0; }", 0, "");
valid!(initializing_with_a_constant_keeps_its_type, "void f(void) { int x = 1; }\nint main(void) { return 0; }", 0, "");
valid!(initialization_converts_the_initializer_to_the_declared_type, "void f(void) { int x = 3.5; }\nint main(void) { return 0; }", 0, "");
valid!(zero_initializes_a_pointer_as_a_null_pointer_constant, "void f(void) { int *p = 0; }\nint main(void) { return 0; }", 0, "");
valid!(initializing_a_pointer_that_gains_const_is_accepted, "void f(void) { char *p; const char *q = p; }\nint main(void) { return 0; }", 0, "");
valid!(array_initializer_types_each_element, "void f(void) { int a[3] = {1,2,3}; }\nint main(void) { return 0; }", 0, "");
valid!(array_initializer_may_have_fewer_elements_than_declared, "void f(void) { int a[3] = {1,2}; }\nint main(void) { return 0; }", 0, "");
valid!(incomplete_array_size_is_inferred_from_initializer, "void f(void) { int a[] = {1,2,3}; }\nint main(void) { return 0; }", 0, "");
valid!(scalar_initializer_may_be_wrapped_in_braces, "void f(void) { int x = {1}; }\nint main(void) { return 0; }", 0, "");
valid!(nested_array_initializer_types_every_element, "void f(void) { int a[2][2] = {{1,2},{3,4}}; }\nint main(void) { return 0; }", 0, "");
valid!(array_initializer_converts_each_element_to_the_declared_type, "void f(void) { int a[2] = {1, 3.5}; }\nint main(void) { return 0; }", 0, "");
valid!(array_of_pointers_initializer_accepts_null_pointer_constants, "void f(void) { int *a[2] = {0, 0}; }\nint main(void) { return 0; }", 0, "");
valid!(subscripting_an_array_designates_an_element, "int a[3]; void f(void) { a[0]; }\nint main(void) { return 0; }", 0, "");
valid!(subscripting_a_pointer_designates_the_object_it_points_to, "int *p; void f(void) { p[1]; }\nint main(void) { return 0; }", 0, "");
valid!(a_subscript_may_precede_the_array, "int a[3]; void f(void) { 0[a]; }\nint main(void) { return 0; }", 0, "");
valid!(a_subscripted_element_is_assignable, "int a[3]; void f(void) { a[0] = 1; }\nint main(void) { return 0; }", 0, "");
valid!(subscripting_an_array_of_arrays_designates_a_row, "int a[2][3]; void f(void) { a[0]; }\nint main(void) { return 0; }", 0, "");
valid!(a_member_of_a_structure_lvalue_is_an_lvalue, "struct S { int x; } s; void f(void) { s.x; }\nint main(void) { return 0; }", 0, "");
valid!(a_member_reached_through_a_pointer_is_an_lvalue, "struct S { int x; } *p; void f(void) { p->x; }\nint main(void) { return 0; }", 0, "");
valid!(a_union_member_has_the_type_of_the_named_member, "union U { int x; double y; } u; void f(void) { u.y; }\nint main(void) { return 0; }", 0, "");
valid!(a_member_of_an_rvalue_structure_is_an_rvalue, "struct S { int x; }; struct S g(void); void f(void) { g().x; }\nint main(void) { return 0; }\nstruct S g(void) { struct S value = { 0 }; return value; }", 0, "");
valid!(a_member_of_a_const_structure_is_const, "struct S { int x; }; void f(void) { const struct S s; s.x; }\nint main(void) { return 0; }", 0, "");
valid!(a_member_reached_through_a_pointer_to_const_is_const, "struct S { int x; }; void f(void) { const struct S *p; p->x; }\nint main(void) { return 0; }", 0, "");
valid!(a_member_of_a_volatile_structure_is_volatile, "volatile struct S { int x; } s; void f(void) { s.x; }\nint main(void) { return 0; }", 0, "");
valid!(post_increment_yields_the_value_of_its_operand, "int i; void f(void) { i++; }\nint main(void) { return 0; }", 0, "");
valid!(post_decrement_yields_the_value_of_its_operand, "double d; void f(void) { d--; }\nint main(void) { return 0; }", 0, "");
valid!(post_increment_of_a_pointer_is_a_pointer, "int *p; void f(void) { p++; }\nint main(void) { return 0; }", 0, "");
valid!(post_increment_keeps_the_type_of_its_operand, "char c; void f(void) { c++; }\nint main(void) { return 0; }", 0, "");
valid!(pre_increment_yields_the_value_of_its_operand, "int i; void f(void) { ++i; }\nint main(void) { return 0; }", 0, "");
valid!(pre_decrement_yields_the_value_of_its_operand, "double d; void f(void) { --d; }\nint main(void) { return 0; }", 0, "");
valid!(pre_increment_of_a_pointer_is_a_pointer, "int *p; void f(void) { ++p; }\nint main(void) { return 0; }", 0, "");
valid!(pre_increment_keeps_the_type_of_its_operand, "char c; void f(void) { ++c; }\nint main(void) { return 0; }", 0, "");
valid!(multiplying_two_constants_stays_int, "void f(void) { 2 * 3; }\nint main(void) { return 0; }", 0, "");
valid!(the_remainder_of_two_integers_is_an_integer, "void f(void) { 7 % 2; }\nint main(void) { return 0; }", 0, "");
valid!(multiplication_performs_the_usual_arithmetic_conversions, "int i; double d; void f(void) { i * d; }\nint main(void) { return 0; }", 0, "");
valid!(a_floating_division_by_zero_is_accepted, "void f(void) { 1 / 0.0; }\nint main(void) { return 0; }", 0, "");
valid!(a_shift_of_two_constants_is_an_int, "void f(void) { 1 << 2; }\nint main(void) { return 0; }", 0, "");
valid!(a_shift_count_below_the_width_of_the_promoted_left_operand_is_accepted, "void f(void) { 1 << 5; }\nint main(void) { return 0; }", 0, "");
valid!(the_left_operand_of_a_shift_is_promoted, "char c; void f(void) { c << 1; }\nint main(void) { return 0; }", 0, "");
valid!(an_enumeration_may_be_shifted, "enum E { A }; enum E e; void f(void) { e << 1; }\nint main(void) { return 0; }", 0, "");
valid!(a_shift_has_the_type_of_its_promoted_left_operand, "int i; long l; void f(void) { i << l; }\nint main(void) { return 0; }", 0, "");
valid!(the_operands_of_a_shift_are_promoted_independently, "unsigned u; void f(void) { u >> 1; }\nint main(void) { return 0; }", 0, "");
valid!(a_char_left_operand_is_measured_after_its_promotion, "char c; void f(void) { c << 10; }\nint main(void) { return 0; }", 0, "");
valid!(a_short_left_operand_is_measured_after_its_promotion, "short s; void f(void) { s << 20; }\nint main(void) { return 0; }", 0, "");
valid!(a_count_one_below_the_width_of_the_left_operand_is_accepted, "int i; void f(void) { i << 31; }\nint main(void) { return 0; }", 0, "");
valid!(the_type_of_the_count_does_not_bound_the_shift, "int i; void f(void) { i << (short)20; }\nint main(void) { return 0; }", 0, "");
valid!(a_shift_by_a_variable_count_promotes_its_operands, "char c; int n; void f(void) { c << n; }\nint main(void) { return 0; }", 0, "");
valid!(an_enumeration_may_be_shifted_by_a_variable_count, "enum E { A }; enum E e; int n; void f(void) { e << n; }\nint main(void) { return 0; }", 0, "");
valid!(pointers_to_compatible_object_types_may_be_ordered, "int *p; int *q; void f(void) { p < q; }\nint main(void) { return 0; }", 0, "");
valid!(ordering_pointers_disregards_the_qualifiers_of_the_pointed_to_type, "const int *p; int *q; void f(void) { p < q; }\nint main(void) { return 0; }", 0, "");
valid!(pointers_to_an_incomplete_structure_may_be_ordered, "struct S; struct S *p; struct S *q; void f(void) { p >= q; }\nint main(void) { return 0; }", 0, "");
valid!(pointers_to_void_may_be_ordered, "void *p; void *q; void f(void) { p > q; }\nint main(void) { return 0; }", 0, "");
valid!(ordering_arithmetic_operands_performs_the_usual_arithmetic_conversions, "int i; double d; void f(void) { i < d; }\nint main(void) { return 0; }", 0, "");
valid!(an_array_operand_of_an_ordering_decays_to_a_pointer, "int a[3]; int *p; void f(void) { a < p; }\nint main(void) { return 0; }", 0, "");
valid!(pointers_to_compatible_incomplete_arrays_may_be_ordered, "int (*p)[]; int (*q)[]; void f(void) { p < q; }\nint main(void) { return 0; }", 0, "");
valid!(a_pointer_compared_to_a_null_pointer_constant_converts_the_constant, "int *p; void f(void) { p == 0; }\nint main(void) { return 0; }", 0, "");
valid!(a_null_pointer_constant_may_be_the_left_operand, "int *p; void f(void) { 0 != p; }\nint main(void) { return 0; }", 0, "");
valid!(a_pointer_to_a_function_may_be_compared_to_a_null_pointer_constant, "int (*p)(void); void f(void) { p == 0; }\nint main(void) { return 0; }", 0, "");
valid!(an_object_pointer_compared_to_a_void_pointer_is_converted_to_void_pointer, "void *v; int *p; void f(void) { v == p; }\nint main(void) { return 0; }", 0, "");
valid!(an_incomplete_pointer_compared_to_a_void_pointer_is_converted_to_void_pointer, "struct S; struct S *p; void *v; void f(void) { p != v; }\nint main(void) { return 0; }", 0, "");
valid!(comparing_a_qualified_pointer_to_a_void_pointer_discards_its_qualifiers, "void *v; const int *p; void f(void) { v == p; }\nint main(void) { return 0; }", 0, "");
valid!(a_bitwise_and_of_two_constants_is_an_int, "void f(void) { 6 & 3; }\nint main(void) { return 0; }", 0, "");
valid!(a_bitwise_xor_of_two_constants_is_an_int, "void f(void) { 6 ^ 3; }\nint main(void) { return 0; }", 0, "");
valid!(a_bitwise_or_of_two_constants_is_an_int, "void f(void) { 6 | 3; }\nint main(void) { return 0; }", 0, "");
valid!(the_operands_of_a_bitwise_and_are_promoted, "char c; void f(void) { c & c; }\nint main(void) { return 0; }", 0, "");
valid!(a_bitwise_xor_converts_its_operands_to_a_common_type, "int i; unsigned u; void f(void) { i ^ u; }\nint main(void) { return 0; }", 0, "");
valid!(a_bitwise_or_with_a_long_operand_meets_at_long, "int i; long l; void f(void) { i | l; }\nint main(void) { return 0; }", 0, "");
valid!(an_enumeration_may_be_combined_bitwise, "enum E { A }; enum E e; void f(void) { e & 1; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_two_pointers_to_the_same_type_keeps_that_type, "int *p, *q; void f(int c) { c ? p : q; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_pointers_to_array_takes_the_known_size, "int a[3]; extern int b[]; void f(int c) { c ? &a : &b; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_pointers_to_unsized_arrays_stays_unsized, "extern int b[]; extern int d[]; void f(int c) { c ? &b : &d; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_function_pointers_keeps_the_parameter_type_list, "int g(int); int h(); void f(int c) { c ? g : h; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_pointers_unions_the_qualifiers_of_the_pointed_to_types, "volatile int *vp; const int *cp; void f(int c) { c ? vp : cp; }\nint main(void) { return 0; }", 0, "");
valid!(the_composite_type_is_built_recursively, "int (*x[])(int); int (*y[])(); void f(int c) { c ? &x : &y; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_arithmetic_operands_meets_at_a_common_type, "int i; double d; void f(int c) { c ? i : d; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_two_structures_keeps_the_structure_type, "struct S { int x; } s, t; void f(int c) { c ? s : t; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_a_const_and_a_plain_structure_keeps_the_structure_type, "struct S { int x; }; const struct S s; struct S t; void f(int c) { c ? s : t; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_a_volatile_and_a_plain_union_keeps_the_union_type, "union U { int x; }; volatile union U u; union U v; void f(int c) { c ? u : v; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_two_void_operands_is_void, "void g(void); void h(void); void f(int c) { c ? g() : h(); }\nvoid g(void) { } void h(void) { } int main(void) { f(0); f(1); return 0; }", 0, "");
valid!(a_conditional_with_a_null_pointer_constant_takes_the_other_pointer_type, "int *p; void f(int c) { c ? p : 0; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_a_void_pointer_and_an_object_pointer_is_a_void_pointer, "void *vp; int *p; void f(int c) { c ? vp : p; }\nint main(void) { return 0; }", 0, "");
valid!(a_composite_parameter_list_composes_each_parameter, "int g(int (*)[3]); int h(int (*)[]); void f(int c) { c ? g : h; }\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_two_unspecified_functions_stays_unspecified, "int g(); int h(); void f(int c) { c ? g : h; }\nint main(void) { return 0; }", 0, "");
valid!(a_composite_prototype_keeps_the_ellipsis, "int g(int, ...); int h(int, ...); void f(int c) { c ? g : h; }\nint main(void) { return 0; }", 0, "");
valid!(the_return_type_of_a_composite_function_is_composite, "int (*g(void))[3]; int (*h(void))[]; void f(int c) { c ? g : h; }\nint main(void) { return 0; }", 0, "");
valid!(a_null_pointer_constant_may_be_the_second_operand, "int *p; void f(int c) { c ? 0 : p; }\nint main(void) { return 0; }", 0, "");
valid!(a_void_pointer_may_be_the_third_operand, "void *vp; int *p; void f(int c) { c ? p : vp; }\nint main(void) { return 0; }", 0, "");
valid!(a_logical_and_of_two_constants_is_an_int, "void f(void) { 1 && 2; }\nint main(void) { return 0; }", 0, "");
valid!(a_logical_or_of_two_constants_is_an_int, "void f(void) { 0 || 1; }\nint main(void) { return 0; }", 0, "");
valid!(an_array_operand_of_a_logical_or_decays_to_a_pointer, "int a[3]; void f(void) { a || 0; }\nint main(void) { return 0; }", 0, "");
valid!(a_comma_expression_has_the_type_of_its_right_operand, "double d; int i; void f(void) { d, i; }\nint main(void) { return 0; }", 0, "");
valid!(every_operand_but_the_last_of_a_comma_is_discarded_to_void, "void f(void) { 1, 2, 3; }\nint main(void) { return 0; }", 0, "");
valid!(an_additive_assignment_of_an_int_yields_an_int, "int i; void f(void) { i += 1; }\nint main(void) { return 0; }", 0, "");
valid!(an_additive_assignment_converts_the_result_back_to_the_left_operand_type, "int i; void f(void) { i += 1.5; }\nint main(void) { return 0; }", 0, "");
valid!(an_additive_assignment_to_a_pointer_stays_a_pointer, "int *p; void f(void) { p += 2; }\nint main(void) { return 0; }", 0, "");
valid!(an_additive_assignment_to_a_volatile_operand_has_unqualified_type, "volatile int i; void f(void) { i += 1; }\nint main(void) { return 0; }", 0, "");
valid!(a_multiplicative_assignment_of_an_int_yields_an_int, "int i; void f(void) { i *= 2; }\nint main(void) { return 0; }", 0, "");
valid!(a_multiplicative_assignment_converts_the_result_back_to_the_left_operand_type, "int i; void f(void) { i *= 1.5; }\nint main(void) { return 0; }", 0, "");
valid!(a_bitwise_assignment_promotes_the_left_operand_and_narrows_the_result, "char c; void f(void) { c &= 1; }\nint main(void) { return 0; }", 0, "");
valid!(a_shift_assignment_has_the_type_of_its_left_operand, "int i; long n; void f(void) { i <<= n; }\nint main(void) { return 0; }", 0, "");
valid!(equality_of_two_arithmetic_operands_is_an_int, "void f(void) { 1 == 2; }\nint main(void) { return 0; }", 0, "");
valid!(comparing_two_compatible_object_pointers_is_an_int, "int *p; int *q; void f(void) { p == q; }\nint main(void) { return 0; }", 0, "");
valid!(enum_without_negative_points_as_unsigned, "enum E { A, B } e; unsigned int *p = &e;\nint main(void) { return 0; }", 0, "");
invalid!(enum_without_negative_is_not_int, "enum E { A, B } e; int *p = &e;", &["error: initialization of 'int *' from incompatible pointer type 'enum E *'"]);
valid!(enum_without_negative_is_unsigned, "enum E { A, B }; int main(void) { enum E x = A; return x - 1 < 0; }", 0, "");
valid!(enum_with_negative_points_as_int, "enum E { A = -1, B } e; int *p = &e;\nint main(void) { return 0; }", 0, "");
invalid!(enum_with_negative_is_not_unsigned, "enum E { A = -1, B } e; unsigned int *p = &e;", &["error: initialization of 'unsigned int *' from incompatible pointer type 'enum E *'"]);
valid!(enum_with_negative_is_signed, "enum E { A = -1, B }; int main(void) { enum E x = B; return x - 1 < 0; }", 1, "");
valid!(enum_without_negative_converts_to_floating_as_unsigned, "enum E { A }; int main(void) { enum E x = (enum E)0x80000000u; return (double)x > 0; }", 1, "");
valid!(enum_without_negative_shifts_right_logically, "enum E { A }; int main(void) { enum E x = (enum E)0x80000000u; return (x >> 31) == 1; }", 1, "");
valid!(a_parenthesized_zero_is_a_null_pointer_constant, "int *p = (0);\nint main(void) { return 0; }", 0, "");
valid!(a_parenthesized_void_star_cast_of_zero_is_a_null_pointer_constant, "int *p = ((void *)0);\nint main(void) { return 0; }", 0, "");
valid!(a_character_zero_is_a_null_pointer_constant, "int *p = '\\0';\nint main(void) { return 0; }", 0, "");
valid!(a_folded_difference_is_a_null_pointer_constant, "int *p = 1 - 1;\nint main(void) { return 0; }", 0, "");
valid!(a_void_star_cast_of_a_folded_difference_is_a_null_pointer_constant, "int *p = (void *)(1 - 1);\nint main(void) { return 0; }", 0, "");
valid!(an_enumerator_of_value_zero_is_a_null_pointer_constant, "enum { E }; int *p = E;\nint main(void) { return 0; }", 0, "");
valid!(a_conditional_of_constants_is_a_null_pointer_constant, "int *p = 1 ? 0 : 0;\nint main(void) { return 0; }", 0, "");
valid!(a_sizeof_difference_is_a_null_pointer_constant, "int *p = sizeof(int) - sizeof(int);\nint main(void) { return 0; }", 0, "");
valid!(a_constant_conditional_may_be_assigned_to_a_pointer_to_function, "void (*p)(void); void f(void) { p = 1 ? 0 : 0; }\nint main(void) { return 0; }", 0, "");
valid!(a_constant_conditional_may_be_compared_to_a_pointer, "int *p; void f(void) { p == (1 ? 0 : 0); }\nint main(void) { return 0; }", 0, "");
valid!(a_null_pointer_constant_may_be_a_conditional_operand_beside_a_pointer, "int *p; void f(int c) { c ? p : 0; }\nint main(void) { return 0; }", 0, "");
valid!(a_null_pointer_constant_may_be_returned_as_a_pointer, "int *f(void) { return (void *)(1 - 1); }\nint main(void) { return 0; }", 0, "");
valid!(a_null_pointer_constant_may_be_passed_to_a_pointer_to_function_parameter, "void g(void (*)(void)); void f(void) { g(1 - 1); }\nint main(void) { return 0; }\nvoid g(void (*p0)(void)) {  }", 0, "");
invalid!(a_conditional_with_a_variable_arm_is_not_a_null_pointer_constant, "int main(void) { int x = 1; int *p = 1 ? 0 : x; return p != 0; }", &["error: initialization of 'int *' from incompatible pointer type 'int'"]);
invalid!(a_logical_and_with_a_variable_operand_is_not_a_null_pointer_constant, "int main(void) { int x = 1; int *p = 0 && x; return p != 0; }", &["error: initialization of 'int *' from incompatible pointer type 'int'"]);
invalid!(a_conditional_with_a_variable_arm_may_not_be_compared_to_a_pointer, "int *p; void f(void) { int x = 1; p == (1 ? 0 : x); }", &["error: invalid operands to binary expression ('int *' and 'int')"]);
invalid!(a_logical_and_with_a_variable_operand_may_not_be_assigned_to_a_pointer, "int *p; void f(void) { int x = 1; p = 0 && x; }", &["error: assignment to 'int *' from incompatible pointer type 'int'"]);
invalid!(cast_to_a_non_scalar_type_is_reported_once, "struct S { int a; }; enum E { A = (struct S)1 };", &["error: Conversion to non scalar type"]);
