#![cfg_attr(rustfmt, rustfmt_skip)]

valid!(offset_plain_with_padding, "struct S { char a; int b; };\n\nint main(void) { struct S value = { 0 }; if ((unsigned long)((char *)&value.a - (char *)&value) != 0ul) return 1; if ((unsigned long)((char *)&value.b - (char *)&value) != 4ul) return 1; return 0; }", 0, "");
valid!(offset_double_alignment, "struct S { char a; double d; };\n\nint main(void) { struct S value = { 0 }; if ((unsigned long)((char *)&value.a - (char *)&value) != 0ul) return 1; if ((unsigned long)((char *)&value.d - (char *)&value) != 4ul) return 1; return 0; }", 0, "");
valid!(offset_array_member, "struct S { char a; int arr[3]; };\n\nint main(void) { struct S value = { 0 }; if ((unsigned long)((char *)&value.a - (char *)&value) != 0ul) return 1; if ((unsigned long)((char *)&value.arr - (char *)&value) != 4ul) return 1; return 0; }", 0, "");
valid!(offset_nested_struct_member, "struct Inner { char x; int y; }; struct S { char a; struct Inner in; };\n\nint main(void) { struct S value = { 0 }; if ((unsigned long)((char *)&value.a - (char *)&value) != 0ul) return 1; if ((unsigned long)((char *)&value.in - (char *)&value) != 4ul) return 1; return 0; }", 0, "");
valid!(offset_union_all_zero, "union U { char a; int b; double d; };\n\nint main(void) { union U value = { 0 }; if ((unsigned long)((char *)&value.a - (char *)&value) != 0ul) return 1; if ((unsigned long)((char *)&value.b - (char *)&value) != 0ul) return 1; if ((unsigned long)((char *)&value.d - (char *)&value) != 0ul) return 1; return 0; }", 0, "");
valid!(offset_bitfields_sharing_a_unit, "struct S { int a:3; int b:4; };\nvoid gcc_set_a(struct S *); int gcc_zero_a(struct S *);\nvoid gcc_set_b(struct S *); int gcc_zero_b(struct S *);\nint main(void) { struct S value = { 0 }; gcc_set_a(&value); if (value.a != -1) return 1; value.a = 0; if (!gcc_zero_a(&value)) return 1; gcc_set_b(&value); if (value.b != -1) return 1; value.b = 0; if (!gcc_zero_b(&value)) return 1; return 0; }", 0, "", helper = "struct S { int a:3; int b:4; };\nvoid gcc_set_a(struct S *p) { p->a = -1; } int gcc_zero_a(struct S *p) { return p->a == 0; }\nvoid gcc_set_b(struct S *p) { p->b = -1; } int gcc_zero_b(struct S *p) { return p->b == 0; }");
valid!(offset_bitfield_opens_a_new_unit, "struct S { int a:20; int b:20; };\nvoid gcc_set_a(struct S *); int gcc_zero_a(struct S *);\nvoid gcc_set_b(struct S *); int gcc_zero_b(struct S *);\nint main(void) { struct S value = { 0 }; gcc_set_a(&value); if (value.a != -1) return 1; value.a = 0; if (!gcc_zero_a(&value)) return 1; gcc_set_b(&value); if (value.b != -1) return 1; value.b = 0; if (!gcc_zero_b(&value)) return 1; return 0; }", 0, "", helper = "struct S { int a:20; int b:20; };\nvoid gcc_set_a(struct S *p) { p->a = -1; } int gcc_zero_a(struct S *p) { return p->a == 0; }\nvoid gcc_set_b(struct S *p) { p->b = -1; } int gcc_zero_b(struct S *p) { return p->b == 0; }");
valid!(offset_unnamed_bitfield_between_named, "struct S { int a:3; int :2; int b:4; };\nvoid gcc_set_a(struct S *); int gcc_zero_a(struct S *);\nvoid gcc_set_b(struct S *); int gcc_zero_b(struct S *);\nint main(void) { struct S value = { 0 }; gcc_set_a(&value); if (value.a != -1) return 1; value.a = 0; if (!gcc_zero_a(&value)) return 1; gcc_set_b(&value); if (value.b != -1) return 1; value.b = 0; if (!gcc_zero_b(&value)) return 1; return 0; }", 0, "", helper = "struct S { int a:3; int :2; int b:4; };\nvoid gcc_set_a(struct S *p) { p->a = -1; } int gcc_zero_a(struct S *p) { return p->a == 0; }\nvoid gcc_set_b(struct S *p) { p->b = -1; } int gcc_zero_b(struct S *p) { return p->b == 0; }");
valid!(offset_zero_width_bitfield, "struct S { int a:1; int :0; int b:1; };\nvoid gcc_set_a(struct S *); int gcc_zero_a(struct S *);\nvoid gcc_set_b(struct S *); int gcc_zero_b(struct S *);\nint main(void) { struct S value = { 0 }; gcc_set_a(&value); if (value.a != -1) return 1; value.a = 0; if (!gcc_zero_a(&value)) return 1; gcc_set_b(&value); if (value.b != -1) return 1; value.b = 0; if (!gcc_zero_b(&value)) return 1; return 0; }", 0, "", helper = "struct S { int a:1; int :0; int b:1; };\nvoid gcc_set_a(struct S *p) { p->a = -1; } int gcc_zero_a(struct S *p) { return p->a == 0; }\nvoid gcc_set_b(struct S *p) { p->b = -1; } int gcc_zero_b(struct S *p) { return p->b == 0; }");
valid!(offset_bitfield_after_char, "struct S { char a; int b:3; };\nvoid gcc_set_b(struct S *); int gcc_zero_b(struct S *);\nint main(void) { struct S value = { 0 }; if ((unsigned long)((char *)&value.a - (char *)&value) != 0ul) return 1; gcc_set_b(&value); if (value.b != -1) return 1; value.b = 0; if (!gcc_zero_b(&value)) return 1; return 0; }", 0, "", helper = "struct S { char a; int b:3; };\nvoid gcc_set_b(struct S *p) { p->b = -1; } int gcc_zero_b(struct S *p) { return p->b == 0; }");
valid!(offset_of_a_tag_reached_only_through_a_pointer, "struct S { char a; int b; }; struct S *p;\n\nint main(void) { struct S value = { 0 }; if ((unsigned long)((char *)&value.a - (char *)&value) != 0ul) return 1; if ((unsigned long)((char *)&value.b - (char *)&value) != 4ul) return 1; return 0; }", 0, "");
valid!(offset_of_a_tag_declared_inside_a_function, "int main(void) { struct S { char a; int b; } value = { 0 }; if ((unsigned long)((char *)&value.a - (char *)&value) != 0ul) return 1; if ((unsigned long)((char *)&value.b - (char *)&value) != 4ul) return 1; return 0; }", 0, "");
valid!(size_single_char, "struct S { char a; };\nint main(void) { return !(sizeof(struct S) == 1); }", 0, "");
valid!(size_single_short, "struct S { short a; };\nint main(void) { return !(sizeof(struct S) == 2); }", 0, "");
valid!(size_single_int, "struct S { int a; };\nint main(void) { return !(sizeof(struct S) == 4); }", 0, "");
valid!(size_single_double, "struct S { double a; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_single_pointer, "struct S { int *p; };\nint main(void) { return !(sizeof(struct S) == 4); }", 0, "");
valid!(size_three_chars, "struct S { char a; char b; char c; };\nint main(void) { return !(sizeof(struct S) == 3); }", 0, "");
valid!(size_two_ints, "struct S { int a; int b; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_char_then_short, "struct S { char a; short b; };\nint main(void) { return !(sizeof(struct S) == 4); }", 0, "");
valid!(size_char_then_int, "struct S { char a; int b; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_char_char_then_int, "struct S { char a; char b; int c; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_short_then_int, "struct S { short a; int b; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_char_then_double, "struct S { char a; double b; };\nint main(void) { return !(sizeof(struct S) == 12); }", 0, "");
valid!(size_char_then_pointer, "struct S { char a; int *p; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_int_then_char, "struct S { int a; char b; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_short_then_char, "struct S { short a; char b; };\nint main(void) { return !(sizeof(struct S) == 4); }", 0, "");
valid!(size_double_then_char, "struct S { double a; char b; };\nint main(void) { return !(sizeof(struct S) == 12); }", 0, "");
valid!(size_pointer_then_char, "struct S { int *p; char c; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_char_int_char, "struct S { char a; int b; char c; };\nint main(void) { return !(sizeof(struct S) == 12); }", 0, "");
valid!(size_long_double_then_char, "struct S { long double a; char b; };\nint main(void) { return !(sizeof(struct S) == 16); }", 0, "");
valid!(size_union_char_int, "union U { char a; int b; };\nint main(void) { return !(sizeof(union U) == 4); }", 0, "");
valid!(size_union_char_double, "union U { char a; double b; };\nint main(void) { return !(sizeof(union U) == 8); }", 0, "");
valid!(size_union_single_char, "union U { char a; };\nint main(void) { return !(sizeof(union U) == 1); }", 0, "");
valid!(size_union_padded_to_alignment, "union U { char a[7]; short b; };\nint main(void) { return !(sizeof(union U) == 8); }", 0, "");
valid!(size_union_of_bitfield, "union U { int a:3; char b; };\nint main(void) { return !(sizeof(union U) == 4); }", 0, "");
valid!(size_array_of_char, "struct S { char a[3]; };\nint main(void) { return !(sizeof(struct S) == 3); }", 0, "");
valid!(size_array_then_int, "struct S { char a[3]; int b; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_array_of_int, "struct S { int a[4]; };\nint main(void) { return !(sizeof(struct S) == 16); }", 0, "");
valid!(size_nested_struct, "struct I { char a; int b; }; struct S { char x; struct I i; };\nint main(void) { return !(sizeof(struct S) == 12); }", 0, "");
valid!(size_nested_struct_of_chars, "struct I { char a; char b; }; struct S { struct I i; char c; };\nint main(void) { return !(sizeof(struct S) == 3); }", 0, "");
valid!(size_nested_union, "union U { char a; int b; }; struct S { char x; union U u; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_enum, "enum E { A };\nint main(void) { return !(sizeof(enum E) == 4); }", 0, "");
valid!(size_struct_of_enum, "enum E { A }; struct S { char c; enum E e; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_char_then_double_array, "struct S { char c; double a[2]; };\nint main(void) { return !(sizeof(struct S) == 20); }", 0, "");
valid!(size_double_array_then_char, "struct S { double a[3]; char c; };\nint main(void) { return !(sizeof(struct S) == 28); }", 0, "");
valid!(size_bitfield_single, "struct S { int a:3; };\nint main(void) { return !(sizeof(struct S) == 4); }", 0, "");
valid!(size_bitfields_share_a_unit, "struct S { int a:3; int b:2; };\nint main(void) { return !(sizeof(struct S) == 4); }", 0, "");
valid!(size_bitfield_does_not_straddle, "struct S { int a:3; int b:30; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_bitfield_fills_a_unit, "struct S { int a:32; int b:1; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_char_then_bitfield, "struct S { char c; int a:1; };\nint main(void) { return !(sizeof(struct S) == 4); }", 0, "");
valid!(size_bitfield_then_char, "struct S { int a:1; char c; };\nint main(void) { return !(sizeof(struct S) == 4); }", 0, "");
valid!(size_unnamed_bitfield_shares_a_unit, "struct S { int a:3; int :2; int b:4; };\nint main(void) { return !(sizeof(struct S) == 4); }", 0, "");
valid!(size_unnamed_bitfield_opens_a_unit, "struct S { int a:3; int :30; int b:4; };\nint main(void) { return !(sizeof(struct S) == 12); }", 0, "");
valid!(size_zero_width_bitfield_closes_the_unit, "struct S { int a:1; int :0; int b:1; };\nint main(void) { return !(sizeof(struct S) == 8); }", 0, "");
valid!(size_unnamed_bitfield_alone_in_a_unit, "struct S { char a; int :17; };\nint main(void) { return !(sizeof(struct S) == 4); }", 0, "");
valid!(size_unnamed_bitfield_keeps_alignment, "struct S { char a; int :1; char b; };\nint main(void) { return !(sizeof(struct S) == 3); }", 0, "");
valid!(size_zero_width_bitfield_keeps_alignment, "struct S { char a; int :0; char b; };\nint main(void) { return !(sizeof(struct S) == 5); }", 0, "");
valid!(size_union_unnamed_bitfield, "union U { char a; int :17; };\nint main(void) { return !(sizeof(union U) == 3); }", 0, "");
valid!(size_union_zero_width_bitfield, "union U { char a; int :0; };\nint main(void) { return !(sizeof(union U) == 1); }", 0, "");
