#![cfg_attr(rustfmt, rustfmt_skip)]

invalid!(stray_hash_after_expression, "int main(void) { return 0 # 1\n; }", &["error: stray '#' in program", "error: syntax error, unexpected CONSTANT, expecting ',' or ';'"]);
invalid!(stray_hash_after_initializer, "int x = 1; int y = x # this is swallowed ; int z;", &["error: stray '#' in program", "error: syntax error, unexpected IDENTIFIER, expecting ',' or ';'"]);
invalid!(stray_hash_is_reported, "int x = 1 # 2;", &["error: stray '#' in program", "error: syntax error, unexpected CONSTANT, expecting ',' or ';'"], preprocessed = true);
invalid!(case_conditional_with_non_constant_arm, "int main(void){ int x = 1; switch (x) { case 1 ? 2 : x: break; } return 0; }", &["error: Non constant expression"]);
invalid!(case_logical_and_with_non_constant_operand, "int main(void){ int x = 1; switch (x) { case 0 && x: break; } return 0; }", &["error: Non constant expression"]);
invalid!(case_logical_or_with_non_constant_operand, "int main(void){ int x = 1; switch (x) { case 1 || x: break; } return 0; }", &["error: Non constant expression"]);
invalid!(array_size_conditional_with_non_constant_arm, "int main(void){ int x = 1; int a[1 ? 2 : x]; return 0; }", &["error: Non constant expression"]);
invalid!(enumerator_logical_and_with_non_constant_operand, "int x; enum { A = 0 && x };", &["error: Non constant expression"]);
valid!(static_initializer_logical_or_non_constant, "int x; int y = 1 || x; int fixture_main(void){ return 0; }\nint main(void) { return 0; }", 0, "");
valid!(static_initializer_logical_and_non_constant, "int x; int y = 0 && x; int fixture_main(void){ return 0; }\nint main(void) { return 0; }", 0, "");
valid!(static_initializer_conditional_non_constant, "int x; int y = 1 ? 2 : x; int fixture_main(void){ return 0; }\nint main(void) { return 0; }", 0, "");
invalid!(static_initializer_conditional_function_call_arm, "int f(void); static int x = 1 ? 2 : f();", &["error: initializer element is not a compile-time constant"]);
invalid!(static_initializer_logical_and_assignment, "int y; static int x = 0 && (y = 2);", &["error: initializer element is not a compile-time constant"]);
invalid!(static_initializer_logical_or_increment, "int y; static int x = 1 || y++;", &["error: initializer element is not a compile-time constant"]);
invalid!(static_initializer_conditional_comma_arm, "static int x = 1 ? 2 : (3, 4);", &["error: initializer element is not a compile-time constant"]);
invalid!(aggregate_initializer_conditional_function_call_arm, "int f(void); int main(void) { int a[2] = { 1 ? 2 : f(), 3 }; return a[0]; }", &["error: initializer element is not a compile-time constant"]);
invalid!(static_initializer_conditional_function_call_arm_message, "int f(void); static int x = 1 ? 2 : f();", &["error: initializer element is not a compile-time constant"], preprocessed = true);
valid!(static_initializer_sizeof_function_call, "int f(void); static int s = sizeof(f()); int fixture_main(void){ return 0; }\nint main(void) { return 0; }", 0, "");
valid!(static_initializer_sizeof_assignment, "int y; static int t = sizeof(y = 2); int fixture_main(void){ return 0; }\nint main(void) { return 0; }", 0, "");
valid!(automatic_initializer_conditional_function_call_arm, "int f(void) { return 1; } int main(void) { int v = 1 ? 2 : f(); return v - 2; }", 0, "");
valid!(case_unevaluated_division_by_zero, "int fixture_main(void){ int x = 1; switch (x) { case 0 && (1 / 0): break; case 1 ? 3 : 1 / 0: break; } return 0; }\nint main(void) { return 0; }", 0, "");
valid!(case_unevaluated_sizeof_operand, "int fixture_main(void){ int x = 1; switch (x) { case 0 || sizeof(x): break; } return 0; }\nint main(void) { return 0; }", 0, "");
valid!(runtime_logical_and_still_folds, "int f(void) { return 1; } int main(void) { return 0 && f() ? 1 : 42; }", 42, "");
invalid!(enumerator_float_overflow, "enum { A = (int)1e10 };", &["error: overflow in constant expression"], preprocessed = true);
invalid!(case_float_overflow, "int main(void){ int x = 1; switch (x) { case (int)1e10: ; } return 0; }", &["error: overflow in constant expression"]);
invalid!(static_initializer_float_overflow, "int i = (int)1e10;", &["error: overflow in constant expression"]);
invalid!(static_unsigned_initializer_negative_float, "unsigned u = (unsigned)-1.0;", &["error: overflow in constant expression"]);
valid!(static_initializer_float_in_range, "int a = (int)2147483647.5; unsigned b = (unsigned)4294967295.5; int c = (int)-2147483648.5;\nint main(void) { return 0; }", 0, "");
valid!(block_scope_float_conversion_is_runtime, "int main(void){ double d = 3.9; int i = (int)d; int j = (int)1e5; return i + (j == 100000) * 39; }", 42, "");
valid!(block_scope_float_overflow_initializer, "int fixture_main(void){ int i = (int)1e10; return 0; }\nint main(void) { return 0; }", 0, "");
valid!(float_constant_in_range_is_clean, "float a = 3.4028235e38f; double b = 1.7976931348623157e308; long double c = 1.18973149535723176502e4932L; double d = 4.9e-324; float e = 1.4e-45f; double z = 0.0; double y = 0e-400; double w = 2.5e-324; float v = 8e-46f;\nint main(void) { return 0; }", 0, "");
invalid!(array_typedef_const_duplicated, "typedef const int A[2]; const A x = {1, 2};", &["error: Duplicate type qualifiers"]);
invalid!(array_typedef_volatile_duplicated, "typedef volatile int A[2]; volatile A x;", &["error: Duplicate type qualifiers"]);
invalid!(array_typedef_const_duplicated_2d, "typedef const int A[2][3]; const A x = {{0}};", &["error: Duplicate type qualifiers"]);
valid!(array_typedef_other_qualifier_ok, "typedef const int A[2]; volatile A z = {0};\nint main(void) { return 0; }", 0, "");
valid!(array_typedef_unqualified_element_ok, "typedef int A[2]; const A x = {1, 2}; typedef int B[2][3]; volatile B y;\nint main(void) { return 0; }", 0, "");
invalid!(address_of_void_object, "extern void v; void *p = &v;", &["error: cannot take the address of an rvalue of type 'void'"]);
invalid!(assign_to_void_object, "extern void v; int main(void){ v = 0; return 0; }", &["error: expression is not assignable"]);
valid!(void_object_as_expression_statement, "extern void v; int fixture_main(void){ v; return 0; }\nint main(void) { return 0; }", 0, "");
valid!(const_void_object_declaration, "extern const void cv; int fixture_main(void){ return 0; }\nint main(void) { return 0; }", 0, "");
valid!(leading_zero_floating_constants_are_not_octal, "double d = 09.5; double e = 09e1;\nint main(void) { return 0; }", 0, "");
valid!(float_constant_out_of_range_warns, "double d = 1e400; float f = 1e39f; long double e = 1e5000L;\nint main(void) { return 0; }", 0, "", warnings = &["warning: floating constant exceeds range of 'double'", "warning: floating constant exceeds range of 'float'", "warning: floating constant exceeds range of 'long double'"]);
valid!(float_constant_truncated_to_zero_warns, "double z = 1e-400; float g = 1e-46f; long double h = 1e-5000L;\nint main(void) { return 0; }", 0, "", warnings = &["warning: floating constant truncated to zero", "warning: floating constant truncated to zero", "warning: floating constant truncated to zero"]);
valid!(float_constant_boundaries_warn, "float a = 3.5e38f; double b = 1.8e308; long double c = 1.2e4932L; double d = 2.4e-324; float e = 7e-46f;\nint main(void) { return 0; }", 0, "", warnings = &["warning: floating constant exceeds range of 'float'", "warning: floating constant exceeds range of 'double'", "warning: floating constant exceeds range of 'long double'", "warning: floating constant truncated to zero", "warning: floating constant truncated to zero"]);
invalid!(stray_hash_in_raw_input_is_rejected, "int main(void) { return 0 # 1\n; }", &["error: stray '#' in program", "error: syntax error, unexpected CONSTANT, expecting ',' or ';'"], preprocessed = true);
invalid!(indented_hash_after_line_marker_is_stray, "# 1 \"a.c\"\nint x = 1;\n # x = 2;\nint main(void) { return x; }", &["error: stray '#' in program", "error: syntax error, unexpected '='"], preprocessed = true);
valid!(column_one_pragma_after_line_marker_is_skipped, "# 1 \"a.c\"\n#pragma foo\nint main(void) { return 0; }", 0, "", preprocessed = true);
invalid!(indented_directive_text_after_line_marker_is_rejected, "# 1 \"a.c\"\nint x;\n #pragma foo\nint main(void) { return 0; }", &["error: stray '#' in program", "error: syntax error, unexpected IDENTIFIER", "error: syntax error, unexpected '}', expecting end of file"], preprocessed = true);
