#![cfg_attr(rustfmt, rustfmt_skip)]

valid!(label_backward_goto, "void f(void){ l: ; goto l; }\nint main(void) { return 0; }", 0, "");
valid!(label_forward_goto, "void f(void){ goto l; l: ; }\nint main(void) { return 0; }", 0, "");
valid!(label_goto_out_of_a_block, "void f(void){ { l: ; } goto l; }\nint main(void) { return 0; }", 0, "");
valid!(label_goto_into_a_block, "void f(void){ goto l; { l: ; } }\nint main(void) { return 0; }", 0, "");
valid!(label_inside_a_loop, "void f(void){ while (1) { l: goto l; } }\nint main(void) { return 0; }", 0, "");
valid!(label_out_of_a_switch, "void f(void){ switch (1) { case 1: goto l; } l: ; }\nint main(void) { return 0; }", 0, "");
valid!(label_several_in_one_function, "void f(void){ l: ; m: ; goto m; goto l; }\nint main(void) { return 0; }", 0, "");
valid!(label_shares_a_name_with_an_object, "void f(void){ int x; x: ; goto x; x = 1; }\nint main(void) { return 0; }", 0, "");
valid!(label_reused_in_another_function, "void f(void){ l: ; } void g(void){ l: ; }\nint main(void) { return 0; }", 0, "");
valid!(stmt_goto_and_label, "void f(void){ goto l; l: ; }\nint main(void) { return 0; }", 0, "");
valid!(stmt_case_beyond_the_unpromoted_range, "void f(char c){ switch (c) { case 1: ; case 257: ; } }\nint main(void) { return 0; }", 0, "");
valid!(stmt_case_inside_a_loop_inside_its_switch, "void f(void){ switch (1) { while (1) { case 1: ; } } }\nint main(void) { return 0; }", 0, "");
valid!(stmt_continue_inside_a_switch_inside_its_loop, "void f(void){ while (1) { switch (1) { case 1: continue; } } }\nint main(void) { return 0; }", 0, "");
valid!(stmt_default_inside_a_loop_inside_its_switch, "void f(void){ switch (1) { while (1) { default: ; } } }\nint main(void) { return 0; }", 0, "");
valid!(stmt_nested_switches_keep_their_own_cases, "void f(void){ switch (1) { switch (2) { case 1: ; } case 2: ; } }\nint main(void) { return 0; }", 0, "");
valid!(stmt_return_without_a_value_from_void, "void f(void){ return; }\nint main(void) { return 0; }", 0, "");
valid!(labels_are_empty_without_any, "void f(void){ ; }\nint main(void) { return 0; }", 0, "");
valid!(labels_are_collected_in_order, "void f(void){ a: ; b: ; }\nint main(void) { return 0; }", 0, "");
valid!(labels_are_collected_from_nested_statements, "void f(void){ while (1) { a: ; if (1) { b: ; } } }\nint main(void) { return 0; }", 0, "");
valid!(labels_belong_to_their_own_function, "void f(void){ a: ; } void g(void){ b: ; }\nint main(void) { return 0; }", 0, "");
valid!(labels_record_a_forward_target, "void f(void){ goto l; l: ; }\nint main(void) { return 0; }", 0, "");
valid!(stmt_return_without_a_value, "int f(void){ return; }\nint main(void) { return 0; }", 0, "", warnings = &["warning: 'return' with no value, in function returning non-void"]);
invalid!(label_goto_undefined, "void f(void){ goto nowhere; }", &["error: use of undeclared label 'nowhere'"]);
invalid!(label_defined_twice, "void f(void){ l: ; l: ; }", &["error: redefinition of label 'l'"]);
invalid!(label_goto_from_another_function, "void f(void){ l: ; } void g(void){ goto l; }", &["error: use of undeclared label 'l'"]);
invalid!(label_goto_never_defined_anywhere, "void f(void){ goto l; }", &["error: use of undeclared label 'l'"]);
invalid!(control_if_undeclared, "void f(void){ if (undeclared_cond) ; }", &["error: Use of undeclared identifier 'undeclared_cond'"]);
invalid!(control_if_else_undeclared, "void f(void){ if (1) ; else undeclared_else; }", &["error: Use of undeclared identifier 'undeclared_else'"]);
invalid!(control_switch_undeclared, "void f(void){ switch (undeclared_ctl) { case 1: ; } }", &["error: Use of undeclared identifier 'undeclared_ctl'"]);
invalid!(control_while_undeclared, "void f(void){ while (undeclared_while) ; }", &["error: Use of undeclared identifier 'undeclared_while'"]);
invalid!(control_do_undeclared, "void f(void){ do ; while (undeclared_do); }", &["error: Use of undeclared identifier 'undeclared_do'"]);
invalid!(control_for_init_undeclared, "void f(void){ for (undeclared_init; 1; 1) ; }", &["error: Use of undeclared identifier 'undeclared_init'"]);
invalid!(control_for_condition_undeclared, "void f(void){ for (1; undeclared_cond; 1) ; }", &["error: Use of undeclared identifier 'undeclared_cond'"]);
invalid!(control_for_step_undeclared, "void f(void){ for (1; 1; undeclared_step) ; }", &["error: Use of undeclared identifier 'undeclared_step'"]);
invalid!(control_if_requires_a_scalar, "struct S { int x; }; void f(struct S s){ if (s) ; }", &["error: statement requires expression of scalar type ('struct S' invalid)"]);
invalid!(control_switch_requires_an_integer, "void f(double d){ switch (d) { case 1: ; } }", &["error: statement requires expression of integer type ('double' invalid)"]);
invalid!(stmt_duplicate_case_after_conversion, "void f(void){ switch (1) { case 1: ; case 1L: ; } }", &["error: duplicate case value '1'"]);
invalid!(stmt_case_outside_any_switch, "void f(void){ while (1) { case 1: ; } }", &["error: 'case' statement not in switch statement"]);
invalid!(stmt_continue_outside_any_loop, "void f(void){ switch (1) { case 1: continue; } }", &["error: 'continue' statement not in loop statement"]);
invalid!(stmt_case_with_a_floating_value, "void f(void){ switch (1) { case 1.0: ; } }", &["error: Non integer constant expression"]);
invalid!(stmt_case_with_a_non_constant, "void f(void){ int x; switch (1) { case x: ; } }", &["error: Non constant expression"]);
invalid!(stmt_return_with_a_value_from_void, "void f(void){ return 1; }", &["error: returning 'int' from a function with incompatible result type 'void'"]);
valid!(stmt_loop_holds_its_jumps, "void f(void){ while (1) { break; continue; } }\nint main(void) { return 0; }", 0, "");
valid!(stmt_switch_holds_its_cases, "void f(void){ switch (2) { case 1: break; default: ; } }\nint main(void) { return 0; }", 0, "");
valid!(stmt_switch_inside_a_loop, "void f(void){ while (1) { switch (2) { case 1: break; continue; } } }\nint main(void) { return 0; }", 0, "");
valid!(stmt_loop_inside_a_switch, "void f(void){ switch (2) { while (1) { case 1: break; } } }\nint main(void) { return 0; }", 0, "");
valid!(stmt_case_values_take_the_promoted_control_type, "void f(char c){ switch (c) { case 1: ; case 'a': ; } }\nint main(void) { return 0; }", 0, "");
