#![cfg_attr(rustfmt, rustfmt_skip)]

valid!(typedef_then_use, "typedef int T; T x;\nint main(void) { return 0; }", 0, "");
valid!(typedef_use_in_block, "typedef int T; void f(void) { T x; x = 1; }\nint main(void) { return 0; }", 0, "");
valid!(typedef_chain, "typedef int A; typedef A B; B x;\nint main(void) { return 0; }", 0, "");
valid!(typedef_of_struct_tag, "struct S { int x; }; typedef struct S S; S v;\nint main(void) { return 0; }", 0, "");
valid!(forward_struct_typedef, "typedef struct S *SP; struct S { SP p; };\nint main(void) { return 0; }", 0, "");
valid!(cast_to_typedef, "typedef int T; void f(void) { int x; x = (T)1; }\nint main(void) { return 0; }", 0, "");
valid!(typedef_redef_in_block, "typedef int T; void f(void) { typedef T T; T x; x = 1; }\nint main(void) { return 0; }", 0, "");
valid!(knr_definition_with_typedef_param_type, "typedef int T; f(a) T a; { return a; }\nint main(void) { return 0; }", 0, "");
valid!(block_typedef_no_leak, "void f(void) { typedef int T; } int T;\nint main(void) { return 0; }", 0, "");
valid!(sizeof_shadowed_verdict, "typedef int T; int fixture_main(void) { int T; return sizeof(T); }\nint main(void) { return 0; }", 0, "");
valid!(local_var_shadows_typedef, "typedef int T; int fixture_main(void) { int T; T = 1; return T; }\nint main(void) { return 0; }", 0, "");
valid!(param_shadows_typedef, "typedef int T; T f(T T) { return T; }\nint main(void) { return 0; }", 0, "");
valid!(paren_expr_of_shadowed_typedef, "typedef int T; int fixture_main(void) { int T; return (T); }\nint main(void) { return 0; }", 0, "");
valid!(sizeof_expr_on_shadowed_typedef, "typedef int T; int fixture_main(void) { int T; return sizeof T; }\nint main(void) { return 0; }", 0, "");
valid!(label_named_as_typedef, "typedef int T; void f(void) { T: ; goto T; }\nint main(void) { return 0; }", 0, "");
valid!(struct_tag_named_as_typedef, "typedef int S; struct S { int x; };\nint main(void) { return 0; }", 0, "");
valid!(union_tag_named_as_typedef, "typedef int S; union S { int x; };\nint main(void) { return 0; }", 0, "");
valid!(member_named_as_typedef, "typedef int T; struct S { T T; };\nint main(void) { return 0; }", 0, "");
valid!(member_access_named_as_typedef, "typedef int x; struct S { int x; }; void f(void) { struct S s; s.x = 1; }\nint main(void) { return 0; }", 0, "");
valid!(knr_struct_def_in_declaration_list, "f(a) struct S { int x; } *a; { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(member_shadows_outer_typedef, "typedef int T; struct S { int T; }; T x;\nint main(void) { return 0; }", 0, "");
valid!(enum_tag_named_as_typedef, "typedef int E; enum E { A };\nint main(void) { return 0; }", 0, "");
valid!(struct_body_then_typedef_decl, "typedef struct { int x; } S; S s;\nint main(void) { return 0; }", 0, "");
valid!(multiword_type_then_typedef, "typedef unsigned long UL; UL u;\nint main(void) { return 0; }", 0, "");
valid!(typedef_after_nontypedef_decl, "typedef int T; int y; void f(void) { y = 1; }\nint main(void) { return 0; }", 0, "");
valid!(escaped_newline_in_string_literal, "char *s = \"ab\\ncd\";\nint main(void) { return 0; }", 0, "");
valid!(escaped_newline_in_char_constant, "int c = '\\n';\nint main(void) { return 0; }", 0, "");
valid!(literal_single, "int main(void) { return !(((unsigned char)(\"x\")[0] == 120) && ((unsigned char)(\"x\")[1] == 0)); }", 0, "");
valid!(literal_concat_two, "int main(void) { return !(((unsigned char)(\"x\" \"y\")[0] == 120) && ((unsigned char)(\"x\" \"y\")[1] == 121) && ((unsigned char)(\"x\" \"y\")[2] == 0)); }", 0, "");
valid!(literal_concat_three, "int main(void) { return !(((unsigned char)(\"x\" \"y\" \"z\")[0] == 120) && ((unsigned char)(\"x\" \"y\" \"z\")[1] == 121) && ((unsigned char)(\"x\" \"y\" \"z\")[2] == 122) && ((unsigned char)(\"x\" \"y\" \"z\")[3] == 0)); }", 0, "");
valid!(literal_concat_across_comment, "int main(void) { return !(((unsigned char)(\"x\" \"y\")[0] == 120) && ((unsigned char)(\"x\" \"y\")[1] == 121) && ((unsigned char)(\"x\" \"y\")[2] == 0)); }", 0, "");
valid!(literal_concat_across_newline, "int main(void) { return !(((unsigned char)(\"x\" \"y\" \"z\")[0] == 120) && ((unsigned char)(\"x\" \"y\" \"z\")[1] == 121) && ((unsigned char)(\"x\" \"y\" \"z\")[2] == 122) && ((unsigned char)(\"x\" \"y\" \"z\")[3] == 0)); }", 0, "");
valid!(literal_concat_empty_pieces, "int main(void) { return !(((unsigned char)(\"\" \"x\" \"\")[0] == 120) && ((unsigned char)(\"\" \"x\" \"\")[1] == 0)); }", 0, "");
valid!(literal_concat_all_empty, "int main(void) { return !(((unsigned char)(\"\" \"\")[0] == 0)); }", 0, "");
valid!(literal_wide_prefix, "int main(void) { return !(((L\"x\")[0] == 120) && ((L\"x\")[1] == 0)); }", 0, "");
valid!(literal_wide_empty, "int main(void) { return !(((L\"\")[0] == 0)); }", 0, "");
valid!(literal_concat_wide, "int main(void) { return !(((L\"a\" L\"b\")[0] == 97) && ((L\"a\" L\"b\")[1] == 98) && ((L\"a\" L\"b\")[2] == 0)); }", 0, "");
valid!(literal_concat_narrow_then_wide, "int main(void) { return !(((\"a\" L\"b\")[0] == 97) && ((\"a\" L\"b\")[1] == 98) && ((\"a\" L\"b\")[2] == 0)); }", 0, "", warnings = &["warning: concatenation of a wide and a narrow string literal is undefined", "warning: concatenation of a wide and a narrow string literal is undefined", "warning: concatenation of a wide and a narrow string literal is undefined"]);
valid!(literal_concat_wide_then_narrow, "int main(void) { return !(((L\"a\" \"b\")[0] == 97) && ((L\"a\" \"b\")[1] == 98) && ((L\"a\" \"b\")[2] == 0)); }", 0, "", warnings = &["warning: concatenation of a wide and a narrow string literal is undefined", "warning: concatenation of a wide and a narrow string literal is undefined", "warning: concatenation of a wide and a narrow string literal is undefined"]);
valid!(literal_splice_in_string, "int main(void) { return !(((unsigned char)(\"a\\\nb\")[0] == 97) && ((unsigned char)(\"a\\\nb\")[1] == 98) && ((unsigned char)(\"a\\\nb\")[2] == 0)); }", 0, "");
valid!(literal_splice_concat_pieces, "int main(void) { return !(((unsigned char)(\"a\" \"b\")[0] == 97) && ((unsigned char)(\"a\" \"b\")[1] == 98) && ((unsigned char)(\"a\" \"b\")[2] == 0)); }", 0, "");
invalid!(nested_block_typedef_no_leak, "typedef int T; void f(void) { if (1) { typedef char U; } } U u;", &["error: syntax error, unexpected IDENTIFIER"]);
invalid!(enumerator_conflicts_with_typedef, "typedef int T; enum E { T };", &["error: duplicate declaration of enumerator `T'"]);
invalid!(knr_param_named_as_typedef, "typedef int a; f(a) int a; { return a; }", &["error: prototype-style function declaration shall not be followed by a declaration list", "error: unexpected type name 'a': expected expression"]);
invalid!(typedef_redeclared_as_var, "typedef int T; int T;", &["error: duplicate declaration of variable `T'"]);
invalid!(pointer_declarator_typedef, "typedef int T; int *T;", &["error: duplicate declaration of variable `T'"]);
valid!(primary_identifier, "int x; int f(void) { return x; }\nint main(void) { return 0; }", 0, "");
valid!(primary_parenthesized, "int f(void) { return (((1))); }\nint main(void) { return 0; }", 0, "");
valid!(constant_decimal, "int f(void) { return 42; }\nint main(void) { return 0; }", 0, "");
valid!(constant_octal, "int f(void) { return 0777; }\nint main(void) { return 0; }", 0, "");
valid!(constant_hex, "int f(void) { return 0xFFu; }\nint main(void) { return 0; }", 0, "");
valid!(constant_suffixes, "unsigned long f(void) { return 1ul + 2UL + 3L + 4U; }\nint main(void) { return 0; }", 0, "");
valid!(constant_char, "int f(void) { return 'a'; }\nint main(void) { return 0; }", 0, "");
valid!(constant_char_escape, "int f(void) { return '\\n' + '\\0' + '\\\\' + '\\''; }\nint main(void) { return 0; }", 0, "");
valid!(constant_wide_char, "int f(void) { return L'a'; }\nint main(void) { return 0; }", 0, "");
valid!(constant_float, "double f(void) { return 1.0 + .5 + 2. + 1e10 + 1.5e-3 + 1.0f + 1.0L; }\nint main(void) { return 0; }", 0, "");
valid!(string_literal_expr, "char *f(void) { return \"hello\"; }\nint main(void) { return 0; }", 0, "");
valid!(string_literal_escapes, "char *f(void) { return \"a\\tb\\\"c\\\\d\"; }\nint main(void) { return 0; }", 0, "");
valid!(string_literal_wide, "int f(void) { return L\"wide\"[0]; }\nint main(void) { return 0; }", 0, "");
valid!(postfix_subscript, "int a[4]; int f(void) { return a[2]; }\nint main(void) { return 0; }", 0, "");
valid!(postfix_subscript_nested, "int a[4][5]; int f(void) { return a[1][2]; }\nint main(void) { return 0; }", 0, "");
valid!(postfix_call_no_args, "int g(void); int f(void) { return g(); }\nint main(void) { return 0; }\nint g(void) { return 0; }", 0, "");
valid!(postfix_call_one_arg, "int g(int); int f(void) { return g(1); }\nint main(void) { return 0; }\nint g(int p0) { return 0; }", 0, "");
valid!(postfix_call_many_args, "int g(int, int, int); int f(void) { return g(1, 2, 3); }\nint main(void) { return 0; }\nint g(int p0, int p1, int p2) { return 0; }", 0, "");
valid!(postfix_call_comma_arg, "int g(int); int f(void) { return g((1, 2)); }\nint main(void) { return 0; }\nint g(int p0) { return 0; }", 0, "");
valid!(postfix_call_through_pointer, "int (*fp)(int); int f(void) { return (*fp)(1) + fp(2); }\nint main(void) { return 0; }", 0, "");
valid!(postfix_member_dot, "struct S { int m; } s; int f(void) { return s.m; }\nint main(void) { return 0; }", 0, "");
valid!(postfix_member_arrow, "struct S { int m; } *p; int f(void) { return p->m; }\nint main(void) { return 0; }", 0, "");
valid!(postfix_member_chain, "struct A { int m; }; struct B { struct A a; } b; int f(void) { return b.a.m; }\nint main(void) { return 0; }", 0, "");
valid!(postfix_inc_dec, "int f(void) { int x; x = 0; x++; x--; return x; }\nint main(void) { return 0; }", 0, "");
valid!(unary_prefix_inc_dec, "int f(void) { int x; x = 0; ++x; --x; return x; }\nint main(void) { return 0; }", 0, "");
valid!(unary_address_and_deref, "int f(void) { int x; int *p; x = 0; p = &x; return *p; }\nint main(void) { return 0; }", 0, "");
valid!(unary_arithmetic, "int f(void) { int x; x = 1; return +x + -x + ~x + !x; }\nint main(void) { return 0; }", 0, "");
valid!(unary_sizeof_expr, "int f(void) { int x; x = 0; return sizeof x; }\nint main(void) { return 0; }", 0, "");
valid!(unary_sizeof_paren_expr, "int f(void) { int x; x = 0; return sizeof (x); }\nint main(void) { return 0; }", 0, "");
valid!(unary_sizeof_type, "int f(void) { return sizeof(int); }\nint main(void) { return 0; }", 0, "");
valid!(unary_sizeof_ptr_type, "int f(void) { return sizeof(char *) + sizeof(int (*)(void)); }\nint main(void) { return 0; }", 0, "");
valid!(unary_sizeof_array_type, "int f(void) { return sizeof(int[10]); }\nint main(void) { return 0; }", 0, "");
valid!(cast_scalar, "int f(void) { return (int)1.5; }\nint main(void) { return 0; }", 0, "");
valid!(cast_pointer, "int f(void) { int x; x = 0; return *(int *)&x; }\nint main(void) { return 0; }", 0, "");
valid!(cast_void, "void g(void); void f(void) { (void)0; }\nint main(void) { return 0; }", 0, "");
valid!(cast_nested, "int f(void) { return (int)(char)(long)1; }\nint main(void) { return 0; }", 0, "");
valid!(cast_to_function_pointer, "void f(void) { int (*p)(int); p = 0; (void)(int (*)(int))p; }\nint main(void) { return 0; }", 0, "");
valid!(binary_multiplicative, "int f(int a, int b) { return a * b / a % b; }\nint main(void) { return 0; }", 0, "");
valid!(binary_additive, "int f(int a, int b) { return a + b - a; }\nint main(void) { return 0; }", 0, "");
valid!(binary_shift, "int f(int a, int b) { return a << b >> a; }\nint main(void) { return 0; }", 0, "");
valid!(binary_relational, "int f(int a, int b) { return (a < b) + (a > b) + (a <= b) + (a >= b); }\nint main(void) { return 0; }", 0, "");
valid!(binary_equality, "int f(int a, int b) { return (a == b) + (a != b); }\nint main(void) { return 0; }", 0, "");
valid!(binary_bitwise, "int f(int a, int b) { return (a & b) | (a ^ b); }\nint main(void) { return 0; }", 0, "");
valid!(binary_logical, "int f(int a, int b) { return (a && b) || (a || b); }\nint main(void) { return 0; }", 0, "");
valid!(binary_precedence_mix, "int f(int a, int b, int c) { return a + b * c - a / b % c; }\nint main(void) { return 0; }", 0, "");
valid!(conditional_expr, "int f(int a) { return a ? 1 : 2; }\nint main(void) { return 0; }", 0, "");
valid!(conditional_nested, "int f(int a) { return a ? a ? 1 : 2 : 3; }\nint main(void) { return 0; }", 0, "");
valid!(assignment_simple, "int f(void) { int x; x = 1; return x; }\nint main(void) { return 0; }", 0, "");
valid!(assignment_compound, "int f(void) { int x; x = 1; x += 1; x -= 1; x *= 2; x /= 2; x %= 2; x <<= 1; x >>= 1; x &= 1; x ^= 1; x |= 1; return x; }\nint main(void) { return 0; }", 0, "");
valid!(assignment_chained, "int f(void) { int a, b; a = b = 1; return a; }\nint main(void) { return 0; }", 0, "");
valid!(comma_expr, "int f(void) { int x; x = (1, 2, 3); return x; }\nint main(void) { return 0; }", 0, "");
valid!(storage_extern, "extern int x;\nint main(void) { return 0; }", 0, "");
valid!(storage_static_file, "static int x; static int f(void) { return x; }\nint main(void) { return 0; }", 0, "");
valid!(storage_auto_register, "int f(void) { auto int x; register int y; x = 0; y = 0; return x + y; }\nint main(void) { return 0; }", 0, "");
valid!(storage_typedef, "typedef int T;\nint main(void) { return 0; }", 0, "");
valid!(storage_before_and_after_type, "static int a; int static b;\nint main(void) { return 0; }", 0, "");
valid!(type_void_function, "void f(void) { return; }\nint main(void) { return 0; }", 0, "");
valid!(type_plain_char, "char c;\nint main(void) { return 0; }", 0, "");
valid!(type_signed_unsigned_char, "signed char a; unsigned char b;\nint main(void) { return 0; }", 0, "");
valid!(type_short_forms, "short a; short int b; signed short c; signed short int d; unsigned short e; unsigned short int f;\nint main(void) { return 0; }", 0, "");
valid!(type_int_forms, "int a; signed b; signed int c; unsigned d; unsigned int e;\nint main(void) { return 0; }", 0, "");
valid!(type_long_forms, "long a; long int b; signed long c; signed long int d; unsigned long e; unsigned long int f;\nint main(void) { return 0; }", 0, "");
valid!(type_float_double, "float a; double b; long double c;\nint main(void) { return 0; }", 0, "");
valid!(type_specifier_order_swapped, "int unsigned a; int long b; char signed c;\nint main(void) { return 0; }", 0, "");
valid!(struct_with_tag_and_body, "struct S { int a; char b; };\nint main(void) { return 0; }", 0, "");
valid!(struct_anonymous_body, "struct { int a; } s;\nint main(void) { return 0; }", 0, "");
valid!(struct_tag_only_reference, "struct S { int a; }; struct S s;\nint main(void) { return 0; }", 0, "");
valid!(struct_forward_reference, "struct S; struct S *p;\nint main(void) { return 0; }", 0, "");
valid!(struct_self_referential, "struct Node { int v; struct Node *next; };\nint main(void) { return 0; }", 0, "");
valid!(struct_mutually_recursive, "struct A { struct B *b; }; struct B { struct A *a; };\nint main(void) { return 0; }", 0, "");
valid!(struct_nested_definition, "struct Outer { struct Inner { int x; } in; };\nint main(void) { return 0; }", 0, "");
valid!(struct_multiple_declarators, "struct S { int a, b, *c, d[4]; };\nint main(void) { return 0; }", 0, "");
valid!(struct_bitfields, "struct S { unsigned a : 1; signed b : 3; int c : 2; };\nint main(void) { return 0; }", 0, "");
valid!(struct_anonymous_bitfield, "struct S { unsigned a : 1; unsigned : 2; int b; };\nint main(void) { return 0; }", 0, "");
valid!(struct_zero_width_bitfield, "struct S { unsigned a : 1; unsigned : 0; unsigned b : 1; };\nint main(void) { return 0; }", 0, "");
valid!(struct_qualified_members, "struct S { const int a; volatile int b; const volatile int c; };\nint main(void) { return 0; }", 0, "");
valid!(union_with_tag_and_body, "union U { int i; float f; char c[4]; };\nint main(void) { return 0; }", 0, "");
valid!(union_anonymous_body, "union { int i; float f; } u;\nint main(void) { return 0; }", 0, "");
valid!(union_nested_in_struct, "struct S { union { int i; float f; } u; };\nint main(void) { return 0; }", 0, "");
valid!(enum_with_tag, "enum E { A, B, C };\nint main(void) { return 0; }", 0, "");
valid!(enum_anonymous, "enum { A, B }; \nint main(void) { return 0; }", 0, "");
valid!(enum_explicit_values, "enum E { A = 1, B = 2, C = A + B };\nint main(void) { return 0; }", 0, "");
valid!(enum_mixed_values, "enum E { A, B = 5, C };\nint main(void) { return 0; }", 0, "");
valid!(enum_single_enumerator, "enum E { A };\nint main(void) { return 0; }", 0, "");
valid!(enum_tag_reference, "enum E { A }; enum E e;\nint main(void) { return 0; }", 0, "");
valid!(enum_variable_declaration, "enum E { A } e;\nint main(void) { return 0; }", 0, "");
valid!(qualifier_const, "const int a = 1;\nint main(void) { return 0; }", 0, "");
valid!(qualifier_volatile, "volatile int a;\nint main(void) { return 0; }", 0, "");
valid!(qualifier_both_orders, "const volatile int a; volatile const int b;\nint main(void) { return 0; }", 0, "");
valid!(qualifier_after_type, "int const a; int volatile b;\nint main(void) { return 0; }", 0, "");
valid!(qualifier_on_pointer, "int *const p = 0; const int *q; const int *const r = 0;\nint main(void) { return 0; }", 0, "");
valid!(qualifier_with_storage, "static const int a = 1; extern volatile int b;\nint main(void) { return 0; }", 0, "");
valid!(declarator_pointer_levels, "int *a; int **b; int ***c;\nint main(void) { return 0; }", 0, "");
valid!(declarator_qualified_pointers, "int *const *volatile p;\nint main(void) { return 0; }", 0, "");
valid!(declarator_parenthesized, "int (a); int (*(b));\nint main(void) { return 0; }", 0, "");
valid!(declarator_array_sized, "int a[10];\nint main(void) { return 0; }", 0, "");
valid!(declarator_array_unsized_extern, "extern int a[];\nint main(void) { return 0; }", 0, "");
valid!(declarator_array_multidim, "int a[2][3][4];\nint main(void) { return 0; }", 0, "");
valid!(declarator_array_of_pointers, "int *a[10];\nint main(void) { return 0; }", 0, "");
valid!(declarator_pointer_to_array, "int (*a)[10];\nint main(void) { return 0; }", 0, "");
valid!(declarator_array_const_expr_size, "int a[2 + 3 * 4];\nint main(void) { return 0; }", 0, "");
valid!(declarator_function_prototype, "int f(int a, char b);\nint main(void) { return 0; }", 0, "");
valid!(declarator_function_unnamed_params, "int f(int, char);\nint main(void) { return 0; }", 0, "");
valid!(declarator_function_void_params, "int f(void);\nint main(void) { return 0; }", 0, "");
valid!(declarator_function_empty_params, "int f();\nint main(void) { return 0; }", 0, "");
valid!(declarator_function_variadic, "int f(int a, ...);\nint main(void) { return 0; }", 0, "");
valid!(declarator_function_pointer, "int (*fp)(int);\nint main(void) { return 0; }", 0, "");
valid!(declarator_array_of_function_pointers, "int (*fp[4])(int);\nint main(void) { return 0; }", 0, "");
valid!(declarator_function_returning_pointer, "int *f(void);\nint main(void) { return 0; }", 0, "");
valid!(declarator_function_returning_function_pointer, "int (*f(int))(int);\nint main(void) { return 0; }", 0, "");
valid!(declarator_nested_pointer_array_mix, "int *(*(*a)[4])(int);\nint main(void) { return 0; }", 0, "");
valid!(declarator_param_array_adjusts, "int f(int a[], int b[10], int c[][4]);\nint main(void) { return 0; }", 0, "");
valid!(declarator_param_function_pointer, "int f(int (*cb)(int));\nint main(void) { return 0; }", 0, "");
valid!(declarator_param_qualified, "int f(const int *p, int *const q);\nint main(void) { return 0; }", 0, "");
valid!(init_scalar, "int a = 1;\nint main(void) { return 0; }", 0, "");
valid!(init_scalar_expr, "int a = 1 + 2 * 3;\nint main(void) { return 0; }", 0, "");
valid!(init_multiple_declarators, "int a = 1, b = 2, c;\nint main(void) { return 0; }", 0, "");
valid!(init_array_braced, "int a[3] = { 1, 2, 3 };\nint main(void) { return 0; }", 0, "");
valid!(init_array_trailing_comma, "int a[3] = { 1, 2, 3, };\nint main(void) { return 0; }", 0, "");
valid!(init_array_partial, "int a[5] = { 1, 2 };\nint main(void) { return 0; }", 0, "");
valid!(init_array_inferred_size, "int a[] = { 1, 2, 3 };\nint main(void) { return 0; }", 0, "");
valid!(init_array_nested_braces, "int a[2][2] = { { 1, 2 }, { 3, 4 } };\nint main(void) { return 0; }", 0, "");
valid!(init_array_flat_for_nested, "int a[2][2] = { 1, 2, 3, 4 };\nint main(void) { return 0; }", 0, "");
valid!(init_struct, "struct S { int a; char b; } s = { 1, 'c' };\nint main(void) { return 0; }", 0, "");
valid!(init_struct_nested, "struct I { int x; }; struct O { struct I i; int y; } o = { { 1 }, 2 };\nint main(void) { return 0; }", 0, "");
valid!(init_char_array_from_string, "char s[6] = \"hello\";\nint main(void) { return 0; }", 0, "");
valid!(init_char_array_inferred, "char s[] = \"hello\";\nint main(void) { return 0; }", 0, "");
valid!(init_pointer_from_string, "char *s = \"hello\";\nint main(void) { return 0; }", 0, "");
valid!(init_static_local, "int f(void) { static int a = 1; return a; }\nint main(void) { return 0; }", 0, "");
valid!(abstract_plain, "int f(void) { return sizeof(int); }\nint main(void) { return 0; }", 0, "");
valid!(abstract_pointer, "int f(void) { return sizeof(int *); }\nint main(void) { return 0; }", 0, "");
valid!(abstract_pointer_multi, "int f(void) { return sizeof(char **); }\nint main(void) { return 0; }", 0, "");
valid!(abstract_array, "int f(void) { return sizeof(int[3]); }\nint main(void) { return 0; }", 0, "");
valid!(abstract_array_unsized, "void g(int []);\nint main(void) { return 0; }", 0, "");
valid!(abstract_function_pointer, "int f(void) { return sizeof(int (*)(void)); }\nint main(void) { return 0; }", 0, "");
valid!(abstract_pointer_to_array, "int f(void) { return sizeof(int (*)[4]); }\nint main(void) { return 0; }", 0, "");
valid!(abstract_qualified, "int f(void) { return sizeof(const int *); }\nint main(void) { return 0; }", 0, "");
valid!(abstract_struct, "struct S { int a; }; int f(void) { return sizeof(struct S); }\nint main(void) { return 0; }", 0, "");
valid!(label_and_goto, "void f(void) { goto end; end: ; }\nint main(void) { return 0; }", 0, "");
valid!(label_before_declaration_block, "void f(void) { a: { int x; x = 0; } goto a; }\nint main(void) { return 0; }", 0, "");
valid!(label_multiple, "void f(void) { a: b: c: ; goto b; }\nint main(void) { return 0; }", 0, "");
valid!(switch_case_default, "void f(int x) { switch (x) { case 1: break; case 2: break; default: break; } }\nint main(void) { return 0; }", 0, "");
valid!(switch_case_const_expr, "void f(int x) { switch (x) { case 1 + 2: break; } }\nint main(void) { return 0; }", 0, "");
valid!(switch_fallthrough_and_empty, "void f(int x) { switch (x) { case 1: case 2: ; } }\nint main(void) { return 0; }", 0, "");
valid!(switch_enum_case, "enum E { A, B }; void f(enum E e) { switch (e) { case A: break; default: break; } }\nint main(void) { return 0; }", 0, "");
valid!(compound_empty, "void f(void) { }\nint main(void) { return 0; }", 0, "");
valid!(compound_declarations_only, "void f(void) { int a; char b; }\nint main(void) { return 0; }", 0, "");
valid!(compound_statements_only, "void f(void) { ; ; }\nint main(void) { return 0; }", 0, "");
valid!(compound_declarations_then_statements, "void f(void) { int a; a = 1; }\nint main(void) { return 0; }", 0, "");
valid!(compound_nested_blocks, "void f(void) { { int a; { int b; b = 0; a = b; } } }\nint main(void) { return 0; }", 0, "");
valid!(compound_shadowing, "void f(void) { int a; { int a; a = 1; } a = 2; }\nint main(void) { return 0; }", 0, "");
valid!(statement_null, "void f(void) { ; }\nint main(void) { return 0; }", 0, "");
valid!(statement_expression, "void f(void) { int a; a = 1; a + 1; }\nint main(void) { return 0; }", 0, "");
valid!(if_without_else, "void f(int x) { if (x) ; }\nint main(void) { return 0; }", 0, "");
valid!(if_with_else, "void f(int x) { if (x) ; else ; }\nint main(void) { return 0; }", 0, "");
valid!(if_else_if_chain, "void f(int x) { if (x) ; else if (x) ; else ; }\nint main(void) { return 0; }", 0, "");
valid!(if_dangling_else, "void f(int x) { if (x) if (x) ; else ; }\nint main(void) { return 0; }", 0, "");
valid!(if_with_blocks, "void f(int x) { if (x) { ; } else { ; } }\nint main(void) { return 0; }", 0, "");
valid!(if_declaration_in_branch_block, "void f(int x) { if (x) { int y; y = 0; } }\nint main(void) { return 0; }", 0, "");
valid!(while_loop, "void f(int x) { while (x) ; }\nint main(void) { return 0; }", 0, "");
valid!(while_with_block, "void f(int x) { while (x) { x = x - 1; } }\nint main(void) { return 0; }", 0, "");
valid!(do_while_loop, "void f(int x) { do ; while (x); }\nint main(void) { return 0; }", 0, "");
valid!(do_while_with_block, "void f(int x) { do { x = x - 1; } while (x); }\nint main(void) { return 0; }", 0, "");
valid!(for_full, "void f(void) { int i; for (i = 0; i < 10; i++) ; }\nint main(void) { return 0; }", 0, "");
valid!(for_no_init, "void f(void) { int i; i = 0; for (; i < 10; i++) ; }\nint main(void) { return 0; }", 0, "");
valid!(for_no_condition, "void f(void) { int i; for (i = 0; ; i++) break; }\nint main(void) { return 0; }", 0, "");
valid!(for_no_increment, "void f(void) { int i; for (i = 0; i < 10;) i++; }\nint main(void) { return 0; }", 0, "");
valid!(for_empty_all, "void f(void) { for (;;) break; }\nint main(void) { return 0; }", 0, "");
valid!(for_comma_clauses, "void f(void) { int i, j; for (i = 0, j = 9; i < j; i++, j--) ; }\nint main(void) { return 0; }", 0, "");
valid!(for_nested, "void f(void) { int i, j; for (i = 0; i < 2; i++) for (j = 0; j < 2; j++) ; }\nint main(void) { return 0; }", 0, "");
valid!(jump_goto_forward_and_back, "void f(void) { int i; i = 0; back: i++; if (i < 2) goto back; goto fwd; fwd: ; }\nint main(void) { return 0; }", 0, "");
valid!(jump_continue_break, "void f(void) { int i; for (i = 0; i < 10; i++) { if (i) continue; else break; } }\nint main(void) { return 0; }", 0, "");
valid!(jump_break_in_switch, "void f(int x) { switch (x) { default: break; } }\nint main(void) { return 0; }", 0, "");
valid!(jump_return_void, "void f(void) { return; }\nint main(void) { return 0; }", 0, "");
valid!(jump_return_value, "int f(void) { return 1; }\nint main(void) { return 0; }", 0, "");
valid!(jump_return_expression, "int f(int a) { return a ? 1 : 2; }\nint main(void) { return 0; }", 0, "");
valid!(external_function_definition, "int f(int a) { return a; }\nint main(void) { return 0; }", 0, "");
valid!(external_function_no_params, "int f(void) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(external_multiple_definitions, "int f(void) { return 0; } int g(void) { return f(); }\nint main(void) { return 0; }", 0, "");
valid!(external_prototype_then_definition, "int f(int); int f(int a) { return a; }\nint main(void) { return 0; }", 0, "");
valid!(external_static_definition, "static int f(void) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(external_pointer_returning_definition, "int *f(int *p) { return p; }\nint main(void) { return 0; }", 0, "");
valid!(external_struct_param_definition, "struct S { int a; }; int f(struct S s) { return s.a; }\nint main(void) { return 0; }", 0, "");
valid!(knr_definition_no_params, "int f() { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(knr_definition_with_params, "int f(a, b) int a; int b; { return a + b; }\nint main(void) { return 0; }", 0, "");
valid!(knr_definition_implicit_int, "f(a) int a; { return a; }\nint main(void) { return 0; }", 0, "");
valid!(knr_definition_pointer_param, "int f(p) char *p; { return *p; }\nint main(void) { return 0; }", 0, "");
valid!(knr_definition_array_param, "int f(a) int a[]; { return a[0]; }\nint main(void) { return 0; }", 0, "");
valid!(knr_definition_multiple_in_one_decl, "int f(a, b) int a, b; { return a + b; }\nint main(void) { return 0; }", 0, "");
valid!(typedef_pointer, "typedef int *IP; IP p;\nint main(void) { return 0; }", 0, "");
valid!(typedef_array, "typedef int Arr[10]; Arr a;\nint main(void) { return 0; }", 0, "");
valid!(typedef_function, "typedef int Fn(int); Fn *fp;\nint main(void) { return 0; }", 0, "");
valid!(typedef_function_pointer, "typedef int (*Fp)(int); Fp fp;\nint main(void) { return 0; }", 0, "");
valid!(typedef_struct_anonymous, "typedef struct { int a; } S; S s;\nint main(void) { return 0; }", 0, "");
valid!(typedef_union, "typedef union { int i; float f; } U; U u;\nint main(void) { return 0; }", 0, "");
valid!(typedef_enum, "typedef enum { A, B } E; E e;\nint main(void) { return 0; }", 0, "");
valid!(typedef_qualified, "typedef const int CI; CI a = 1;\nint main(void) { return 0; }", 0, "");
valid!(typedef_multiple_in_one, "typedef int A, *B, C[4]; A a; B b; C c;\nint main(void) { return 0; }", 0, "");
valid!(typedef_as_param_type, "typedef int T; int f(T a) { return a; }\nint main(void) { return 0; }", 0, "");
valid!(typedef_as_return_type, "typedef int T; T f(void) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(typedef_in_cast_and_sizeof, "typedef int T; int f(void) { return (T)1 + sizeof(T); }\nint main(void) { return 0; }", 0, "");
valid!(typedef_in_struct_member, "typedef int T; struct S { T a; T *b; T c[2]; };\nint main(void) { return 0; }", 0, "");
valid!(typedef_abstract_declarator, "typedef int T; int f(void) { return sizeof(T *) + sizeof(T (*)(void)); }\nint main(void) { return 0; }", 0, "");
valid!(concat_in_char_array_init, "char s[] = \"ab\" \"cd\";\nint main(void) { return 0; }", 0, "");
valid!(concat_in_sized_array_init, "char s[5] = \"ab\" \"cd\";\nint main(void) { return 0; }", 0, "");
valid!(concat_in_pointer_init, "char *s = \"ab\" \"cd\";\nint main(void) { return 0; }", 0, "");
valid!(concat_in_array_of_pointers, "char *s[] = { \"a\" \"b\", \"c\" };\nint main(void) { return 0; }", 0, "");
valid!(concat_as_call_argument, "int g(char *); int f(void) { return g(\"a\" \"b\"); }\nint main(void) { return 0; }\nint g(char * p0) { return 0; }", 0, "");
valid!(concat_in_sizeof, "int f(void) { return sizeof(\"a\" \"b\"); }\nint main(void) { return 0; }", 0, "");
valid!(concat_in_return, "char *f(void) { return \"a\" \"b\"; }\nint main(void) { return 0; }", 0, "");
valid!(concat_subscripted, "int f(void) { return (\"ab\" \"cd\")[1]; }\nint main(void) { return 0; }", 0, "");
valid!(concat_in_conditional, "char *f(int c) { return c ? \"a\" \"b\" : \"c\" \"d\"; }\nint main(void) { return 0; }", 0, "");
valid!(concat_in_struct_init, "struct S { char *a; char *b; } s = { \"x\" \"y\", \"z\" };\nint main(void) { return 0; }", 0, "");
valid!(concat_with_escapes, "char *s = \"a\\tb\" \"c\\nd\";\nint main(void) { return 0; }", 0, "");
valid!(concat_with_escaped_quote, "char *s = \"a\\\"\" \"b\";\nint main(void) { return 0; }", 0, "");
valid!(concat_wide_in_init, "int f(void) { return L\"ab\" \"cd\"[0]; }\nint main(void) { return 0; }", 0, "", warnings = &["warning: concatenation of a wide and a narrow string literal is undefined"]);
valid!(splice_in_string, "char *s = \"a\\\nb\";\nint main(void) { return 0; }", 0, "");
valid!(splice_in_identifier, "int ab; int f(void) { return a\\\nb; }\nint main(void) { return 0; }", 0, "");
valid!(splice_in_keyword, "in\\\nt x;\nint main(void) { return 0; }", 0, "");
valid!(splice_in_operator, "int f(int a) { if (a =\\\n= 1) return 1; return 0; }\nint main(void) { return 0; }", 0, "");
valid!(splice_in_constant, "int f(void) { return 1\\\n2; }\nint main(void) { return 0; }", 0, "");
valid!(splice_consecutive, "int a\\\n\\\nb;\nint main(void) { return 0; }", 0, "");
valid!(splice_at_line_start, "int x;\n\\\nint y;\nint main(void) { return 0; }", 0, "");
valid!(splice_in_declarator, "int *\\\np;\nint main(void) { return 0; }", 0, "");
valid!(splice_escaped_backslash_before, "char *s = \"a\\\\\\\nb\";\nint main(void) { return 0; }", 0, "");
valid!(knr_implicit_int_no_params, "f() { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(decl_storage_only, "extern x;\nint main(void) { return 0; }", 0, "");
valid!(decl_qualifier_then_storage, "const static x;\nint main(void) { return 0; }", 0, "");
valid!(ptr_two_qualifiers, "int *const volatile p;\nint main(void) { return 0; }", 0, "");
valid!(sqlist_qualifier_only, "struct S { const a; };\nint main(void) { return 0; }", 0, "");
valid!(sqlist_two_type_specs, "struct S { unsigned int a; };\nint main(void) { return 0; }", 0, "");
valid!(sqlist_type_then_qualifier, "struct S { int const a; };\nint main(void) { return 0; }", 0, "");
valid!(abstract_ptr_then_array, "int f(void) { return sizeof(int *[4]); }\nint main(void) { return 0; }", 0, "");
valid!(abstract_array_unsized_suffix, "void g(int (*)[]);\nint main(void) { return 0; }", 0, "");
valid!(abstract_empty_parens, "void g(int ());\nint main(void) { return 0; }", 0, "");
valid!(abstract_paren_param_list, "void g(int (int));\nint main(void) { return 0; }", 0, "");
