#![cfg_attr(rustfmt, rustfmt_skip)]

valid!(linkage_accept_static_then_extern_inherits, "static int b; extern int b;\nint main(void) { return 0; }", 0, "");
valid!(linkage_accept_implicit_extern_function_inherits, "static int sf(void); int sf(void) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(linkage_accept_repeated_block_extern, "void f(void) { extern int x; extern int x; } int x;\nint main(void) { return 0; }", 0, "");
valid!(linkage_accept_no_linkage_local_never_meets_external, "void f(void) { int y; { extern double y; } }\nint main(void) { return 0; }", 0, "");
valid!(linkage_accept_composite_array_length, "extern int a[]; extern int a[10];\nint main(void) { return 0; }", 0, "");
valid!(linkage_accept_redeclare_tentative, "int g; int g;\nint main(void) { return 0; }", 0, "");
valid!(linkage_accept_tentative_then_definition, "int h; int h = 1;\nint main(void) { return 0; }", 0, "");
valid!(linkage_accept_definition_then_tentative, "int i = 1; int i;\nint main(void) { return 0; }", 0, "");
valid!(linkage_accept_internal_tentative_then_definition, "static int j; static int j = 1;\nint main(void) { return 0; }", 0, "");
valid!(tentative_completed_later, "struct S; static struct S x; struct S { int i; };\nint main(void) { return 0; }", 0, "");
valid!(tentative_array_completed, "extern int a[]; int f(void) { return a[0]; } int a[1]; int main(void) { return f(); }", 0, "");
valid!(tentative_object_used, "static int sv; int f(void) { return sv; }\nint main(void) { return 0; }", 0, "");
valid!(internal_function_defined_then_used, "static int sf(void) { return 1; } int use(void) { return sf(); }\nint main(void) { return 0; }", 0, "");
valid!(internal_function_never_used, "static int sf(void); int use(void) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(internal_function_used_under_sizeof, "static int sf(void); int use(void) { return sizeof(&sf); }\nint main(void) { return 0; }", 0, "");
valid!(external_function_never_defined, "int ef(void); int use(void) { return ef(); }\nint main(void) { return 0; }\nint ef(void) { return 0; }", 0, "");
valid!(external_incomplete_array_declaration, "extern int a[]; int *p(void) { return a; }\nint main(void) { return 0; }\nint a[1];", 0, "");
valid!(placement_tentative_external, "int x; int read(void); int main(void) { x = 40; return read(); }", 42, "", files = &["extern int x; int read(void) { return x + 2; }"]);
valid!(placement_tentative_internal, "static int x = 40; int read(void); int main(void) { return x + read(); }", 42, "", files = &["int x = 2; int read(void) { return x; }"]);
valid!(placement_declaration_external, "extern int x; int main(void) { return x; }", 42, "", files = &["int x = 42;"]);
valid!(placement_definition_external, "int x = 40; int read(void); int main(void) { return read(); }", 42, "", files = &["extern int x; int read(void) { return x + 2; }"]);
valid!(placement_block_scope_mix, "void f(void) { int a; static int b; extern int c; }\nint main(void) { return 0; }", 0, "");
valid!(placement_static_then_definition_one_entry, "static int sf(void); int sf(void) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(placement_function_declaration_no_duration, "int fn(void);\nint main(void) { return 0; }", 0, "");
valid!(placement_function_definition_no_duration, "int fn(void) { return 0; }\nint main(void) { return 0; }", 0, "");
valid!(placement_static_function_definition_no_duration, "static int sfn(void) { return 40; } int read(void); int main(void) { return sfn() + read(); }", 42, "", files = &["int sfn(void) { return 2; } int read(void) { return sfn(); }"]);
invalid!(internal_function_never_defined, "static int sf(void); int use(void) { return sf(); }", &["error: 'sf' used but never defined"]);
invalid!(end_of_unit_diagnostic_order, "static int sf(void); struct S; static struct S x; int use(void) { return sf(); }", &["error: 'sf' used but never defined", "error: tentative definition has type 'struct S' that is never completed"]);
invalid!(linkage_reject_extern_then_static, "extern int a; static int a;", &["error: declaration of 'a' conflicts with the linkage of a previous declaration"]);
invalid!(linkage_reject_external_then_static, "int c; static int c;", &["error: declaration of 'c' conflicts with the linkage of a previous declaration"]);
invalid!(linkage_reject_static_then_external, "static int d; int d;", &["error: declaration of 'd' conflicts with the linkage of a previous declaration"]);
invalid!(linkage_reject_block_extern_then_file_static, "void f(void) { extern int x; } static int x;", &["error: declaration of 'x' conflicts with the linkage of a previous declaration"]);
invalid!(linkage_reject_function_then_static_definition, "int g(void); static int g(void) { return 0; }", &["error: declaration of 'g' conflicts with the linkage of a previous declaration"]);
invalid!(tentative_never_completed_external, "struct S; struct S x;", &["error: tentative definition has type 'struct S' that is never completed"]);
invalid!(tentative_never_completed_internal, "struct S; static struct S x;", &["error: tentative definition has type 'struct S' that is never completed"]);
invalid!(tentative_never_completed_used, "struct S; static struct S x; struct S *p(void) { return &x; }", &["error: tentative definition has type 'struct S' that is never completed"]);
invalid!(tentative_array_sizeof_before_completion, "int a[]; enum e { P = sizeof(a) };", &["error: invalid application of 'sizeof' to an incomplete type 'int[]'"]);
