#![cfg_attr(rustfmt, rustfmt_skip)]

invalid!(limit_incomplete_struct_array_unsized, "struct S; struct S a[] = { 1 };", &["error: array has incomplete or function element type 'struct S'", "error: excess elements in array initializer"]);
invalid!(limit_unnamed_bitfield_struct_array_unsized, "struct S { int : 3; } a[] = { 1 };", &["error: struct has no named member", "error: excess elements in array initializer"]);
invalid!(limit_incomplete_struct_array_of_arrays, "struct S; struct S a[][2] = { 1 };", &["error: array has incomplete or function element type 'struct S'", "error: excess elements in array initializer"]);
invalid!(limit_incomplete_struct_automatic_array, "struct S; int main(void) { struct S a[] = { 1, 2 }; return 0; }", &["error: array has incomplete or function element type 'struct S'", "error: excess elements in array initializer"]);
invalid!(limit_incomplete_struct_sized_array, "struct S; struct S a[3] = { 1, 2 };", &["error: array has incomplete or function element type 'struct S'", "error: excess elements in array initializer"]);
invalid!(limit_incomplete_struct_nested_braces, "struct S; struct S a[][2] = { { 1 }, { 2 } };", &["error: array has incomplete or function element type 'struct S'", "error: excess elements in array initializer", "error: excess elements in array initializer"]);
invalid!(limit_struct_over_two_gib, "struct S { char a[0x40000000]; char b[0x40000000]; };", &["error: struct is too large"]);
invalid!(limit_struct_over_four_gib, "struct S { char a[0x7fffffff]; char b[0x7fffffff]; char c[0x7fffffff]; };", &["error: struct is too large"], gcc_accepts = true);
invalid!(limit_struct_over_four_gib_with_sizeof, "struct S { char a[0x7fffffff]; char b[0x7fffffff]; char c[0x7fffffff]; }; int main(void) { return sizeof(struct S) & 255; }", &["error: struct is too large"], gcc_accepts = true);
invalid!(limit_union_just_over_two_gib, "union U { char a[0x7fffffff]; int i; };", &["error: union is too large"]);
invalid!(limit_struct_nested_over_two_gib, "struct A { char a[0x40000000]; }; struct B { struct A x; struct A y; };", &["error: struct is too large"]);
valid!(limit_struct_just_under_two_gib, "struct S { char a[0x7ffffff0]; int i; };\nint main(void) { return 0; }", 0, "");
valid!(limit_union_exactly_max, "union U { char a[0x7ffffffc]; int i; };\nint main(void) { return 0; }", 0, "");
valid!(limit_struct_size_near_max, "struct S { char a[0x7ffffff0]; int i; };\nint main(void) { return !(sizeof(struct S) == 0x7ffffff4); }", 0, "");
valid!(limit_huge_char_array_tail_is_compact, "char a[1048576] = { 1 }; int main(void) { return a[0] + a[1048575]; }", 1, "", max_size = 2000000, max_ir_size = 2000);
valid!(limit_int_array_tail_is_compact, "int buf[10000000] = { 1 }; int fixture_main(void) { return buf[0]; }\nint main(void) { return 0; }", 0, "", max_size = 64000000, max_ir_size = 100000);
valid!(limit_string_tail_is_compact, "static char s[50000000] = \"x\"; int fixture_main(void) { return s[0]; }\nint main(void) { return 0; }", 0, "", max_size = 64000000, max_ir_size = 100000);
valid!(limit_all_zero_array_is_zeroinitializer, "int z[200] = { 0 }; int fixture_main(void) { return z[0]; }\nint main(void) { return 0; }", 0, "", max_size = 64000000, max_ir_size = 100000);
valid!(limit_short_zero_tail_is_not_compacted, "int a[3] = { 1 }; int fixture_main(void) { return a[0]; }\nint main(void) { return 0; }", 0, "", max_size = 64000000, max_ir_size = 100000);
valid!(limit_tail_at_threshold_is_compact, "int a[65] = { 1 }; int fixture_main(void) { return a[0]; }\nint main(void) { return 0; }", 0, "", max_size = 64000000, max_ir_size = 100000);
valid!(limit_tail_below_threshold_is_expanded, "int a[64] = { 1 }; int fixture_main(void) { return a[0]; }\nint main(void) { return 0; }", 0, "", max_size = 64000000, max_ir_size = 100000);
valid!(limit_automatic_string_array_uses_aligned_constant, "int fixture_main(void) { char buf[100000] = \"x\"; return buf[0]; }\nint main(void) { return 0; }", 0, "", max_size = 64000000, max_ir_size = 100000);
valid!(limit_big_int_array_short_initializer, "int buf[1000000] = { 7 }; int main(void) { return buf[0] + buf[999999] + 1; }", 8, "");
valid!(limit_big_string_array_short_initializer, "static char s[100000] = \"x\"; int main(void) { return s[0] + s[99999] + s[1]; }", 120, "");
valid!(limit_big_wide_string_array, "long w[1000] = L\"ab\"; int main(void) { return w[0] + w[1] + w[2] + w[999]; }", 195, "");
valid!(limit_big_member_array_tail, "struct S { int a; char name[1000]; int tail[200]; short z; } g = { 1, \"hello\", { 1, 2, 3 }, 9 };\n     int main(void) { return g.a + g.name[1] + g.name[999] + g.tail[2] + g.tail[199] + g.z; }", 114, "");
valid!(limit_big_two_dimensional_array, "int m[100][100] = { { 1, 2 }, { 3 } }; int n[100][3] = { { 1 }, { 2 }, { 3 } };\n     int main(void) { return m[0][1] + m[1][0] + m[99][99] + n[2][0] + n[99][2] + m[1][1]; }", 8, "");
valid!(limit_big_array_of_structs_with_union_member, "union U { char c[300]; int i; }; struct T { int k; union U u; char tag[200]; };\n     struct T ts[100] = { { 1, { \"abc\" }, \"zz\" }, { 2 } };\n     int main(void) { return ts[0].k + ts[0].u.c[1] + ts[1].k + ts[0].tag[1] + ts[99].k + ts[1].u.c[0] + ts[50].tag[3]; }", 223, "");
valid!(limit_big_union_initialized_by_string, "union V { char c[300]; int i; } v = { \"q\" }; int main(void) { return v.c[0] + v.c[299]; }", 113, "");
valid!(limit_big_array_of_pointers_and_doubles, "char *pp[100] = { \"a\", 0 }; double dd[100] = { 1.5 };\n     int main(void) { return pp[0][0] + (int)dd[0] + (pp[1] == 0) + (dd[99] == 0.0); }", 100, "");
valid!(limit_big_array_of_bitfield_structs, "struct B { int a : 3; int b : 5; char x[100]; } bb[70] = { { 1, 2, \"hi\" } };\n     int main(void) { return bb[0].a + bb[0].b * 8 + bb[0].x[1] + bb[69].a + bb[69].x[99]; }", 122, "");
valid!(limit_unsized_array_keeps_exact_length, "int ex[] = { 1, 2, 3 }; int main(void) { return sizeof(ex); }", 12, "");
valid!(limit_unsized_string_array_keeps_exact_length, "char ex[] = \"abc\"; int main(void) { return sizeof(ex); }", 4, "");
valid!(limit_automatic_big_string_array, "int main(void) { char buf[100000] = \"x\"; int a[200] = { 5 }; struct { char s[100]; int v[100]; } t = { \"ab\", { 1 } };\n     return buf[0] + buf[99999] + a[0] + a[199] + t.s[1] + t.v[0] + t.v[99]; }", 224, "");
valid!(limit_huge_char_array_runs, "char a[1048576] = { 1 }; int main(void) { return a[0] + a[1048575]; }", 1, "", max_size = 2000000, max_ir_size = 2000);
invalid!(limit_fold_probe_cache_keeps_variable_array_size_error, "int x; int a[x];", &["error: Non constant expression"]);
invalid!(limit_fold_probe_cache_keeps_variable_array_size_after_cast, "int main(void) { int x = 1; int a[(int)(int)x]; return 0; }", &["error: Non constant expression"]);
invalid!(limit_fold_probe_cache_keeps_nonconstant_enumerator, "int x; enum { A = (int)(int)x };", &["error: Non constant expression"]);
invalid!(limit_fold_probe_cache_keeps_nonconstant_case, "int main(void) { int x = 1; switch (x) { case (int)(int)x: return 0; } return 1; }", &["error: Non constant expression"]);
valid!(depth_sum_at_the_limit, format!("int main(void) {{ return ({}) & 255; }}", vec!["1"; 32768].join("+")), 0, "", compile_timeout = std::time::Duration::from_secs(20));
valid!(depth_assign_at_the_limit, format!("int main(void) {{ int x; x = {}1; return x; }}", "x = ".repeat(32768)), 1, "", compile_timeout = std::time::Duration::from_secs(20));
invalid!(depth_sum_beyond_the_limit, format!("int main(void) {{ int x; x = {}1; return x; }}", "1+".repeat(150000)), &["error: expression nesting exceeds the implementation limit of 32768"], gcc_accepts = true, compile_timeout = std::time::Duration::from_secs(20));
invalid!(depth_assign_beyond_the_limit, format!("int main(void) {{ int x; x = {}1; return x; }}", "x = ".repeat(32771)), &["error: expression nesting exceeds the implementation limit of 32768"], gcc_accepts = true, compile_timeout = std::time::Duration::from_secs(20));
valid!(cast_chain_compiles_in_linear_time, format!("int main(void) {{ int x = 1; return {}x; }}", "(int)".repeat(20000)), 1, "", compile_timeout = std::time::Duration::from_secs(20));
valid!(null_pointer_constant_cast_chain_compiles_in_linear_time, format!("int main(void) {{ int *p = {}0; return p != 0; }}", "(int)".repeat(20000)), 0, "", compile_timeout = std::time::Duration::from_secs(20));
valid!(constant_cast_chain_compiles_in_linear_time, format!("enum {{ A = {}1 }}; int main(void) {{ return A; }}", "(int)".repeat(20000)), 1, "", compile_timeout = std::time::Duration::from_secs(20));
valid!(limit_string_concat_many_pieces_emits_one_literal, format!("char *p = {}; int main(void) {{ return !(p[0] == 97 && p[499] == 98 && p[500] == 0); }}", vec!["\"ab\""; 250].join(" ")), 0, "", max_size = 32768, max_ir_size = 5000, compile_timeout = std::time::Duration::from_secs(20));
valid!(parenthesis_nesting_c90_minimum, "int main(void) { return ((((((((((((((((((((((((((((((((1)))))))))))))))))))))))))))))))); }", 1, "");
